### ISSUE TITLE
Battery device: iCasa ICZB-KPD18S shows 200% battery

### ISSUE THREAD

**Issue by webnar** [Koenkk/zigbee2mqtt#12641]
### What happened?

The iCasa ICZB-KPD18S shows a battery life of 200% (switch firmware 2.7.6_r25)

![image](https://user-images.githubusercontent.com/7816672/170969605-d8c63e62-e86e-47a3-bc3b-e8ba74ac9a17.png)

### What did you expect to happen?

Showing 100% as my other switches do. (switch firmware: 2.5.3_r21)

![image](https://user-images.githubusercontent.com/7816672/170969754-76108718-783e-434c-8a45-93a75e3e3229.png)

### Zigbee2MQTT version

1.25.1

### Adapter firmware version

20211217

### Adapter

Sonoss

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by webnar** [comment]
Thanks, But i'm still seeing the 200%

![image](https://user-images.githubusercontent.com/7816672/171061808-7f6a715d-0169-48d1-beb5-6d40ea17b66c.png)

![image](https://user-images.githubusercontent.com/7816672/171061853-2c30903a-34f5-4abe-9511-0763fa885a81.png)

**Comment by Koenkk** [comment]
@webnar it can take some time before the device reports a new battery value
