### ISSUE TITLE
[New device support]: Orvibo DS20Z - Zigbee Model ccb9f56837ab41dcad366fb1452096b6

### ISSUE THREAD

**Issue by hirzel23** [Koenkk/zigbee2mqtt#13123]
### Link

https://orvibo.ae/downlight/

### Database entry

const definition = { 	zigbeeModel: ['ccb9f56837ab41dcad366fb1452096b6'], 	model: 'ccb9f56837ab41dcad366fb1452096b6', 	vendor: 'ORVIBO', 	description: 'ORVIBO Smart Spotlight', 	extend: extend.light_onoff_brightness_colortemp({colorTempRange: [153, 370]}), };

### Comments

Paired device to sonoff zigbee 3.0 usb dongle plus - paired successfully but not supported

Create ccb9f56837ab41dcad366fb1452096b6.js in zigbee2mqtt folder and external converters has been added in zigbee2mqtt configuration file as follow:

```
external_converters:
  - ccb9f56837ab41dcad366fb1452096b6.js
```

here is my current configuration in ccb9f56837ab41dcad366fb1452096b6.js

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
	zigbeeModel: ['ccb9f56837ab41dcad366fb1452096b6'],
	model: 'ccb9f56837ab41dcad366fb1452096b6',
	vendor: 'ORVIBO',
	description: 'ORVIBO Smart Spotlight',
	extend: extend.light_onoff_brightness_colortemp({colorTempRange: [153, 370]}),
};

module.exports = definition;
```

I'm quite new in HA, after I added and run the toggle it shows error 

> No converter available for 'state' ("OFF")
> No converter available for 'state' ("ON")
> No converter available for 'brightness' (13)
> ...

are there anyone can help for this issue? Please Help

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
	zigbeeModel: ['ccb9f56837ab41dcad366fb1452096b6'],
	model: 'ccb9f56837ab41dcad366fb1452096b6',
	vendor: 'ORVIBO',
	description: 'ORVIBO Smart Spotlight',
	extend: extend.light_onoff_brightness_colortemp({colorTempRange: [153, 370]}),
};

module.exports = definition;
```

### Supported color modes

onoff_brightness_colortemp

### Color temperature range

probably 166 to 370, I don't have the exact information yet

**Comment by hirzel23** [comment]
here is the debug log when I try to adjust the brightness down

> groupID 0
> Debug 2022-07-14 11:41:52No converter available for 'ccb9f56837ab41dcad366fb1452096b6' with cluster '65280' and type 'attributeReport' and data '{"0":"0x80b300a600000000"}'
> Debug 2022-07-14 11:41:53Received MQTT message on 'zigbee2mqtt/0x4730000025092188/set' with data '{"brightness":8}'
> Debug 2022-07-14 11:41:53Publishing 'set' 'brightness' to '0x4730000025092188'
> Info 2022-07-14 11:41:53MQTT publish: topic 'zigbee2mqtt/0x4730000025092188', payload '{"brightness":8,"color_mode":"color_temp","color_temp":166,"linkquality":69,"state":"ON"}'
> Debug 2022-07-14 11:41:53Received Zigbee message from '0x4730000025092188', type 'attributeReport', cluster '65280', data '{"0":"0x80b300a600000000"}' from endpoint 1 with groupID 0

**Comment by Koenkk** [comment]
Could you provide me the herdsman debug logging when changing the brightness?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by hirzel23** [comment]
> Could you provide me the herdsman debug logging when changing the brightness?
> 
> See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

Hi Koen, thanks for your help. here is the log file

[Debug log herdsman - Orvibo DS20Z - 07262022.txt]
(https://github.com/Koenkk/zigbee2mqtt/files/9185724/Debug.log.herdsman.-.Orvibo.DS20Z.-.07262022.txt)

**Comment by Koenkk** [comment]
Can you check if it works with the converter below and provide the herdsman debug logging again?

``
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const tzLocal = {
    brightness: {
        key: ['brightness'],
        options: [exposes.options.transition()],
        convertSet: async (entity, key, value, meta) => {
            await entity.command(
                'genLevelCtrl',
                'moveToLevel',
                {level: Number(value), transtime: 0},
                utils.getOptions(meta.mapped, entity),
            );

            return {state: {brightness: value}};
        },
    },
}

const definition = {
	zigbeeModel: ['ccb9f56837ab41dcad366fb1452096b6'],
	model: 'ccb9f56837ab41dcad366fb1452096b6',
	vendor: 'ORVIBO',
	description: 'ORVIBO Smart Spotlight',
    toZigbee: [tz.on_off, tzLocal.brightness],
	extend: extend.light_onoff_brightness_colortemp({colorTempRange: [153, 370]}),
};

module.exports = definition;
```

**Comment by hirzel23** [comment]
Hi Koen, I got error message from when changing the brightness shows "utils not defined"
here are the screenshot and the debug log
[Debug log herdsman - Orvibo DS20Z - 07272022.txt](https://github.com/Koenkk/zigbee2mqtt/files/9194011/Debug.log.herdsman.-.Orvibo.DS20Z.-.07272022.txt)

![7-27-2022 7-09-23 AM](https://user-images.githubusercontent.com/97104121/181133817-47f6ed12-4464-4154-913e-92f01e17efed.png)

**Comment by Koenkk** [comment]
I updated https://github.com/Koenkk/zigbee2mqtt/issues/13123#issuecomment-1195564194, can you try again?

**Comment by hirzel23** [comment]
Hi Koen, the brightness is working with the brightness that I set, but seems I got some errors on z2m console here are the log and screenshots

[Debug log herdsman - Orvibo DS20Z - 07282022.txt](https://github.com/Koenkk/zigbee2mqtt/files/9201481/Debug.log.herdsman.-.Orvibo.DS20Z.-.07282022.txt)

![7-28-2022 12-43-31 AM](https://user-images.githubusercontent.com/97104121/181330003-812cc061-4294-49ad-a54d-46b5a4a57434.png)
![7-28-2022 12-41-25 AM](https://user-images.githubusercontent.com/97104121/181330181-14b195da-df46-4ef7-87f0-2b3844227ed4.png)

I also got slightly delay when I change the brightness multiple times.

**Comment by hirzel23** [comment]
sorry and also here is the configuration

![7-28-2022 12-32-18 AM](https://user-images.githubusercontent.com/97104121/181340489-7c75c269-b37c-453e-acab-a494637a02a2.png)

I got some warning on some line

**Comment by Koenkk** [comment]
I've updated https://github.com/Koenkk/zigbee2mqtt/issues/13123#issuecomment-1195564194, can you check if the errors are gone now when setting the brightness.

> I got some warning on some line

This can be ignored

**Comment by hirzel23** [comment]
Hi Koen,

The error is gone now, fully responsive, no error and fully functional.

Thanks a lot for your help and really appreciated.

**Comment by hirzel23** [comment]
Hi Koen,

The error is gone now, fully responsive, logs also no showing any error and fully functional.

Thanks a lot for your help and really appreciated.

**Comment by Koenkk** [comment]
Great, added the device!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by hirzel23** [comment]
Hi Koen,

Sorry to bother you again, this morning I did my test again with the color temperature. it seems showing error as follow

[Debug log herdsman - Orvibo DS20Z - 07292022.txt]

(https://gith
![7-29-2022 8-32-02 AM](https://user-images.githubusercontent.com/97104121/181664441-acfaa7cc-67db-4611-86a7-20ae0e256637.png)
ub.com/Koenkk/zigbee2mqtt/files/9215324/Debug.log.herdsman.-.Orvibo.DS20Z.-.07292022.txt)

the brightness still ok

**Comment by Koenkk** [comment]
I updated https://github.com/Koenkk/zigbee2mqtt/issues/13123#issuecomment-1195564194 this should fix it.

**Comment by hirzel23** [comment]
> 

Hi Koen,

Thanks for your update. I have update the js as follow:
![7-29-2022 11-42-05 PM](https://user-images.githubusercontent.com/97104121/181806925-cb67ea89-7c32-4cce-97f7-d794d0646037.png)

After I update it seems the color temperature did not work and showing error as follow
![7-29-2022 11-42-47 PM](https://user-images.githubusercontent.com/97104121/181807427-9dde84ee-a3b0-4506-a905-8c1b09d9ea68.png)

here is the log file
[Debug.log.herdsman.-.Orvibo.DS20Z.-.07292022.2.txt](https://github.com/Koenkk/zigbee2mqtt/files/9221895/Debug.log.herdsman.-.Orvibo.DS20Z.-.07292022.2.txt)

Am I use the correct js code? please cmiiw

**Comment by hirzel23** [comment]
I also try the second test use orvibo.js file

here is the part of the js code
![7-29-2022 11-44-27 PM](https://user-images.githubusercontent.com/97104121/181808080-bb3ae50c-e858-4af4-9551-49759edcb3fb.png)

Also showing error and the color temperature also not change
![7-29-2022 11-46-39 PM](https://user-images.githubusercontent.com/97104121/181808213-f24a8a3e-4034-480a-9617-4fd63df80fb9.png)

here is the log file
[Debug.log.herdsman.-.Orvibo.DS20Z.-.07292022.3.txt](https://github.com/Koenkk/zigbee2mqtt/files/9221946/Debug.log.herdsman.-.Orvibo.DS20Z.-.07292022.3.txt)

I try both, not sure which one is better. really need your suggestion 😄

**Comment by Koenkk** [comment]
Should be fixed with https://github.com/Koenkk/zigbee2mqtt/issues/13123#issuecomment-1195564194

**Comment by hirzel23** [comment]
> Should be fixed with [#13123 (comment)](https://github.com/Koenkk/zigbee2mqtt/issues/13123#issuecomment-1195564194)

Hi Koen,

It seems still not found the converter
![7-30-2022 4-10-45 PM](https://user-images.githubusercontent.com/97104121/181903869-556e9c38-3144-4b3c-b78c-eab9e9d3cb2e.png)

![7-30-2022 4-11-29 PM](https://user-images.githubusercontent.com/97104121/181903877-459712da-ad82-4674-8ac3-e68d92b0ed40.png)

Here is the log
[Debug log herdsman - Orvibo DS20Z - 07302022.txt](https://github.com/Koenkk/zigbee2mqtt/files/9225881/Debug.log.herdsman.-.Orvibo.DS20Z.-.07302022.txt)

**Comment by Koenkk** [comment]
Are you sure you restarted z2m after updating the converter?

**Comment by hirzel23** [comment]
> Are you sure you restarted z2m after updating the converter?

Hi Koen,

Yes, I restart z2m every time after updated converter. I also restart the HA but still the same error

**Comment by hirzel23** [comment]
Hi Koen,

Sorry I just miss the z2m config on z2m ui config for external converter 
. After update there now all working fine now
![image](https://user-images.githubusercontent.com/97104121/181925390-e7ecec60-c624-422d-86dd-2e17b922c1ae.jpeg)

Thanks a lot Koen
