### ISSUE TITLE
CC2530/CC2531 Router always appears as disconnected

### ISSUE THREAD

**Issue by glentakahashi** [Koenkk/zigbee2mqtt#1418]
# Bug Report
## What happened
The CC2530 router always shows as disconnected in home assistant, even though the device is pinging alive every 60 seconds.

I see this in logs:
```
zigbee2mqtt      |   zigbee2mqtt:info 4/13/2019, 2:55:36 AM MQTT publish: topic 'zigbee2mqtt/0x00124b0014d9d4fa', payload '{"state":false,"linkquality":47,"last_seen":"2019-04-13T02:55:36.539Z","device":{"ieeeAddr":"0x00124b0014d9d4fa","friendlyName":"0x00124b0014d9d4fa","type":"Router","nwkAddr":61243,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.router","status":"online"},"elapsed":59991}'
```

The `status` is `online`, yet the `state` variable says it's `false`, which is what homeassistant goes off of.

I also have `availability_timeout` set to 60, and am still seeing the issue.
## Debug Info
zigbee2mqtt version: latest as of 2019-04-12
CC253X firmware version:  latest as of 2019-04-12

**Comment by Koenkk** [comment]
The state does represent the LED state, not the disconnected/connected state.

**Comment by glentakahashi** [comment]
Hmm, should this be set to `status` then? And change the payload_on and payload_off? https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/homeassistant.js#L84

This is what i see in HA.

![Screenshot 2019-04-14 09 43 462](https://user-images.githubusercontent.com/1022767/56093710-05652500-5e9a-11e9-87f4-0241bdbc17ef.png)

**Comment by Koenkk** [comment]
This is indeed highly misleading, could you update the HA integration?

**Comment by Woodpeckercz** [comment]
I have the same problem, I use two CC2530 routers and they are constantly shown as offline.

**Comment by jasimancas** [comment]
Same here

**Comment by dr-apple** [comment]
Hello ich have the same with all my routers :-(

MQTT publish: topic 'zigbee2mqtt/0x00124b0018e207bc', payload '{"state":false,"linkquality":170}'

**Comment by Filipe-Figueiredo** [comment]
Hello,
I have the same problem:

![image](https://user-images.githubusercontent.com/1395962/58695378-28d22980-838d-11e9-8a54-77ee710cf185.png)

Link Quality is ok, but the device appears to be offline.

**Comment by Koenkk** [comment]
This should already be fixed in the latest dev branch.

**Comment by stepanov1975** [comment]
Sorry, but I still don't understand. When router status is offline is it a bug? If not, is this mean that router not working? And what should I do to fix this?

**Comment by Koenkk** [comment]
The state means the led state, not the online/offline state, your router is probably working.
