### ISSUE TITLE
Xiaomi ZNCZ04LM energy monitoring does not working with Sonoff Dongle -E 

### ISSUE THREAD

**Issue by artlov** [Koenkk/zigbee2mqtt#14299]
### What happened?

Power, energy, device temperature, voltage , current, consumer_connected - all they with status Null. 
When try to refresh power, error generated:
2022-10-03 11:57:36 Publish 'get' 'power' to '0x04cf8cdf3c7e3215' failed: 'TypeError: Cannot read properties of undefined (reading 'read')'

### Zigbee2MQTT version

1.28.0-1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

### Debug log
Debug 2022-10-03 12:15:42 Received MQTT message on 'zigbee2mqtt2/0x04cf8cdf3c7e3215/get' with data '{"power":""}'
Debug 2022-10-03 12:15:42 Publishing get 'get' 'power' to '0x04cf8cdf3c7e3215'
Error 2022-10-03 12:15:42 Publish 'get' 'power' to '0x04cf8cdf3c7e3215' failed: 'TypeError: Cannot read properties of undefined (reading 'read')'
Debug 2022-10-03 12:15:42 TypeError: Cannot read properties of undefined (reading 'read') at Object.convertGet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:2263:28) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:273:37) at EventEmitter.emit (node:events:539:35) at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22) at MQTT.onMessage (/app/lib/mqtt.ts:140:27) at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:94:27) at WebSocket.emit (node:events:527:28) at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1178:20) at Receiver.emit (node:events:527:28) at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:528:14)
Info 2022-10-03 12:15:42 MQTT publish: topic 'zigbee2mqtt2/bridge/log', payload '{"message":"Publish 'get' 'power' to '0x04cf8cdf3c7e3215' failed: 'TypeError: Cannot read properties of undefined (reading 'read')'","meta":{"friendly_name":"0x04cf8cdf3c7e3215"},"type":"zigbee_publish_error"}'

**Comment by cfluegel** [comment]
I have the same issue. I get no information from the power plug. The firmware of my ZNCZ04LM is 01-23-2022. It seems to be a "problem" with the firmware because another power plug with the same coordinator works flawlessly. 

I can guess the answer but I hopeful that I am wrong. There is no way of downgrading a firmware, right? 

The coordinator revision is 20210708. Would it be helpful to update my coordinator usb stick?

**Comment by hugocib** [comment]
I report the same issue after updating OTA to the 01-23-2022 firmware

**Comment by Slayer-24** [comment]
Same issue here. Is there still no option to downgrade the firmware?

**Comment by sfiel** [comment]
I needed to upgrade the firmware of the coordinator USB stick and then everything was working fine again. HowTos can also be found on the [zigbee2mqtt homepage](https://www.zigbee2mqtt.io/guide/adapters/)

**Comment by cfluegel** [comment]
That sounds great. Could you post the release date of the firmware that worked for you?  The version I tested two weeks ago did not work and I want to make sure I use the same release for my adapter.

**Comment by cfluegel** [comment]
Thank you my friends. Indeed it is working with the newest (20220219) firmware. It seems I forgot to remove the power adapter from my network, but it seems that is necessary. So, update your coordinator; remove the zigbee device from zigbee2mqtt and re-add it.

**Comment by Slayer-24** [comment]
Thank you all, I did replace my old CC2531 with a Sonoff CC2653P (with latest FW). After re-join everything works fine.

**Comment by artlov** [comment]
Problem solved with the last Zigbee2mqtt version.  Closing.

**Comment by gyraksi** [comment]
I still have this issue with another coordinator as well. My coordinator is tindie zzh! CC2652R Multiprotocol RF Stick with firmware zStack3x0 revision 20210120. The ZNCZ04LM Mi Power Plug firmware is 01-23-2022.
