### ISSUE TITLE
TS011F_plug_1 has no OTA "Firmware build date" and "Firmware version".

### ISSUE THREAD

**Issue by thierrybla** [Koenkk/zigbee2mqtt#16421]
### What happened?

My Tuya plug is seen and works correctly.
I want to update them but it shows the devices with no "Firmware build date" and no "Firmware version".

When I click on "Check for update" it says: "No update available for 'device'".

Is this just a UI bug? Does the update system work but it's not showing the version?

![image](https://user-images.githubusercontent.com/28044044/215430730-6df1a7b8-6e54-49fe-9cd3-34153caad5d6.png)

### What did you expect to happen?

Show the correct "Firmware build date" and "Firmware version".

### How to reproduce it (minimal and precise)

Add a TS011F_plug_1 to Zigbee2Mqtt and look at the OTA tab.

### Zigbee2MQTT version

1.29.2

### Adapter firmware version

20210708

### Adapter

SONOFF ZB Dongle-P USB Dongle Plus

### Debug log

Zigbee2MQTT:debug 2023-01-30 09:55:02: Received MQTT message on 'zigbee2mqtt/bridge/request/device/ota_update/check' with data '{"id":"Dishwasher plug","transaction":"giiv4-45"}'
Zigbee2MQTT:info  2023-01-30 09:55:02: Checking if update available for 'Dishwasher plug'
Zigbee2MQTT:debug 2023-01-30 09:55:02: Check if update available for '0xa4c13873c86da4c5' (TS011F)
Zigbee2MQTT:debug 2023-01-30 09:55:02: Using endpoint '1'
Zigbee2MQTT:debug 2023-01-30 09:55:02: Received Zigbee message from 'Dishwasher plug', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":192,"imageType":54179,"manufacturerCode":4417}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2023-01-30 09:55:02: MQTT publish: topic 'zigbee2mqtt/Dishwasher plug', payload '{"child_lock":"UNLOCK","current":0,"energy":108.57,"indicator_mode":"off/on","last_seen":"2023-01-30T09:55:02+01:00","linkquality":54,"power":0,"power_outage_memory":"on","state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":null,"voltage":232}'
Zigbee2MQTT:debug 2023-01-30 09:55:02: Got OTA request '{"fieldControl":0,"manufacturerCode":4417,"imageType":54179,"fileVersion":192}'
Zigbee2MQTT:debug 2023-01-30 09:55:02: ZigbeeOTA: downloaded main index
Zigbee2MQTT:debug 2023-01-30 09:55:02: Is new image available for '0xa4c13873c86da4c5', current '{"fieldControl":0,"manufacturerCode":4417,"imageType":54179,"fileVersion":192}', latest meta '{"fileVersion":192,"fileSize":307682,"url":"https://images.tuyaeu.com/smart/firmware/upgrade/20220907/1662545193-oem_zg_tl8258_plug_OTA_3.0.0.bin","sha512":"01939ca4fc790432d2c233e19b2440c1e0248d2ce85c9299e0b88928cb2341de675350ac7b78187a25f06a2768f93db0a17c4ba950b60c82c072e0c0833cfcfb"}'
Zigbee2MQTT:debug 2023-01-30 09:55:02: Update available for '0xa4c13873c86da4c5': NO
Zigbee2MQTT:info  2023-01-30 09:55:02: No update available for 'Dishwasher plug'
Zigbee2MQTT:info  2023-01-30 09:55:02: MQTT publish: topic 'zigbee2mqtt/Dishwasher plug', payload '{"child_lock":"UNLOCK","current":0,"energy":108.57,"indicator_mode":"off/on","last_seen":"2023-01-30T09:55:02+01:00","linkquality":54,"power":0,"power_outage_memory":"on","state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":null,"voltage":232}'
Zigbee2MQTT:info  2023-01-30 09:55:02: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"Dishwasher plug","updateAvailable":false},"status":"ok","transaction":"giiv4-45"}'
Zigbee2MQTT:debug 2023-01-30 09:55:07: Received Zigbee message from 'Livingroom motion sensor', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":20318}' from endpoint 2 with groupID 0

**Comment by janb14** [comment]
Can confirm, they can be updated but dont show their versions in gui. Maybe it has to do with the update. When viewing the state in gui, they didnt show any firmware details. After the update they did but only in the state tab, not the OTA section. Maybe some database entry needs to be updated or general version string parsing is missing.

**Comment by tetsuo55** [comment]
I can confirm also

**Comment by Impact123** [comment]
Unstale

**Comment by tjorim** [comment]
Seeing the same here, Zigbee2MQTT version 1.30.4.
However, I was able to update the firmware of the smart plugs I received.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/1294876/aa5ecbcc-b285-411e-a7c4-4a3d7141444a)

**Comment by vincele** [comment]
+2
I cannot see the version, but a manual check and update "worked" (on the 20A).

* Zigbee Model: TS011F
* SONOFF ZB Dongle-P USB Dongle Plus
* Zigbee Manufacturer: _TZ3000_hdopuwv6 (16A-rated model)
* Zigbee Manufacturer: _TZ3000_gvn91tmx (20A-rated model)

**Comment by Impact123** [comment]
Unstale.

**Comment by tetsuo55** [comment]
Unstaie

**Comment by tjorim** [comment]
Still present in Zigbee2MQTT version 1.33.0.

**Comment by Impact123** [comment]
Unstale.

**Comment by chemuki205** [comment]
I confirm


**Zigbee2MQTT version**
[1.33.2] commit: [9996c93]

**Adapter firmware version**
20230507

**Adapter**
SONOFF ZB Dongle-P USB Dongle Plus

![image](https://github.com/Koenkk/zigbee2mqtt/assets/62309618/f440ddc7-4ab5-4056-9535-261ce7e64777)

**After Check updates...**
```
info  2023-11-21 23:33:01: Checking if update available for 'Enchufe_lavavajillas'
info  2023-11-21 23:33:01: Checking if update available for 'Llave_general_agua'
info  2023-11-21 23:33:01: Checking if update available for 'Enchufe_garaje'
info  2023-11-21 23:33:01: Update available for 'Enchufe_lavavajillas'
info  2023-11-21 23:33:01: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"Enchufe_lavavajillas","updateAvailable":true},"status":"ok","transaction":"3rwx8-16"}'
info  2023-11-21 23:33:02: Update available for 'Enchufe_garaje'
info  2023-11-21 23:33:02: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"Enchufe_garaje","updateAvailable":true},"status":"ok","transaction":"3rwx8-18"}'
info  2023-11-21 23:33:02: Update available for 'Llave_general_agua'
info  2023-11-21 23:33:02: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"Llave_general_agua","updateAvailable":true},"status":"ok","transaction":"3rwx8-17"}'
```


![image](https://github.com/Koenkk/zigbee2mqtt/assets/62309618/4c771eb1-62f8-4ded-801d-f3c8edde8cf7)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/62309618/a23dc15f-6abe-41cd-8713-27d693d875b3)

**Updating Enchufe_garaje**

```
Info 2023-11-21 23:50:51Updating 'Enchufe_garaje' to latest firmware
Info 2023-11-21 23:50:52Update of 'Enchufe_garaje' at 24.78%, ≈ 0 minutes remaining
Info 2023-11-21 23:50:52MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":24.78,"remaining":0,"state":"updating"},"update_available":null,"voltage":225}'
Info 2023-11-21 23:51:22Update of 'Enchufe_garaje' at 26.47%, ≈ 1 minutes remaining
Info 2023-11-21 23:51:22MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":26.47,"remaining":84,"state":"updating"},"update_available":null,"voltage":225}'
Info 2023-11-21 23:51:52Update of 'Enchufe_garaje' at 28.24%, ≈ 3 minutes remaining
Info 2023-11-21 23:51:52MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":28.24,"remaining":153,"state":"updating"},"update_available":null,"voltage":224}'
Info 2023-11-21 23:52:22Update of 'Enchufe_garaje' at 30.03%, ≈ 4 minutes remaining
Info 2023-11-21 23:52:22MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":30.03,"remaining":211,"state":"updating"},"update_available":null,"voltage":224}'
Info 2023-11-21 23:52:53Update of 'Enchufe_garaje' at 31.82%, ≈ 4 minutes remaining
Info 2023-11-21 23:52:53MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":31.82,"remaining":259,"state":"updating"},"update_available":null,"voltage":224}'
Info 2023-11-21 23:53:23Update of 'Enchufe_garaje' at 33.61%, ≈ 5 minutes remaining
Info 2023-11-21 23:53:23MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":112,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":33.61,"remaining":298,"state":"updating"},"update_available":null,"voltage":224}'
Info 2023-11-21 23:53:53Update of 'Enchufe_garaje' at 35.39%, ≈ 6 minutes remaining
Info 2023-11-21 23:53:53MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":112,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":35.39,"remaining":331,"state":"updating"},"update_available":null,"voltage":224}'
Info 2023-11-21 23:54:23Update of 'Enchufe_garaje' at 37.18%, ≈ 6 minutes remaining
Info 2023-11-21 23:54:23MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":37.18,"remaining":357,"state":"updating"},"update_available":null,"voltage":224}'
Info 2023-11-21 23:54:54Update of 'Enchufe_garaje' at 38.97%, ≈ 6 minutes remaining
Info 2023-11-21 23:54:54MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":112,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":38.97,"remaining":378,"state":"updating"},"update_available":null,"voltage":224}'
Info 2023-11-21 23:55:24Update of 'Enchufe_garaje' at 40.76%, ≈ 7 minutes remaining
Info 2023-11-21 23:55:24MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":112,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":40.76,"remaining":395,"state":"updating"},"update_available":null,"voltage":224}'
Info 2023-11-21 23:55:54Update of 'Enchufe_garaje' at 42.54%, ≈ 7 minutes remaining
Info 2023-11-21 23:55:54MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":42.54,"remaining":408,"state":"updating"},"update_available":null,"voltage":224}'
Info 2023-11-21 23:56:24Update of 'Enchufe_garaje' at 44.33%, ≈ 7 minutes remaining
Info 2023-11-21 23:56:24MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":44.33,"remaining":417,"state":"updating"},"update_available":null,"voltage":224}'
Info 2023-11-21 23:56:54Update of 'Enchufe_garaje' at 46.12%, ≈ 7 minutes remaining
Info 2023-11-21 23:56:54MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":46.12,"remaining":424,"state":"updating"},"update_available":null,"voltage":226}'
Info 2023-11-21 23:57:25Update of 'Enchufe_garaje' at 47.91%, ≈ 7 minutes remaining
Info 2023-11-21 23:57:25MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":47.91,"remaining":427,"state":"updating"},"update_available":null,"voltage":226}'
Info 2023-11-21 23:57:55Update of 'Enchufe_garaje' at 49.69%, ≈ 7 minutes remaining
Info 2023-11-21 23:57:55MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":49.69,"remaining":428,"state":"updating"},"update_available":null,"voltage":226}'
Info 2023-11-21 23:58:25Update of 'Enchufe_garaje' at 51.48%, ≈ 7 minutes remaining
Info 2023-11-21 23:58:25MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":51.48,"remaining":427,"state":"updating"},"update_available":null,"voltage":226}'
Info 2023-11-21 23:58:55Update of 'Enchufe_garaje' at 53.27%, ≈ 7 minutes remaining
Info 2023-11-21 23:58:55MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":53.27,"remaining":424,"state":"updating"},"update_available":null,"voltage":226}'
Info 2023-11-21 23:59:26Update of 'Enchufe_garaje' at 55.06%, ≈ 7 minutes remaining
Info 2023-11-21 23:59:26MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":55.06,"remaining":419,"state":"updating"},"update_available":null,"voltage":226}'
Info 2023-11-21 23:59:56Update of 'Enchufe_garaje' at 56.84%, ≈ 7 minutes remaining
Info 2023-11-21 23:59:56MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":56.84,"remaining":413,"state":"updating"},"update_available":null,"voltage":226}'
Info 2023-11-22 00:00:26Update of 'Enchufe_garaje' at 58.63%, ≈ 7 minutes remaining
Info 2023-11-22 00:00:26MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":120,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":58.63,"remaining":405,"state":"updating"},"update_available":null,"voltage":226}'
Info 2023-11-22 00:00:56Update of 'Enchufe_garaje' at 60.42%, ≈ 7 minutes remaining
Info 2023-11-22 00:00:56MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":109,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":60.42,"remaining":396,"state":"updating"},"update_available":null,"voltage":228}'
Info 2023-11-22 00:01:26Update of 'Enchufe_garaje' at 62.21%, ≈ 6 minutes remaining
Info 2023-11-22 00:01:26MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":62.21,"remaining":386,"state":"updating"},"update_available":null,"voltage":228}'
Info 2023-11-22 00:01:57Update of 'Enchufe_garaje' at 63.99%, ≈ 6 minutes remaining
Info 2023-11-22 00:01:57MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":63.99,"remaining":374,"state":"updating"},"update_available":null,"voltage":227}'
Info 2023-11-22 00:02:27Update of 'Enchufe_garaje' at 65.78%, ≈ 6 minutes remaining
Info 2023-11-22 00:02:27MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":65.78,"remaining":362,"state":"updating"},"update_available":null,"voltage":227}'
Info 2023-11-22 00:02:57Update of 'Enchufe_garaje' at 67.57%, ≈ 6 minutes remaining
Info 2023-11-22 00:02:57MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":120,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":67.57,"remaining":348,"state":"updating"},"update_available":null,"voltage":227}'
Info 2023-11-22 00:03:27Update of 'Enchufe_garaje' at 69.36%, ≈ 6 minutes remaining
Info 2023-11-22 00:03:27MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":69.36,"remaining":334,"state":"updating"},"update_available":null,"voltage":227}'
Info 2023-11-22 00:03:57Update of 'Enchufe_garaje' at 71.14%, ≈ 5 minutes remaining
Info 2023-11-22 00:03:57MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":112,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":71.14,"remaining":319,"state":"updating"},"update_available":null,"voltage":227}'
Info 2023-11-22 00:04:28Update of 'Enchufe_garaje' at 72.93%, ≈ 5 minutes remaining
Info 2023-11-22 00:04:28MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":120,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":72.93,"remaining":303,"state":"updating"},"update_available":null,"voltage":227}'
Info 2023-11-22 00:04:58Update of 'Enchufe_garaje' at 74.72%, ≈ 5 minutes remaining
Info 2023-11-22 00:04:58MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":74.72,"remaining":286,"state":"updating"},"update_available":null,"voltage":227}'
Info 2023-11-22 00:05:28Update of 'Enchufe_garaje' at 76.51%, ≈ 4 minutes remaining
Info 2023-11-22 00:05:28MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":76.51,"remaining":269,"state":"updating"},"update_available":null,"voltage":227}'
Info 2023-11-22 00:05:58Update of 'Enchufe_garaje' at 78.08%, ≈ 4 minutes remaining
Info 2023-11-22 00:05:58MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":120,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":78.08,"remaining":254,"state":"updating"},"update_available":null,"voltage":227}'
Info 2023-11-22 00:06:29Update of 'Enchufe_garaje' at 79.87%, ≈ 4 minutes remaining
Info 2023-11-22 00:06:29MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":79.87,"remaining":236,"state":"updating"},"update_available":null,"voltage":227}'
Info 2023-11-22 00:06:59Update of 'Enchufe_garaje' at 81.64%, ≈ 4 minutes remaining
Info 2023-11-22 00:06:59MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":81.64,"remaining":217,"state":"updating"},"update_available":null,"voltage":225}'
Info 2023-11-22 00:07:29Update of 'Enchufe_garaje' at 83.43%, ≈ 3 minutes remaining
Info 2023-11-22 00:07:29MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":83.43,"remaining":198,"state":"updating"},"update_available":null,"voltage":225}'
Info 2023-11-22 00:07:59Update of 'Enchufe_garaje' at 85.22%, ≈ 3 minutes remaining
Info 2023-11-22 00:07:59MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":85.22,"remaining":178,"state":"updating"},"update_available":null,"voltage":225}'
Info 2023-11-22 00:08:29Update of 'Enchufe_garaje' at 87.01%, ≈ 3 minutes remaining
Info 2023-11-22 00:08:29MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":87.01,"remaining":158,"state":"updating"},"update_available":null,"voltage":225}'
info  2023-11-22 00:08:29: Update of 'Enchufe_garaje' at 87.01%, ≈ 3 minutes remaining
info  2023-11-22 00:08:29: MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":87.01,"remaining":158,"state":"updating"},"update_available":null,"voltage":225}'
info  2023-11-22 00:08:59: Update of 'Enchufe_garaje' at 88.79%, ≈ 2 minutes remaining
info  2023-11-22 00:08:59: MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":112,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":88.79,"remaining":137,"state":"updating"},"update_available":null,"voltage":225}'
info  2023-11-22 00:09:29: Update of 'Enchufe_garaje' at 90.58%, ≈ 2 minutes remaining
info  2023-11-22 00:09:29: MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":120,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":90.58,"remaining":116,"state":"updating"},"update_available":null,"voltage":225}'
info  2023-11-22 00:10:00: Update of 'Enchufe_garaje' at 92.37%, ≈ 2 minutes remaining
info  2023-11-22 00:10:00: MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":92.37,"remaining":95,"state":"updating"},"update_available":null,"voltage":222}'
info  2023-11-22 00:10:30: Update of 'Enchufe_garaje' at 94.16%, ≈ 1 minutes remaining
info  2023-11-22 00:10:30: MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":120,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":94.16,"remaining":73,"state":"updating"},"update_available":null,"voltage":222}'
info  2023-11-22 00:11:00: Update of 'Enchufe_garaje' at 95.94%, ≈ 1 minutes remaining
info  2023-11-22 00:11:00: MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":95.94,"remaining":51,"state":"updating"},"update_available":null,"voltage":222}'
info  2023-11-22 00:11:30: Update of 'Enchufe_garaje' at 97.73%, ≈ 0 minutes remaining
info  2023-11-22 00:11:30: MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":97.73,"remaining":29,"state":"updating"},"update_available":null,"voltage":222}'
info  2023-11-22 00:12:00: Update of 'Enchufe_garaje' at 99.50%, ≈ 0 minutes remaining
info  2023-11-22 00:12:00: MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":120,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":99.5,"remaining":6,"state":"updating"},"update_available":null,"voltage":225}'
info  2023-11-22 00:12:09: Update of 'Enchufe_garaje' at 100.00%
info  2023-11-22 00:12:09: MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":120,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"progress":100,"remaining":6,"state":"updating"},"update_available":null,"voltage":225}'
info  2023-11-22 00:14:09: Finished update of 'Enchufe_garaje'
info  2023-11-22 00:14:09: Configuring 'Enchufe_garaje'
info  2023-11-22 00:14:09: MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":116,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":null,"voltage":225}'
info  2023-11-22 00:14:09: Device 'Enchufe_garaje' was updated from 'null' to 'null'
info  2023-11-22 00:14:09: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"from":null,"id":"Enchufe_garaje","to":null},"status":"ok","transaction":"3rwx8-25"}'
info  2023-11-22 00:14:10: Successfully configured 'Enchufe_garaje'
info  2023-11-22 00:14:13: MQTT publish: topic 'zigbee2mqtt/Enchufe_garaje', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","linkquality":120,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":null,"voltage":172}'

```

**After update Enchufe_garaje**

![image](https://github.com/Koenkk/zigbee2mqtt/assets/62309618/e982ce3b-9ace-488e-8d76-6b5a9022f230)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/62309618/c43b4bbb-c382-4dcb-8cdd-3c2a69da49f6)

**Comment by XisoP01** [comment]
> The issue is still present on Z2M version 1.37.1

+1. Not able to update on Sonoff dongle and SLZB-06

**Comment by rvalitov** [comment]
The issue is still present on Zigbee2MQTT version 1.40.2

**Comment by rvalitov** [comment]
Up

**Comment by thierrybla** [comment]
Unstale

**Comment by Ricc68** [comment]
Fixed by mentioned PR https://github.com/nurikk/zigbee2mqtt-frontend/pull/2470.

**Comment by tastyratz** [comment]
This issue appears to still exist.
I can confirm a manual check does return existing and available firmware versions however the reported device version is still -1 on a new device that was recently purchased with build 83 on Zigbee2MQTT version 2.9.1

**Comment by Mastiffen** [comment]
What @tastyratz says. Checking for firmware:

<img width="1580" height="788" alt="Image" src="https://github.com/user-attachments/assets/520409f6-91c6-4bef-8b27-4156ad34d81a" />

Trying to update it:

<img width="565" height="89" alt="Image" src="https://github.com/user-attachments/assets/543ca3c3-469e-4176-bb15-2231e3a34378" />
