### ISSUE TITLE
1.30 breaks Tuya TS0601 _TZE200_lu01t0zl Human presence sensor with fall function

### ISSUE THREAD

**Issue by mescalum** [Koenkk/zigbee2mqtt#16467]
### What happened?

after upgrading the device presence sensor show as unknown in Homeassistant. After restore everyting works again.

### Zigbee2MQTT version

1.30

### Adapter firmware version

not sure 

### Adapter

Slaesh stick

**Comment by brot123** [comment]
i have also Problems with 1.30 with my TS601 lu01t0zl, what exactly logs you need about it? The Sensor didnt work ,i could change to 1.30 tomorrow again, i must change before my wife come back, you know:)

**Comment by alexebner** [comment]
Same Here with     TS0601_TZE200_ztc6ggyl

It logs something like report 0 but only 1,2 allowed.
But only in a short red popup. not ind the logs.
I also have rolled back because my wife is killing me when the light in the bathroom is not working.

**Comment by cdemi** [comment]
I confirm I have this problem as well

**Comment by mescalum** [comment]
@alexebner , I have the Problem with my wife in the dark bathroom too. What makes it worse that Z2M keeps updating itself without any prompts and then issue reoccurs. Happened twice since the first rollback. I have now deactivated the update.

**Comment by cdemi** [comment]
I think Koenkk/zigbee-herdsman-converters/pull/4859 is the cause of this issue

**Comment by cdemi** [comment]
Actually, it looks like problem is not with the hedsman converter, because I see the device reporting Presence and Occupation correctly in Zigbee2MQTT
![image](https://user-images.githubusercontent.com/8025435/216611236-3b316408-0a38-4981-bcc5-d88de41fdb57.png)

However Home Assistant is treating these as Unknown
![image](https://user-images.githubusercontent.com/8025435/216611436-2cbe30b6-9147-4a94-8f82-ee9928c18877.png)

**Comment by mescalum** [comment]
yes, thanks for illustrating. Same here. Sensors such as moving forward are shown correctly. It is just those two unknown sensors,which are unfortunately the important ones.

**Comment by alexebner** [comment]
Today i have updatet all again and flashed the new firmware on my Sonoff stick but the presence detector does not work.
The Log says:
Exception while calling fromZigbee converter: Value '0' is not allowed, expected one of 1,2}

**Comment by alexebner** [comment]
But this topic reports the sensors.

zigbee2mqtt/PM Küche:
{"fall_down_status":"none","fall_sensitivity":6,"illuminance_lux":32,"linkquality":54,"motion_direction":"standing_still","motion_speed":1,"occupancy":"false",**"presence":"true"**,"radar_scene":"area","radar_sensitivity":8,"static_dwell_alarm":null,"tumble_alarm_time":2,"tumble_switch":1}

{"fall_down_status":"none","fall_sensitivity":6,"illuminance_lux":32,"linkquality":54,"motion_direction":"standing_still","motion_speed":0,"occupancy":"false","**presence":"false**","radar_scene":"area","radar_sensitivity":8,"static_dwell_alarm":null,"tumble_alarm_time":2,"tumble_switch":1}

And ther it is reporting as it should.

**Comment by alexebner** [comment]
I have found another topic:
homeassistant/binary_sensor/pm_kuche_presence/presence 

Now i have changed the automation to MQTT topic Change and it looks like its working.

trigger:
  - platform: mqtt
    topic: homeassistant/binary_sensor/pm_kuche_presence/presence
    payload: '"true"'

**Comment by Koenkk** [comment]
The problem is that true became a string, `"true"` instead of `true`, I've pushed a fix, let me know if this works.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by alexebner** [comment]
I am not able to test it because the edge brunsh wont start at my homeasisstant.

When i insert my config and press save then the configuration page does get blank and i am unable to start Z2M.

When i switch back to normal brunsh it works again.

**Comment by mescalum** [comment]
@Koenkk this fixes the issue for Presence which is the important one. Can you do the same trick for Occupancy which still shows as unknown in HA? Thank you very much.

**Comment by Koenkk** [comment]
@mescalum it should already be fixed for `occupancy`, maybe it takes some time before the sensor updates its `occupancy`?

**Comment by mescalum** [comment]
@Koenkk Z2MEdge shows occupancy as null, even after refreshing edge and repairing. I guess that is why HA shows it still as unknown.

**Comment by Koenkk** [comment]
@mescalum has the occupancy ever worked before? Maybe it only triggers in very specific sitatuions.

**Comment by xistor4** [comment]
> @mescalum has the occupancy ever worked before? Maybe it only triggers in very specific situations.

The occupancy sensor behaved like a normal motion sensor triggering instantly from motion, where the presence sensor was slow to react but more accurate on continued room presence

**Comment by mescalum** [comment]
@Koenkk it shows value Occupied in z2m v1.29 and prior at least. I think it also shows that in v1.30 but am not going to verify that currently. Our bathroom window openend last time while wife was in shower as humidity was going up and no presence reported, she cried for help as ot is facing the road.

**Comment by cdemi** [comment]
From my end occupancy definitely worked because I have automations setup on that sensor

**Comment by robertbigk** [comment]
Is any one can say how to fix that now i all house light not work and i dont know how fix issue

**Comment by robertbigk** [comment]
@alexebner Sorry i not much undestood what You mean second trigger?
![brave_9bBDNUJVHS](https://user-images.githubusercontent.com/34956477/216833499-052c398b-42f4-4883-a3bc-416987db12b0.png)
![brave_YQqip8k47o](https://user-images.githubusercontent.com/34956477/216833502-416f367e-7302-497c-8420-a672e2a5f1d3.png)

Can You explane me what to do in long version?:)

**Comment by alexebner** [comment]
![grafik](https://user-images.githubusercontent.com/26386738/216835278-2a6885a4-391a-4931-b304-f8c5009c6f3b.png)

**Comment by alexebner** [comment]
To get all MQTT messages i am using the windows software MQTT.fx

**Comment by robertbigk** [comment]
@alexebner 
![brave_6VKJ3F1Stw](https://user-images.githubusercontent.com/34956477/216837944-24c88e26-e8f6-41fc-84f4-8e59f1bb4347.png)
![brave_iANvfjmFb2](https://user-images.githubusercontent.com/34956477/216837946-3c86373e-a80f-42bf-9319-367163947faa.png)

Sorry I ask, but i miss something? I try that and not work

**Comment by xistor4** [comment]
For anyone else having issues but also using node-red with home assistant,I was able to get it working fine with the zigbee2mqtt integration with node red

**Comment by Koenkk** [comment]
Can anybody else confirm that this issue is fixed in the latest dev? Then I can create a hotfix release.  (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by alexebner** [comment]
@robertbigk 

You have to search for the MQTT Topic with the name instead of the ID because the Problem is that the ID/presence ist not availabe.

**Comment by robertbigk** [comment]
@Koenkk Hi , I got two sensors MIR-HE200-TY. Install Zigbee2MQTT Edge in home assistant and confirm all devices back to life and report state in home assistant.

**Comment by mescalum** [comment]
@Koenkk, sorry, am late to respond. For me the presence sensor is fixed in EDGE 1.30.1-dev and my automations work. Thanks for that. However, the occupancy sensor is not. It shows as Null in Z2M GUI and as unavailable in HA GUI. I am happy to create a new issue for that. Maybe someone can confirm the descibed behavior? For me it is no longer critical as I dont use occupancy sensor.

**Comment by alexebner** [comment]
Same behaviour here
Exception while calling fromZigbee converter: Cannot read properties of undefined (reading 'from')}

And my workarround over the MQTT does not work anymore.

**Comment by cdemi** [comment]
![Screenshot_20230206-203726.png](https://user-images.githubusercontent.com/8025435/217068222-fe59ef35-cc01-470b-96c0-55471531cb80.png)

Yes, it looks like occupation is still Unknown

**Comment by xistor4** [comment]
has broken the occupancy sensor for me also with " Exception while calling
fromZigbee converter: Cannot read properties of undefined (reading 'from')}"

**Comment by raphaabreu** [comment]
I just updated in hoping of seeing this working again but the occupancy sensor still shows as unkown.

I can see that both values seem to have different types now in mqtt:
![DE112EF4-CF0E-46D1-AD5C-D73351C36668](https://user-images.githubusercontent.com/3214715/217126926-51d015fc-20b2-4e7a-a041-e4736141ab34.jpeg)

While the entity is configured to match the payload to boolean types instead of strings:

![51E6E089-5775-4EB3-B961-E513DDDA1B1C](https://user-images.githubusercontent.com/3214715/217127160-8ee4aad8-fdf5-45e9-b533-07b509bf47e7.jpeg)

**Comment by Koenkk** [comment]
@xistor4 could you provide the debug log of this?
