### ISSUE TITLE
Lidl HG06492C Colour Temp issue

### ISSUE THREAD

**Issue by WhiteAss** [Koenkk/zigbee2mqtt#16784]
### What happened?

The issue has been reported [already ](https://github.com/Koenkk/zigbee2mqtt/issues/5717)but hasn't been solved.

The color_temp scale seems inverted and not the full range is working

Normal:
cool - warm
150 - 500

HG06492C:
cool - warm - cool
150 - 256 - 500

150 - 256 isn't liniair. Seems kind of random cool.

Other Lidl/(Tuya) Lights don't have this problem. Examples: [HG08010](https://www.zigbee2mqtt.io/devices/HG08010.html#lidl-hg08010), [HG08007](https://www.zigbee2mqtt.io/devices/HG08007.html#tuya-hg08007)

### What did you expect to happen?

Corresponding temp scale

cool - warm
150 - 500

### How to reproduce it (minimal and precise)

Set "color_temp": VALUE

result is not corresponing:

HG06492C:
cool - warm - cool
150 - 256 - 500

### Zigbee2MQTT version

1.30.1

### Adapter firmware version

20221226

### Adapter

Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/10805832/log.txt)

**Comment by teunvg** [comment]
Having the same problem. I do also have this problem with some (but not all) other Lidl devices (in particular HG06104A). If it's of any use: the exact same problem occurs for these devices when I use ZHA instead.

**Comment by KrijnErmerins** [comment]
Having the same issue. Anyone found a solution yet?

**Comment by WhiteAss** [comment]
since last week the scale is corect. for me the problem is solved.

**Comment by KrijnErmerins** [comment]
That's weird. I still have the issue after updating HA to 2023.3.5 and Z2M running on 1.30.2-1
