### ISSUE TITLE
TS0121_TZ3000_rdtixbnu Power (Instantaneous measured power) stops reporting.

### ISSUE THREAD

**Issue by brunotfr** [Koenkk/zigbee2mqtt#17421]
### What happened?

As soon as I upgrade from version 1.28.4-1 to a newer one, the Power (Instantaneous measured power) of all plugs stops reporting.
Strangely the Energy (Sum of consumed energy) still keeps reporting.
The Addon perfectly runs with Out Of the Box settings with version 1.28.4-1
After a stop/start running version 1.30.3-1, Power does report for a short period of time an then stops.
Tried running it in debug, but there's no error in the log regarding this issue

### What did you expect to happen?

I expected the Power to keep reporting every minute.

### How to reproduce it (minimal and precise)

After upgrading to the latest version (1.30.3-1), stop/start the Addon.
Open the Zigbee2MQTT dashboard, open the Powerplug and switch on the Powerplug with (in my case) the washing machine plugged in.
In the dashboard you will see the current Power used by the washing machine.
As it runs through it's program you'll see the current Power change almost every minute.
After a period of time it stops changing, meaning the reporting stopped.
At this point the washing machine has not finished yet.
Only after a stop/start of the Addon, it wil start reporting again for a short period of time.

Running version 1.28.4-1 there is no issue.
The plug keeps reporting Power over and over, like expected.

### Zigbee2MQTT version

 1.30.3-1

### Adapter firmware version

20230411.1 - latest

### Adapter

Deconz Conbee II

**Comment by PastCoder** [comment]
I have the same issue with Blitzwolf BW-SHP13 (TZ3000_g5xawfcq). It worked well in the past. But some time (I don't know excatly since when) it does noz update anymore (or only after a very long time - sometime there is an update after some hours).
I did not find out if it is always.

**Comment by PastCoder** [comment]
Maybe it is related to this merge? https://github.com/Koenkk/zigbee-herdsman-converters/pull/5461

**Comment by brunotfr** [comment]
My settings are exactly like in the screenshot of stokket.
Looks like it has become an out of the box setting.

With version 1.28.4-1 the reports promptly come every minute and continue to come.
Every version after 1.28, with the same settings, will report for a short period of time and then stop.
Weird thing is, it's only the power that stops reporting

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following external converter: https://gist.github.com/Koenkk/fb4539bb570720f915774e28ef78a8bb

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by brunotfr** [comment]
Thanks for the swift respons.
Downloaded the file, renamed it to ext_converter_ts0121.js and added it to the configuration.yaml 

 external_converters:
  - ext_converter_tuya_battery.js
  - ext_converter_ts0601.js
  - ext_converter_ts0121.js

Next upgraded to version 1.30.3-1 and restarted z2m.
The Addon doesn't start with this error in the log:

[21:06:01] INFO: Preparing to start...
[21:06:01] INFO: Socat not enabled
[21:06:02] INFO: Starting Zigbee2MQTT...
/app/data/extension/externally-loaded.js:15
    fromZigbee: [fz.on_off, fz.electrical_measurement, fz.metering, fz.ignore_basic_report, tuya.fz.power_outage_memory,
                 ^
ReferenceError: fz is not defined
    at /app/data/extension/externally-loaded.js:15:18
    at Script.runInContext (node:vm:141:12)
    at Script.runInNewContext (node:vm:146:17)
    at Object.runInNewContext (node:vm:306:38)
    at loadModuleFromText (/app/lib/util/utils.ts:150:8)
    at loadModuleFromFile (/app/lib/util/utils.ts:157:12)
    at Object.getExternalConvertersDefinitions (/app/lib/util/utils.ts:167:25)
    at getExternalConvertersDefinitions.next (<anonymous>)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:12:20)
    at new Controller (/app/lib/controller.ts:84:58)

Tried to figure out where to set the reference, but did find it yet :-)

**Comment by Koenkk** [comment]
Updated https://gist.github.com/Koenkk/fb4539bb570720f915774e28ef78a8bb, power outage memory and indicator mode support will be added back later.

**Comment by brunotfr** [comment]
Did the same routine with the new file.
This time I get this error in the log during startup (version 1.30.3-1):

<img width="723" alt="image" src="https://user-images.githubusercontent.com/71332170/233826864-d44b43cd-8fcd-4a74-af05-f598530930b8.png">

**Comment by Koenkk** [comment]
Whooops, fixed with https://gist.github.com/Koenkk/fb4539bb570720f915774e28ef78a8bb

**Comment by brunotfr** [comment]
Haha, no problem.
Same routine with the latest file and this time it did startup :-)
Will run some test today and get back to you asap.

**Comment by brunotfr** [comment]
Looks like the problem is still there.
The washing machine started around 10:02 and reported every minute until around 10:15

<img width="425" alt="image" src="https://user-images.githubusercontent.com/71332170/233830266-44317acb-f646-4fb4-b6de-a95d6f990a32.png">

The history showed an update/report every minute, now the latest update is an hour ago:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/71332170/233830388-f972287b-8417-4946-81b2-5da4e4549dd8.png">

**Comment by Koenkk** [comment]
Can you provide the debug log on 1.28.4 and 1.30.3 when letting z2m run for a few hours (and receive power measurements from the device)? (without using any external converter)

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

**Comment by brunotfr** [comment]
Sure, will try to run some tests on both versions tommorrow with debug enabled

**Comment by brunotfr** [comment]
Attached the debug log files of both versions.
As the log file is rotating approximately every 10 minutes, I’ve downloaded several in a sequence and put them together in one file for each version.

Maybe I should rephrase the topic of the case to: 'It keeps reporting, but no longer the actual power consumption'.

For testing purposes I’ve connected an infrared heating panel to a plug called 'Wasmachine’.
So this is the object to look for in the logs.

In the ‘Version 1.30.3.log’ file the last actual power reading for 'Wasmachine' was 409 and then it froze:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/71332170/234004088-95631609-067f-4054-be7b-337893f188b5.png">

After 30 minutes in this state I switched over to version 1.28.4
As you can see in the ‘Version 1.28.4.log’ file, even after a period of time the actual Power consumption of 'Wasmachine’ is still reported correctly.

[Version 1.28.4.log](https://github.com/Koenkk/zigbee2mqtt/files/11310676/Version.1.28.4.log)
[Version 1.30.3.log](https://github.com/Koenkk/zigbee2mqtt/files/11310677/Version.1.30.3.log)

**Comment by Koenkk** [comment]
Could you check with the following external converter (on 1.30.3): https://gist.github.com/Koenkk/b6e8a5ead526d5c1bc737013c1676e96

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m
- let it run for some time until power measurements freeze
- provide me the STDOUT logging (not the log file), you should see messages like `SET TIMER`

**Comment by brunotfr** [comment]
Sure, downloaded the file and will run a test tomorrow.

**Comment by Koenkk** [comment]
@brunotfr I see, that's strange indeed. Please provide the log once it stops working again.

**Comment by brunotfr** [comment]
Issue is still there.
Today when using it for the first time again it stopped working.
At 10:52 the power was 67 and it stil is at this moment.

This is version 1.30.3 with the external_converter.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/71332170/235345656-81b9f662-1918-4c76-83bf-604f04a59066.png">

<img width="507" alt="image" src="https://user-images.githubusercontent.com/71332170/235345676-4ac77c55-efe2-4296-b64a-ba813cd09ae0.png">

Attached the STDOUT
The IEEE address you are looking for is 0x60a423fffe621677

[zigbee-herdsman.log](https://github.com/Koenkk/zigbee2mqtt/files/11360977/zigbee-herdsman.log)

**Comment by martinusgithubius** [comment]
I have similar problems, with TS011F  (_TZ3000_gvn91tmx), z2m version 1.30.4-1. The values of 'power' and 'current' remain unchanged after a certain period, especially when the device has been turned off. The recorded values during the 'on' period are still being displayed.

**Comment by Koenkk** [comment]
Thanks, I think I found & fixed the issue.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by brunotfr** [comment]
Jus stopped z2m and installed z2m Edge next to it.
Edited the configuration yaml and it started.
However after a couple of minutes the add-on stopped with this error:

[08:28:07] INFO: [32mPreparing to start...[0m
[08:28:08] INFO: [32mSocat not enabled[0m
[08:28:09] INFO: [32mStarting Zigbee2MQTT...[0m
Zigbee2MQTT:warn  2023-05-07 08:28:14: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2023-05-07 08:28:14: Allowing new devices to join.
Zigbee2MQTT:warn  2023-05-07 08:28:14: Set `permit_join` to `false` once you joined all devices.
Error: APS TIMEOUT
    at Driver.processApsBusyQueue (/app/node_modules/zigbee-herdsman/src/adapter/deconz/driver/driver.ts:721:28)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/adapter/deconz/driver/driver.ts:161:56)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

**Comment by Koenkk** [comment]
@brunotfr could you give me the herdsman debug log of this?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by brunotfr** [comment]
Followed the same steps and added herdsman debug.
After 7-10 minutes the devices became unavailable again (the add-on showed that is was still running).
Grabbing the log appeared to be not possible as the container was no longer available (forgot to copy the ID upfront).

For the next attempt I've rebooted everything and at the moment it's still running in Edge and herdsman debug after 35 minutes.
Also the power is still reporting every minute.
No clue why it crashed the first two times, but rebooting may have taken care of it.
Will keep an eye on it the next couple of hours.

**Comment by brunotfr** [comment]
Until now z2m Edge is still working as expected (with herdsman debug on).
Three rounds of the washing machine and one of the tumble dryer where reported neatly.
Looks like you found and fixed the issue :-)

**Comment by brunotfr** [comment]
@Koenkk The dev branch is still running fine.
Did not see this fix in the current releases.
Is it possible to add it to the next release?

**Comment by Koenkk** [comment]
@brunotfr I expect it is, can you check with z2m 1.31.0?

**Comment by brunotfr** [comment]
Sure, will give it a try and let you know.

**Comment by brunotfr** [comment]
Checked and it's fixed in z2m version 1.31.0-1

**Comment by brunotfr** [comment]
Checked and it's fixed in z2m version 1.31.0-1
