### ISSUE TITLE
Not working since 1.30.4 update

### ISSUE THREAD

**Issue by Chacsam** [Koenkk/zigbee2mqtt#17534]
### What happened?

Since update to 1.30.4, my container keeps crashing.

The error I receive in the docker conatiner log is
```
Zigbee2MQTT:info  2023-05-02 10:21:28: Zigbee2MQTT started!
Error: connect ECONNREFUSED 85.214.195.163:9005
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
```
What's that external IP it's trying to connect to?

### What did you expect to happen?

Zigbee2mqtt to work as usual

### How to reproduce it (minimal and precise)

It started crashing after automated update to 1.30.4 by Watchtower last night.
Container keeps restarting.

### Zigbee2MQTT version

1.30.4

### Adapter firmware version

20221226

### Adapter

ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

```
debug 2023-05-02 11:17:20: Loaded state from file /app/data/state.json
info  2023-05-02 11:17:20: Logging to console and directory: '/app/data/log/2023-05-02.11-17-20' filename: log.txt
debug 2023-05-02 11:17:20: Removing old log directory '/app/data/log/2023-05-02.10-58-27'
info  2023-05-02 11:17:20: Starting Zigbee2MQTT version 1.30.4 (commit #b2dd21e)
info  2023-05-02 11:17:20: Starting zigbee-herdsman (0.14.111)
debug 2023-05-02 11:17:20: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBa>
info  2023-05-02 11:17:20: zigbee-herdsman started (resumed)
info  2023-05-02 11:17:20: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20221226,"transportrev":2},"type":"zStack3x0"}'
debug 2023-05-02 11:17:20: Zigbee network parameters: {"channel":11,"extendedPanID":"0x00124b0024c0aebb","panID":6754}
info  2023-05-02 11:17:20: Currently 0 devices are joined:
info  2023-05-02 11:17:20: Zigbee: disabling joining new devices.
info  2023-05-02 11:17:20: Connecting to MQTT server at mqtt://192.168.11.211:1883
debug 2023-05-02 11:17:20: Using MQTT keepalive: 60
debug 2023-05-02 11:17:20: Using MQTT login with username: zigbee2mqtt
info  2023-05-02 11:17:21: Connected to MQTT server
info  2023-05-02 11:17:21: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
info  2023-05-02 11:17:21: Loaded  MyExampleExtension1682976504061
info  2023-05-02 11:17:21: MQTT publish: topic 'zigbee2mqtt/example/extension', payload 'hello from MyExampleExtension1682976504061'
info  2023-05-02 11:17:21: Started frontend on port 0.0.0.0:8080
debug 2023-05-02 11:17:21: Received MQTT message on 'zigbee2mqtt/bridge/config' with data '{"commit":"b2dd21e","coordinator":{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"re>
info  2023-05-02 11:17:21: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"b2dd21e","coordinator":{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision>
info  2023-05-02 11:17:21: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
info  2023-05-02 11:17:21: Zigbee2MQTT started!
```

**Comment by Chacsam** [comment]
OK... it is somehow solved now. A night doing nothing did help

**Comment by AugustinN** [comment]
I have the exact same issue (same ip adress), and doing nothing has not solved it...anyone has a clue what might be going on ? Running zigbee2mqtt on an old raspberry pi b+

**Comment by Chacsam** [comment]
It's good to feel less lonely. 
As a rollback didn't work, I assumed it wasn't linked to the update so I closed this issue to have a more 'to the point' description in #17550

**Comment by Palhersan** [comment]
Solucionado:
https://www.reddit.com/r/Zigbee2MQTT/comments/137c9ar/zigbee2mqtt_connecting_to_external_server/
