### ISSUE TITLE
[Wrong device]: Tuya ZigBee Human Presence Sensor ZY-M100-S

### ISSUE THREAD

**Issue by Burki24** [Koenkk/zigbee2mqtt#17583]
### Link

https://de.aliexpress.com/item/1005004704966668.html?aff_fcid=a6c1939fce52480b88ae7361ee630d45-1683452632112-09740-_Ddy0YiH&tt=CPS_NORMAL&aff_fsk=_Ddy0YiH&aff_platform=shareComponent-detail&sk=_Ddy0YiH&aff_trace_key=a6c1939fce52480b88ae7361ee630d45-1683452632112-09740-_Ddy0YiH&terminal_id=478e162037384eab98ba9ba82186f96e&afSmartRedirect=y&gatewayAdapt=4itemAdapt

### Model

ZY-M100-S

### Description

Tuya ZigBee Human Presence Sensor

### Vendor

Tuya

### Picture (link)

https://github.com/Burki24/Z2M_Pictures/blob/main/devices/radar-wall-1.jpg

### Database entry

{"id":47,"type":"Router","ieeeAddr":"0xe0798dfffed6de48","nwkAddr":55536,"manufId":4098,"manufName":"_TZE204_ztc6ggyl","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":".3�+i/3�+i/3�+i03�+i03�+i33�+i43�+i53�+i","65506":31,"65508":0,"modelId":"TS0601","manufacturerName":"_TZE204_ztc6ggyl","powerSource":1,"zclVersion":3,"stackVersion":0,"hwVersion":1,"dateCode":"","appVersion":70}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1683450017555,"defaultSendRequestWhen":"immediate"}

### Notes

This is the wall mount Version of the ZY-M100. Ther is also an in-wall mount version with a different design called ZY-M100-L.

**Comment by Koenkk** [comment]
Already fixed in https://github.com/Koenkk/zigbee2mqtt/issues/17525

**Comment by Burki24** [comment]
Sorry,

but it isn't fixed:
![image](https://user-images.githubusercontent.com/20765982/236694778-09d305b3-7c59-4f0a-aa04-c67523d49b82.png)
![image](https://user-images.githubusercontent.com/20765982/236694947-4a31d600-e563-4237-b85c-3d8c064de7b9.png)

Running on 1.30.4-dev commit b8e46075. Tested in Edge, Chrome and firefox. With cleaned cache in every browser.

Greetings
Burkhard

**Comment by ERgoliner** [comment]
the ceiling mount got detected the right way

![grafik](https://user-images.githubusercontent.com/45270504/236815392-a8a96e95-730e-4523-bd7b-63b1acfe57e0.png)

but not the wall mount mentioned at the top

![grafik](https://user-images.githubusercontent.com/45270504/236815793-922d3ec4-da4a-44c4-a833-37553ccf7e1d.png)

**Comment by Sch8er** [comment]
> Everything works fine with this #17483, check converter: [https://gist.github.com/Koenkk/9295fc8afcc65f36027f9ab4d319ce64](url)

If i try to enter at configuration.yml
-> Integration error: external_converters - Integration 'external_converters' not found.
If i added it to Configuration of "Zigbee2MQTT Edge" no changes - still "not supported"
`data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyUSB0
external_converters:
  - /config/ext_converter.js`

Any idea?

**Comment by ERgoliner** [comment]
> Everything works fine with this #17483, check converter: [https://gist.github.com/Koenkk/9295fc8afcc65f36027f9ab4d319ce64](url)

confirmed thx all
