### ISSUE TITLE
TuYa TS0726 identified as TS0004

### ISSUE THREAD

**Issue by marek-vrana** [Koenkk/zigbee2mqtt#19276]
### What happened?

I have couple of Zigbee 4CH Switch Module devices: https://www.zigbee2mqtt.io/devices/TS0726.html
All of them are identified as TS0004 https://www.zigbee2mqtt.io/devices/TS0004.html

Currently switches work, but I'm unable to set switch mode and read action.

Database entry
````
{"id":12,"type":"Router","ieeeAddr":"0xa4c138061628305c","nwkAddr":15702,"manufId":4417,"manufName":"_TZ3000_liygxtcq","powerSource":"Mains (single phase)","modelId":"TS0004","epList":[1,2,3,4,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,1794,2820,57344,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":".��,\u0012","65506":56,"65508":0,"65534":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZ3000_liygxtcq","zclVersion":3,"appVersion":72,"modelId":"TS0004","powerSource":1}},"manuSpecificBosch":{"attributes":{"53251":"AAAAAgAABAAABgAA"}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"moesStartUpOnOff":2}},"manuSpecificTuya_3":{"attributes":{"53248":0,"53249":0,"53250":0,"53251":0,"53252":0,"53253":0,"switchType":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1af32e","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1af32e","endpointID":1}],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":256,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1af32e","endpointID":1}],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":256,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1af32e","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":889996980},"lastSeen":1696968291288,"defaultSendRequestWhen":"immediate"}
````

### What did you expect to happen?

Device is recognized correctly as TS0726 exposing: switch (state), power_on_behavior, switch_mode, action, linkquality.

### Zigbee2MQTT version

1.33.1-1

### Adapter firmware version

20221226

### Adapter

SONOFF ZBDongle-P

**Comment by ralvarez83** [comment]
I update to Home Assistant 2023.10.2 and the problem has been resolved :)

**Comment by marek-vrana** [comment]
Nice try @ralvarez83, can you point to a commit that is supposed to fix this issue? Because it is not fixed and updating from 2023.10.1 to 2023.10.2 did not help at all!

**Comment by marek-vrana** [comment]
@Koenkk please reopen this issue again. Issue still persists.

**Comment by ralvarez83** [comment]
I don’t know. I have updated home-assistant and now it works. I didn’t do anymore.

It’s true that I can’t find a bug solve in the version change: https://www.home-assistant.io/blog/2023/10/04/release-202310/

Maybe it solved only when I restarted Home-Assistant.

If I can help anymore please tell me.

Best regards

**Comment by krylek** [comment]
Has anyone found a solution to this problem?

**Comment by marek-vrana** [comment]
It's still an issue.

**Comment by marek-vrana** [comment]
Still an issue

**Comment by marek-vrana** [comment]
Still an issue
