### ISSUE TITLE
Cannot change operation_mode on Aqara H1 Switches (Xiaomi WS-EUK01/02/04)

### ISSUE THREAD

**Issue by AkshayRao27** [Koenkk/zigbee2mqtt#20036]
### What happened?

Trying to change the Operation mode on three different models of Aqara H1 switches (Xiaomi WS-EUK01, WS-EUK02, & WS-EUK04) results in an error:
WS-EUK01: `Publish 'set' 'operation_mode' to 'Wardrobe Switch' failed: 'Error: undefined is not a object, got string ("decoupled")'`
WS-EUK02: `Publish 'set' 'operation_mode' to 'Toilet Switch' failed: 'Error: undefined is not a object, got string ("decoupled")''`
WS-EUK04: `Publish 'set' 'operation_mode' to 'Bathroom Switch' failed: 'Error: undefined is not a object, got string ("decoupled")'`

None of the methods that I have tried so far have been able to change the operation mode. I have tried:
- Zigbee2MQTT > Devices > Exposes > Operation Mode
- HA > Settings > Devices & Services > MQTT > Devices > Operation Mode Left
- MQTT Expolorer > `zigbee2mqtt/Bathroom Switch/operation_mode/set` & `{"operation_mode_left": "decoupled"}`
- MQTT Expolorer > `zigbee2mqtt/Bathroom Switch/set` & `{"operation_mode_left": "decoupled"}`

_This may be related to #19960, #19964, and/or #19478, but I'm not sure because those issues were about other models_

### What did you expect to happen?

When the Operation Mode for a switch is changed in the front end or by manually sending an MQTT Payload, there is no error & the Operation Mode changes to the specified value.

### How to reproduce it (minimal and precise)

Via Z2M:
1. Open Zigbee2MQTT & select an Aqara H1 Switch
2. In the "Exposes" tab, find "Operation mode" and click on "decoupled"

Via MQTT:
1. Go to Settings > Devices & Services > MQTT > Devices
2. Select an Aqara H1 Switch, find the "Configuration" card and select a value from the "Operation mode" drop down

Via MQTT Explorer:
1. In MQTT Explorer, navigate to the Aqara H1 Switch under the zigbee2mqtt topic
2. Publish a packet with `{"operation_mode_left": "decoupled"}` to `zigbee2mqtt/<Switch_Name>/operation_mode/set`
3. Just to be sure, publish a packet with  `{"operation_mode_left": "decoupled"}` to `zigbee2mqtt/<Switch_Name>/set`

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

7.3.1.0 build 0

### Adapter

[SONOFF ZBDongle-E](https://www.zigbee2mqtt.io/devices/ZBDongle-E.html)

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/13559841/log.txt)

**Comment by pusheax0** [comment]
Still having this issue too. It is NOT fixed.
<img width="948" alt="about" src="https://github.com/Koenkk/zigbee2mqtt/assets/127334508/c2038957-d55d-4e3d-8c15-f2952db3ce12">
<img width="1698" alt="log" src="https://github.com/Koenkk/zigbee2mqtt/assets/127334508/7ed4ce61-b4a9-4232-95d1-eab8f5cb681e">
<img width="927" alt="state" src="https://github.com/Koenkk/zigbee2mqtt/assets/127334508/f516d826-d86a-4045-8885-657e16d99bdd">
<img width="1718" alt="switch" src="https://github.com/Koenkk/zigbee2mqtt/assets/127334508/9d9c33c2-2949-4783-af05-66cab16981be">

**Comment by wezzle** [comment]
Commit [392ad722](https://github.com/Koenkk/zigbee-herdsman-converters/commit/392ad722e0f9ad9f151b9bfacab433f3492904f1) fixes this for `xiaomi_switch_operation_mode_basic`. My device seems to run  `xiaomi_switch_operation_mode_opple` where the check is still  `utils.assertObject(value);` https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/converters/toZigbee.ts#L2501C30-L2501C30

I have no running dev version so I can't test the fix but perhaps @Koenkk can take another look?

**Comment by pusheax0** [comment]
> Commit [392ad722](https://github.com/Koenkk/zigbee-herdsman-converters/commit/392ad722e0f9ad9f151b9bfacab433f3492904f1) fixes this for `xiaomi_switch_operation_mode_basic`. My device seems to run `xiaomi_switch_operation_mode_opple` where the check is still `utils.assertObject(value);` https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/converters/toZigbee.ts#L2501C30-L2501C30
> 
> I have no running dev version so I can't test the fix but perhaps @Koenkk can take another look?

I replaced this line https://github.com/Koenkk/zigbee-herdsman-converters/commit/392ad722e0f9ad9f151b9bfacab433f3492904f1#diff-cdc7c627220d02e6995b7fa52a0056b8650198a9850fc9f61c3eee7365fb8698R2487

with ```let targetValue = utils.isObject(value) && value.hasOwnProperty('state') ? value.state : value;``` and it fixed it.

**Comment by Koenkk** [comment]
Already fixed in the dev branch

**Comment by pusheax0** [comment]
> Already fixed in the dev branch

Not fixed for 0pple devices. Please read thread and see that the dev branch is being used.

**Comment by Sperum** [comment]
Im running the latest commit and i still have the same issue (below is the error from the log)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/4891161/e659c2f7-3b19-4ce7-8d7d-1176cb2bb2ee)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/4891161/7a262eaa-7fdb-4d3b-9732-a90691774c4c)



`Zigbee2MQTT:debug 2023-12-05 22:59:20: Received MQTT message on 'zigbee2mqtt/Switch_Light Toilet Down/set' with data '{"operation_mode_left":"decoupled"}'
Zigbee2MQTT:debug 2023-12-05 22:59:20: Publishing 'set' 'operation_mode' to 'Switch_Light Toilet Down'
Zigbee2MQTT:error 2023-12-05 22:59:20: Publish 'set' 'operation_mode' to 'Switch_Light Toilet Down' failed: 'Error: undefined is not a object, got string ("decoupled")'
Zigbee2MQTT:debug 2023-12-05 22:59:20: Error: undefined is not a object, got string ("decoupled")
    at Object.assertObject (/app/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:517:15)
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:2501:19)
    at Publish.onMQTTMessage (/app/lib/extension/publish.ts:249:52)
    at EventEmitter.emit (node:events:525:35)
    at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22)
    at MQTT.onMessage (/app/lib/mqtt.ts:141:27)
    at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:130:27)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1192:20)
    at Receiver.emit (node:events:513:28)`

**Comment by AkshayRao27** [comment]
I just tried this again on the dev branch by installing Zigbee2MQTT Edge in Home Assistant. The issue doesn't seem to be fixed. See screenshot:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/44117116/367e0b5b-06c6-463f-b298-5440203d48da)

**Comment by ynsgnr** [comment]
I have the same issue!

**Comment by Koenkk** [comment]
Pushed another fix, please try again.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by Sperum** [comment]
> Pushed another fix, please try again.
> 
> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

Tested with : 1.34.0-dev commit: [f11eb24](https://github.com/Koenkk/zigbee2mqtt/commit/f11eb24)

Error:

Zigbee2MQTT:debug 2023-12-06 21:47:45: Received MQTT message on 'zigbee2mqtt/Switch_Light Toilet Down/set' with data '{"operation_mode_left":"decoupled"}'
Zigbee2MQTT:debug 2023-12-06 21:47:45: Publishing 'set' 'operation_mode' to 'Switch_Light Toilet Down'
Zigbee2MQTT:error 2023-12-06 21:47:45: Publish 'set' 'operation_mode' to 'Switch_Light Toilet Down' failed: 'Error: undefined is not a object, got string ("decoupled")'
Zigbee2MQTT:debug 2023-12-06 21:47:45: Error: undefined is not a object, got string ("decoupled")
    at Object.assertObject (/app/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:517:15)
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:2501:19)
    at Publish.onMQTTMessage (/app/lib/extension/publish.ts:249:52)
    at EventEmitter.emit (node:events:525:35)
    at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22)
    at MQTT.onMessage (/app/lib/mqtt.ts:141:27)
    at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:130:27)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1192:20)
    at Receiver.emit (node:events:513:28)

**Comment by AkshayRao27** [comment]
Having the same issue still.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/44117116/9e9a6f19-e4a6-4da5-b8c5-7f4de0be1cb4)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/44117116/7f6f1ac4-2e75-4315-a53c-d9b0688d4b96)

**Comment by pusheax0** [comment]
@AkshayRao27 Try again after version 16.2.0 is released later today. https://github.com/Koenkk/zigbee-herdsman-converters/releases

**Comment by Sperum** [comment]
> @AkshayRao27 Try again after version 16.2.0 is released later today. https://github.com/Koenkk/zigbee-herdsman-converters/releases

I've reinstall Z2M Edge, but only the commit got updated.
How do you force 16.2 update with HA ?

Thank you

**Comment by AkshayRao27** [comment]
Just did a quick test with 16.2
The error message has gone away now and I can set the switch to decoupled Mode. However, even after setting it to decoupled it is still behaving like a relay - how can I figure out why exactly this may be happening? What troubleshooting info would be helpful?

**Comment by gloaysa** [comment]
> > @AkshayRao27 Try again after version 16.2.0 is released later today. https://github.com/Koenkk/zigbee-herdsman-converters/releases
> 
> I've reinstall Z2M Edge, but only the commit got updated. How do you force 16.2 update with HA ?
> 
> Thank you

The 16.2.0 release is for the converters library. The latest commit on the Z2M Edge (dev) updates the dependency of said library to 16.2.0. If you are in 1.34.0-dev commit: [cb50942](https://github.com/Koenkk/zigbee2mqtt/commit/cb50942) on Edge, you are good to go.

I was able to set decoupled mode, but I'm not physically next to the switch (yet) to confirm is not working as a relay. @AkshayRao27 can you confirm you have "Mode switch": "fast_mode"? I think you have to have it on fast_mode (I've read it in some Reddit thread, so take it with a grain of salt).

**Comment by AkshayRao27** [comment]
Strange. Your layout looks different from mine:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/44117116/0ca06762-e21a-4995-82b9-d7c977d83105)

I restarted HA, and now pressing the switch seems to not trigger the relay. I can run automations with the "single left" action. 

If I use the state switch either in the Zigbee2MQTT or in the MQTT integration in Home Assistant 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/44117116/8f42bbc5-8d25-41bd-bf40-20fd69e28f90)
then the switch continues to act like a relay. Is this intended behaviour?

With the switch in decoupled mode, the LED on the switch never turns off - is this intended behaviour too?

**Comment by KMTsvetanov** [comment]
one more here from me:
`Publish 'set' 'operation_mode' to '0x54ef44100096461e' failed: 'Error: undefined is not a object, got string ("decoupled")'`

**Comment by AkshayRao27** [comment]
@KMTsvetanov Can you check if your Edge build has updated correctly?
I have the same switch ("Bedroom Switch" from the screenshot in my previous reply) and decoupled mode is working for me on this version of edge:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/44117116/d67fce98-2a38-4230-b4be-3f7e5d6d4c25)
I had to reinstall the Edge addon twice (including the whole "check for updates" thing in the addon store in HA) and then restart HA completely before decoupled mode started working for me.

**Comment by AkshayRao27** [comment]
> for me it's this:
Yup, that's the issue then. The 'operation_mode' thing isn't working on the release branch right now and has only been fixed on the latest version of the dev branch.

> don't know how to switch to dev version
It's VERY easy! If you're running Home Assistant: 
1. Go to the Addon Store & install Zigbee2MQTT **Edge**. Don't start it yet.
2. Then, go to the non-edge version of the addon that you currently have running, go to the Configuration Tab, select "Edit in YAML" from the three-dot menu, and copy the contents of what you see to somewhere safe.
- If you want to be extra-safe, use some kind of File Browser addon, navigate to the Zigbee2MQTT Folder (for me it was in /homeassistant/zigbee2mqtt) and copy all of the contents of that folder to your PC (highly unlikely that this would be required, but it never hurts to have a backup)
4. Stop Zigbee2MQTT (you don't need to uninstall it).
5. Go to the Configuration Tab in the newly installed Zigbee2MQTT **Edge**,  select "Edit in YAML" from the three-dot menu, and paste in what you copied from Zigbee2MQTT earlier. 
6. Start Zigbee2MQTT Edge, and it should all work seamlessly. 

Verify that you are on the version that I posted above - the decoupled mode should ideally work for you then :)

**Comment by gloaysa** [comment]
@KMTsvetanov assuming you are using a home assistant addon:

You are using the 'normal' addon of Z2M, you need to stop that addon and install Zigbee2Mqtt Edge one. To do so, go to the addons store in HomeAssistant, click on 'Check for Updates' and the right top corner menu, give a few seconds and install the Edge addon.

**Comment by KMTsvetanov** [comment]
@AkshayRao27 ok tested. Now:

1. Good -  I can decouple
2. Bad -  I'm still getting Sensors -> Energy = Unknows
![image](https://github.com/Koenkk/zigbee2mqtt/assets/15339860/eacca853-6ed9-4ae5-9d5b-380a870fea82)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/15339860/1943b118-b606-42dc-989e-59e480488184)
Triend to refresh "Power"
![image](https://github.com/Koenkk/zigbee2mqtt/assets/15339860/4dd64ce3-f19f-4473-a75a-b8c8dd5b7389)

1 Question (maybe bug): I can't hame trigger for clicking
![image](https://github.com/Koenkk/zigbee2mqtt/assets/15339860/fac52647-25f7-41aa-aa68-9c5d73f205f7)

**Comment by gloaysa** [comment]
Regarding the trigger for clicking:

You are using the action of the physical switch (that won't work when clicking because is on decoupled mode). That will only trigger when you manually, from the UI, switch the relay on/off.

I have created this automation, sharing in case it helps:

```yml
alias: Control interruptores (temporal)
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.playroom_interruptor_action
      - sensor.cuarto_interruptor_action
      - sensor.bano_interruptor_action
      - sensor.vestidor_interruptor_action
      - sensor.aseo_interruptor_action
    to: single
condition: []
action:
  - service: switch.turn_on
    target:
      entity_id: "{{ trigger.to_state.entity_id }}"
    enabled: false
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
    enabled: false
  - service: light.toggle
    target:
      entity_id: >-
        {{ 'light.' ~ trigger.to_state.entity_id.split('.')[1].split('_')[0] ~ '_techo' }}
mode: queued
max: 10

```

The important take away here is that you have to use as trigger for your automation the state of your_name_action when changes to 'single' (there are other options, I'm only using the single click).

My automation reuses code for multiple switches because the lights they are turning on follows the same pattern:
name of light to change: light.{name}_techo
name of the event that operates the light: switch.interruptor_{name}_action

**Comment by KMTsvetanov** [comment]
@gloaysa when on 'decoupled' or 'control_relay' mode there are no logs when pressing buttons (Light still turns on on control_relay).
Even in the Developer Tools I can't see the sate change on click for all my testing:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/15339860/cc1fac0b-1937-4f08-8b15-23cea9dc2dd9)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/15339860/ea313a21-8956-4cfb-a036-3fb1aefccb02)

**Comment by gloaysa** [comment]
@KMTsvetanov it could be that the device is not responsive or not properly paired? I would try disconnecting it from the zigbee network and connecting it again.

I can say much more than that, my experience with all this is also only at user level.

**Comment by KMTsvetanov** [comment]
@gloaysa Thank you. Tried many things. Even talked to the seller just now. Maybe for HA it's still doesn't have the single, double, triple click functionality ('decoupled' and 'control_relay')... :/

**Comment by KMTsvetanov** [comment]
I found what is the problem but we need to open a ticket for this:
The same problem can be found here but I don't know what to do or if I can even do it
https://github.com/Koenkk/zigbee2mqtt/discussions/16573

I think it's something to do with my Coordinator ?
But I got the new Sonoff ZB Dongle - E

**Comment by Sperum** [comment]
Ok it seems its working now.
However it only accept to setup controlled our decoupled trough the HA device view instead of Z2M device view.
However the behavior is as expected.
Thx

**Comment by Ajhomepn** [comment]
When will be released the version with this correction (normal not edge) ?

**Comment by Ajhomepn** [comment]
I'm runing the last edge version , i'm abel to go to decoupled or to relay , howerver on decoupled  i can not triger anything ... this is ruining all my routines :/

**Comment by gloaysa** [comment]
@Ajhomepn 

In case it helps, I'm sharing my automation on Home Assistant. To me, decoupled mode does not allow me to bind the switch to a bulb (or group, for that matter), so I ended using Home Assistant to control it:

```yml
alias: Switches Controller (temporal)
description: "Manages all Aqara switches, toggling lights if they haven't been recently turned on."
trigger:
  - platform: state
    entity_id:
      - sensor.playroom_interruptor_action
      - sensor.cuarto_interruptor_action
      - sensor.bano_interruptor_action
      - sensor.aseo_interruptor_action
      - sensor.vestidor_interruptor_action
    to: single
condition: []
action:
  - variables:
      room: >-
        {{ trigger.to_state.entity_id.split('.')[1].split('_')[0].replace('ñ',
        'n') }}
      light: "{{ 'light.' ~ room ~ '_techo' }}"
      light_last_changed: "{{ (as_timestamp(now()) - as_timestamp(states[light].last_changed)) }}"
  - alias: >-
      Avoid turning off a light that has just turned on (due to delay of switch
      and occupation triggering faster)
    if:
      - alias: Light hasn't changed in the last second
        condition: template
        value_template: "{{ light_last_changed > 1 }}"
    then:
      - service: light.toggle
        target:
          entity_id: "{{ 'light.' ~ room ~ '_techo' }}"
mode: queued
max: 10

```

I don't like to repeat myself, so this automation control all switches. The trick here is to follow a pattern on the naming of your switches and lights.

for example, all my switches follow this pattern: `sensor.ROOM_SWITCH_action`.
all my lights follow this pattern:`light.ROOM_techo`.

Because of that, I'm able to toggle a light by reading the ROOM part of the switch.

If you want something simpler, you could do this for each switch instead:

```yml
alias: Switch Controller for YOUR SWITCH
description: "Manages A SWITCH, toggling lights on user input."
trigger:
  - platform: state
    entity_id:
      - sensor.YOUR_SWITCH_action # notice the _action part, that's what you are looking for.
    to: single # and also notice this single. This is a single click event
condition: []
action:
  - service: light.toggle
        target:
          entity_id: light.your_light
mode: single

```

**Comment by drashish87** [comment]
Sorry to reopen the thread, has this been fixed in the latest Z2MQTT version or I still need to install the dev version? Having similar issue using latest Sky connect zigbee dongle, thank you.
Zigbee2MQTT version
[1.36.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.36.0) commit: [2a53b8e5](https://github.com/Koenkk/zigbee2mqtt/commit/2a53b8e5)
Coordinator type
EZSP v12
Coordinator revision
7.3.2.0 build 212

**Comment by jeff08568** [comment]
Any reason why is this not on main?

**Comment by korobcov** [comment]
I confirm, it doesn’t work for me on the stable version either 



Error 2024-04-14 01:43:12Publish 'set' 'operation_mode' to 'Выключатель прихожая ' failed: 'Error: ZCL command 0x54ef4410008b7064/1 manuSpecificLumi.write({"512":{"value":0,"type":32}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 8792 - 1 - 82 - 64704 - 4 after 10000ms)'

**Comment by newbyp** [comment]
Sorry I am new to this, can someone confirm what the desired result is of setting the switch as decoupled. 

I have just installed the 3 switch version and set as relay and all lights work fine. I now want to install more switches but need one to toggle on and off in HA but not physically switch the relay and therefore turn the light on. I assume this is decoupled mode. 

I'm running z2m not the dev branch and have tried changing the setting in mqtt and checking it in z2m and regardless of what the mode is set to I don't see any changes in the operation.

Are my assumptions correct and is this an ongoing issue?

I could buy a battery powered smart switch instead of the single light switch or wait for it to be fixed.
