### ISSUE TITLE
incomplete device info for Bosch BTH-RM230Z

### ISSUE THREAD

**Issue by aaamoeder** [Koenkk/zigbee2mqtt#20057]
### What happened?

I tried pairing the device but got constant interview errors

the device [info page](https://www.zigbee2mqtt.io/devices/BTH-RM230Z.html) is incomplete since it mentions nowhere there is an install code needed to pair the device succesfully.

### What did you expect to happen?

since the device is mentioned as fully supported I expected it to be paired succesfully without any install code (never even heard of it before)

### How to reproduce it (minimal and precise)

attempt to pair without install code

### Zigbee2MQTT version

1.34.0 

### Adapter firmware version

20221226

### Adapter

cc2652 slaesh

### Debug log

failed interview log data.. irrelevant info...

**Comment by h1nnak** [comment]
Hey aaamoeder, with the last update it is solved i think: [19377](https://github.com/Koenkk/zigbee2mqtt/issues/19377).
I paired the thermostat without problems.

**Comment by metallmanu** [comment]
poorly the device is not completely supported. The system_mode cool is missing and also to set the valves either to no (normaly open) or nc (normaly closed)

**Comment by metallmanu** [comment]
set the valves either to no (normaly open) or nc (normaly closed) is still missing

**Comment by metallmanu** [comment]
set the valves either to no (normaly open) or nc (normaly closed) is still missing

**Comment by metallmanu** [comment]
set the valves either to no (normaly open) or nc (normaly closed) is still missing

**Comment by DerDreschner** [comment]
This is resolved with [version 2.6.3](https://github.com/Koenkk/zigbee2mqtt/releases/tag/2.6.3) which was released yesterday. 🥳
