### ISSUE TITLE
TuYa TS0044 messed up in 1.35.3-1

### ISSUE THREAD

**Issue by TomaamoT7** [Koenkk/zigbee2mqtt#21458]
### What happened?

Changelog for 1.35.3-1 says that it was addressing issue with TuYa TS0042:
#21196 Fix no actions for TuYa TS0042 (@Koenkk)
Unfortunatelly it messed up TuYa TS0044 devices.

After the upgrade to 1.35.3-1 the TuYa TS0044 devices stopped working. They also show incorrect device picture (now they look like remote with buttons instead of 4-way switch).
Everything is working ok after rollback to  previous version (1.35.2-1). 

Zigbee2MQTT
Installed version
1.35.2-1
Latest version
1.35.3-1

### Zigbee2MQTT version

1.35.3-1

### Adapter firmware version

0x26660700

### Adapter

Conbee II

### Setup

Add-on on Home Assistant running directly on Raspberry Pi4

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of your device?

**Comment by TomaamoT7** [comment]
Sure. I have 7 of them bought from different sellers in different time. They have minimal mechanical differences but they are all reported the same way (same manufacturer and model id). Here's one example (see at the bottom) I extracted it directly as text from database.db file.

One additional info: in order to avoid missed clicks and high battery drain I applied (months ago) the following fix:
https://community.home-assistant.io/t/tuya-ts0044-first-action-ignored/475940/2
I can confirm that with the fix there are no missed clicks and I don't need to replace batteries every 2-3 months in them.
Anyway most likely it has nothing to do with the current issue.


Second comment: looks like the zigbee2mqtt.io site is wrong now (it used to be ok).
Both the remote (that I don't have) and the switch are shown as the same device.
https://www.zigbee2mqtt.io/devices/TS0044.html   -> this should be the switch (that was working fine, but is messed up right now, picture in the atachement
![TS0044](https://github.com/Koenkk/zigbee2mqtt/assets/95109929/99aeb5ff-ef00-479b-b2e3-f119d08a6ee9)
)
https://www.zigbee2mqtt.io/devices/TS0044_1.html  ->this is most likely the remote (I don't have it and I can't confirm)
Both share the same (or similar name) and that may be the issue??


{"id":4,"type":"EndDevice","ieeeAddr":"0xcc86ecfffe168bd0","nwkAddr":63031,"manufId":4098,"manufName":"_TZ3000_wkai4ga5","powerSource":"Battery","modelId":"TS0044","epList":[1,2,3,4],"endpoints":{"1":{"profId":260,"epId":1,"devId":0,"inClusterList":[0,1,6],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"uO�,\u0019\u0000\u0000\u0000\u0000\u0007\u0000\u0000\u0000\u0000\u0011","65506":31,"65508":1,"65534":0,"modelId":"TS0044","manufacturerName":"_TZ3000_wkai4ga5","powerSource":3,"zclVersion":3,"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":30}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00212effff07ba7d","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}},"2":{"profId":260,"epId":2,"devId":0,"inClusterList":[1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":0,"inClusterList":[1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":0,"inClusterList":[1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-302029049},"lastSeen":1708464576726}

**Comment by Koenkk** [comment]
I've fixed the detection part!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by brinzlee** [comment]
I have installed the updated version 1.36 which is supposed to address this issue and it still shows the wrong icons as described above. Restoring to 1.35.2 corrects this discrepancy

**Comment by Koenkk** [comment]
can you provide a screenshot of the about screen with 1.35.2?

**Comment by brinzlee** [comment]
@Koenkk 
![Screenshot 2024-03-05 192911](https://github.com/Koenkk/zigbee2mqtt/assets/14986700/504d79e4-ddb5-4f06-b7c9-e9ff817dcbaf)
![Screenshot 2024-03-05 192951](https://github.com/Koenkk/zigbee2mqtt/assets/14986700/5d5ce871-5b56-457e-8ef9-6c8acbd74d45)

**Comment by Koenkk** [comment]
Fixed the picture, may take some time for the cache to refresh.

**Comment by brinzlee** [comment]
@Koenkk Thanks I refreshed the cache and the first one is fixed but the second one is still wrong icon. Its a different model number but the same switch visually  
![Screenshot 2024-03-05 192951](https://github.com/Koenkk/zigbee2mqtt/assets/14986700/c1712d7e-431d-49c4-914a-b0b85b5bea61)

**Comment by Koenkk** [comment]
fixed!

Assuming this issue can be closed now.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by TomaamoT7** [comment]
@Koenkk: The pictures are still wrong. They are switched now.
https://www.zigbee2mqtt.io/devices/TS0044.html -> this should be the switch picture (square, 4 buttons)
![TS0044_1](https://github.com/Koenkk/zigbee2mqtt/assets/95109929/cc523724-1459-4650-95e7-c861050fceda)


https://www.zigbee2mqtt.io/devices/TS0044_1.html -> this should be the remote picture (rectangle remote like)
![TS0044](https://github.com/Koenkk/zigbee2mqtt/assets/95109929/55a81001-5d8c-45a7-bbb5-f888b4c9d374)


It's only about the pictures, functionality is correct (at least for the devices that I have.

**Comment by Koenkk** [comment]
fixed!

**Comment by brinzlee** [comment]
@koenkk. I am very confused how these updates work. And how the icons update. Is this something that happens when the addon is updated or something that is cloud updated. When I updated the app from 1.35.2 to 1.36 the icons were incorrect on
_TZ3000_uaa99arv and _TZ3000_wkai4ga5. You mentioned the cache would take some time to update and after a while _TZ3000_wkai4ga5 proceeded to the correct icon but _TZ3000_uaa99arv never did....Now I have updated to 1.36.1 and both icons have reverted back to the incorrect picture. Is this an update issue or still the cache misbehaving ?

**Comment by TomaamoT7** [comment]
For me the fix that was applied on 28 March by Koenkk corrected the pictures issue. Now they are displayed correctly.
All of my switches are _TZ3000_wkai4ga5, I don't have any other.

To the best of my knowledge it's just the cloud data update, so no need to download/install anything... 
I was also quite confused about how it works. For me the pictures were switched from 5th to 28th March.

**Comment by TomaamoT7** [comment]
@Koenkk: the story continues...
I updated to zigbee2mqtt_1.36.0-1 and the images are wrong again.

This is what I have now:
![obraz](https://github.com/Koenkk/zigbee2mqtt/assets/95109929/79ee974a-9d65-4368-a83d-8153dc291d7e)

_TZ3000_wkai4ga5 should be 4 button SWITCH.
https://www.zigbee2mqtt.io/devices/TS0044.html

**Comment by Koenkk** [comment]
@TomaamoT7 I don't understand, in https://github.com/Koenkk/zigbee2mqtt/issues/21458#issuecomment-2024960636 you mentioned that `TS0044_1` (which is the device you have) should use this picture:

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2892853/783be9ef-eb2b-4f82-8bfe-a817e3acebad)

**Comment by brinzlee** [comment]
I think there is a lot of confusion now in this thread. My pictures that I referred to are now showing the the 4 button rectangular remote control when they should both refer to the 4 button square panel with green leds.

**Comment by aoaite** [comment]
My TS044 (the square one) stopped working after update. It is now incorrectly recognized as TS0044_1(the long one).

**Comment by Koenkk** [comment]
@brinzlee for each manufacturer name (starting with _TZ) can you indicate if it should be the long remote or the square 4 button remote picture?

**Comment by brinzlee** [comment]
@Koenkk 

_TZ3000_wkai4ga5
_TZ3000_uaa99arv

**these should both be the square 4 button remotes with the green LEDs.**

Using the current version 1.36.1-1 of the Home Assistant Addon they are being shown as the the long remote which is incorrect

Thanks for your kind help

**Comment by Koenkk** [comment]
@brinzlee done!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
