### ISSUE TITLE
Error: ZCL command genOnOff.on

### ISSUE THREAD

**Issue by rw-django-fan-2020** [Koenkk/zigbee2mqtt#22189]
### What happened?

My Home Assistant System crashed. Dont know why. Had to move to another Device (ThinClient). Restored my Home Assistant Backup. But zigbee dont work anymore. Help. 

### What did you expect to happen?

I expected it to work.

### Zigbee2MQTT version

1.36.1-1

### Adapter firmware version

 0x26780700

### Adapter

ConBee2/RaspBee2

### Setup

Add-on on Home Assistant OS on Proxmox VM

### Debug log

error 2024-04-12 00:24:18Publish 'set' 'state' to 'Blitzwolf Steckdose 2' failed: 'Error: ZCL command 0x3425b4fffe4984d2/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (76))'
debug 2024-04-12 00:24:18Error: ZCL command 0x3425b4fffe4984d2/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (76)) at DeconzAdapter.sendZclFrameToEndpoint (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:666:23) at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:760:28) at Endpoint.command (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:591:24) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:46:17) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:259:36) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17)

**Comment by robertomontinaro80** [comment]
Similar error for me for that getonoff command after the update 
I can't turn on any lamp in my home.
I add also this error stack trace if it can help

`18Publish 'set' 'state' to 'osram_kitchen_lamp' failed: 'Error: ZCL command 0x7cb03eaa0a038452/3 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'`

**Comment by gentleman1979** [comment]
Similar problems for a few days 
`Zigbee2MQTT:error 2024-04-12 22:25:07: Publish 'set' 'state' to 'SFZ-Wand-rechts' failed: 'Error: ZCL command 0x00178801037e0089/11 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC channel access failure' (225))'`

**Comment by albert-canfield** [comment]
Similar issue too with a SONOFF ZBMINIL2 switch. 

Publish 'set' 'state' to 'Entrance lights' failed: 'Error: ZCL command 0x0ceff6fffe16f9fb/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 33295 - 1 - 36 - 6 - 11 after 10000ms)'

**Comment by majkers** [comment]
Same. Here. I updated to 1.36.1-1 from 1.35.2-1 because I wanted to test https://github.com/Koenkk/zigbee2mqtt/issues/21162


`Publish 'set' 'state' to 'gniazdko_xiaomi' failed: 'Error: Command 0x00158d0002347282/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (16))'`

**Comment by robertomontinaro80** [comment]
> Same here. I updated to 1.36.1-1 from 1.35.2-1 because I wanted to test #21162
> 
> `Publish 'set' 'state' to 'gniazdko_xiaomi' failed: 'Error: Command 0x00158d0002347282/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (16))'`
> 
> `Publish 'set' 'state' to 'gniazdko_neo' failed: 'Error: Command 0xa4c1389a7623f41a/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (17))'`
> 
> They are Xiaomi ZNCZ02LM and Tuya TS011F_plug_1

For me ver 1.36.0 works fine. 1.36.1 does not.

**Comment by hytepro** [comment]
Similar issue

**Comment by Pepeuch** [comment]
Similaire issue with conbee 2 hassos supervised on rpi4 8go.

**Comment by blakefrain** [comment]
I am having the same issue conbee 2 and multiple connected devices

**Comment by vencakratky** [comment]
Similar Issue with Immax bulbs

**Comment by Langhii** [comment]
Me too

**Comment by galant-ho** [comment]
Having similar issue with my Aqara E1 Roller Shade Driver starting last week.  Thought it was my setting issue so repair it several times.  The E1 paired successfully, able to control the blind for certain times until the next day, lost control from HA.

`2024-04-17 08:03:54Publish 'set' 'state' to 'E1-blind' failed: 'Error: ZCL command 0x54ef4410009ff334/1 genAnalogOutput.write({"presentValue":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 47747 - 1 - 208 - 13 - 4 after 10000ms)'`

**Comment by shanec42** [comment]
I've got the same problem as others above.  Here's the important failure, but I'm including the full log just in case it helps.
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/15019245/log.txt)


Zigbee2MQTT version [1.36.1] (https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.36.1) commit: [ffc2ff1](https://github.com/Koenkk/zigbee2mqtt/commit/ffc2ff1)
Coordinator type  zStack3x0
Coordinator revision  20230507
Coordinator IEEE Address  0x00124b002a2f28c2
Frontend version  0.6.161
zigbee_herdsman_converters_version  19.11.2
zigbee_herdsman_version  0.40.3

debug 2024-04-17 20:17:19: Received MQTT message on 'zigbee2mqtt/Office Ceiling Light 4/set' with data '{"state":"OFF"}'
debug 2024-04-17 20:17:19: Publishing 'set' 'state' to 'Office Ceiling Light 4'
error 2024-04-17 20:17:42: Publish 'set' 'state' to 'Office Ceiling Light 4' failed: 'Error: ZCL command 0xb0ce18140352fa2f/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 53320 - 1 - 64 - 6 - 11 after 10000ms)'
debug 2024-04-17 20:17:42: Error: ZCL command 0xb0ce18140352fa2f/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 53320 - 1 - 64 - 6 - 11 after 10000ms)
    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:499:47)
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
    at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)
    at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:760:28)
    at Endpoint.command (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:591:24)
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:46:17)
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1129:32)
    at Publish.onMQTTMessage (/app/lib/extension/publish.ts:259:36)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17)

**Comment by siddharthghiya** [comment]
Hi, I was having the same issue where I restored my HA installation from a backup. Zigbee stopped working. I also had individual add-on backups, and things started working again after I downgraded zigbee2mqtt from 1.36.1-1 to 1.36.0-1.

It started working again after downgrading to 1.36.0-1 and then I upgraded back to 1.36.1.-1. Hope this helps!

**Comment by Aposei** [comment]
Seems like the same problem to me. 

zigbee2mqtt 1.36.1-1 (but I can't change to 1.36.0-1)

`Error 2024-04-20 14:19:20Publish 'set' 'state' to 'Plancha' failed: 'Error: ZCL command 0xa4c138e4e6ae7bd2/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 43659 - 1 - 76 - 6 - 11 after 10000ms)'
Debug 2024-04-20 14:19:20Error: ZCL command 0xa4c138e4e6ae7bd2/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 43659 - 1 - 76 - 6 - 11 after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:492:47) at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:760:28) at Endpoint.command (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:591:24) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:46:17) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:259:36) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17)`

**Comment by bezdekf** [comment]
The same problem:

Zigbee2MQTT:error 2024-04-20 16:43:04: Publish 'set' 'state' to 'IKEA 3' failed: 'Error: ZCL command 0xcc86ecfffe8d422e/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
Zigbee2MQTT:error 2024-04-20 16:43:06: Publish 'set' 'state' to 'WOOX  1' failed: 'Error: ZCL command 0x588e81fffede3426/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'

etc

**Comment by paboman** [comment]
same here:

`Failed to configure '0xa4c1387bc939184d', attempt 2 (Error: ZCL command 0xa4c1387bc939184d/1 haElectricalMeasurement.configReport([{"attribute":"rmsCurrent","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":50}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)) at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:760:28) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:561:9) at Object.rmsCurrent (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:216:5) at configure (/app/node_modules/zigbee-herdsman-converters/src/devices/tuya.ts:3773:13) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:162:21) at Configure.configure (/app/lib/extension/configure.ts:122:13))`

**Comment by bezdekf** [comment]
I didn't change anything and suddenly after 2 days everything works. Grrrr...

> The same problem:
> 
> Zigbee2MQTT:error 2024-04-20 16:43:04: Publish 'set' 'state' to 'IKEA 3' failed: 'Error: ZCL command 0xcc86ecfffe8d422e/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))' Zigbee2MQTT:error 2024-04-20 16:43:06: Publish 'set' 'state' to 'WOOX 1' failed: 'Error: ZCL command 0x588e81fffede3426/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
> 
> etc

I didn't change anything and suddenly after 2 days everything works. But just to be sure, I'm switching from the not recommended CC 2531 to the SONOFF ZB Dongle-P Zigbee 3.0

**Comment by bezdekf** [comment]
> The same problem:
> 
> Zigbee2MQTT:error 2024-04-20 16:43:04: Publish 'set' 'state' to 'IKEA 3' failed: 'Error: ZCL command 0xcc86ecfffe8d422e/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))' Zigbee2MQTT:error 2024-04-20 16:43:06: Publish 'set' 'state' to 'WOOX 1' failed: 'Error: ZCL command 0x588e81fffede3426/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
> 
> etc

I didn't change anything and suddenly after 2 days everything works. But just to be sure, I'm switching from the not recommended CC 2531 to the SONOFF ZB Dongle-P Zigbee 3.0

**Comment by Pepeuch** [comment]
Est il possible d’avoir une réponse à cette erreur qui est récurrente et surtout qui bloque tout fonctionnement? Par avance merci

**Comment by mhzawadi** [comment]
I now have this issue too, was working fine till a stop and start of the z2m.

```
2024-04-21 10:31:22Publish 'set' 'state' to '01 - switch - mbed' failed: 'Error: ZCL command 0x00124b00246cb0b6/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (70))'
```

Conbee2 in a Pi 4

```
DEVLINKS: >-
  /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2436161-if00
  /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.2:1.0
DEVNAME: /dev/ttyACM0
DEVPATH: >-
  /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.2/1-1.2:1.0/tty/ttyACM0
ID_BUS: usb
ID_MODEL: ConBee_II
ID_MODEL_ENC: ConBee\x20II
ID_MODEL_ID: '0030'
ID_PATH: platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.2:1.0
ID_PATH_TAG: platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_2_1_0
ID_REVISION: '0100'
ID_SERIAL: dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2436161
ID_SERIAL_SHORT: DE2436161
ID_TYPE: generic
ID_USB_DRIVER: cdc_acm
ID_USB_INTERFACES: ':020201:0a0000:'
ID_USB_INTERFACE_NUM: '00'
ID_USB_MODEL: ConBee_II
ID_USB_MODEL_ENC: ConBee\x20II
ID_USB_MODEL_ID: '0030'
ID_USB_REVISION: '0100'
ID_USB_SERIAL: dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2436161
ID_USB_SERIAL_SHORT: DE2436161
ID_USB_TYPE: generic
ID_USB_VENDOR: dresden_elektronik_ingenieurtechnik_GmbH
ID_USB_VENDOR_ENC: dresden\x20elektronik\x20ingenieurtechnik\x20GmbH
ID_USB_VENDOR_ID: 1cf1
ID_VENDOR: dresden_elektronik_ingenieurtechnik_GmbH
ID_VENDOR_ENC: dresden\x20elektronik\x20ingenieurtechnik\x20GmbH
ID_VENDOR_ID: 1cf1
MAJOR: '166'
MINOR: '0'
SUBSYSTEM: tty
TAGS: ':systemd:'
USEC_INITIALIZED: '1797972056257'
```

**Comment by gregorth** [comment]
The same issuse started on 1.36.1 
I've moved back to 1.36 but the issue exists:
`zigbee2mqtt  | Zigbee2MQTT:debug 2024-04-22 16:10:54: Error: Command 0x84fd27fffee27a55/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 55120 - 1 - 13 - 6 - 11 after 10000ms)
zigbee2mqtt  |     at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23)
zigbee2mqtt  |     at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:499:47)
zigbee2mqtt  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
zigbee2mqtt  |     at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
zigbee2mqtt  |     at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)
zigbee2mqtt  |     at Endpoint.command (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:746:28)
zigbee2mqtt  |     at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:46:17)
zigbee2mqtt  |     at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:3242:28)
zigbee2mqtt  |     at Publish.onMQTTMessage (/app/lib/extension/publish.ts:259:36)
zigbee2mqtt  |     at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17)`


device

Zigbee 3.0 smart light switch module 2 gang (BW-SS7_2gang)
producent: BlitzWolf 

logs attached
[mqtt-e9c00b799d38e6cea56d6ca67013c4a7-0x84fd27fffee27a55-cfb76b68aa064a467d78c69ab1342f1f.json](https://github.com/Koenkk/zigbee2mqtt/files/15064291/mqtt-e9c00b799d38e6cea56d6ca67013c4a7-0x84fd27fffee27a55-cfb76b68aa064a467d78c69ab1342f1f.json)

**Comment by DiegoJp** [comment]
Same behaviour with a ZB-GW04 v1.2 (latest fw: [v7.4.1.0](https://github.com/darkxst/silabs-firmware-builder/blob/main/firmware_builds/zb-gw04-1v2/ncp-uart-hw-v7.4.1.0-zb-gw04-1v2-115200.gbl=)) and some Tuya lightbulbs: TS0505B_1_1 and TS0505B_2_1

**Comment by galant-ho** [comment]
Does anyone here have this error with SONOFF Zigbee dongle-P?

I am trying to understand if this is an isolated issue with ConBee2/RaspBee2.  If so then it's something else I need to resolve with my SONOFF Zigbee dongle-P.

**Comment by paveltsytovich** [comment]
Have the same issue with TS0002 (model _TZ3000_fisb3ajo) 2 gang switch module

`Publish 'get' 'power_on_behavior' to 'Bathroom_Switch' failed: 'Error: ZCL command 0xa4c13873a4df1d0c/1 genOnOff.read(["moesStartUpOnOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 391 - 1 - 5 - 6 - 1 after 10000ms)'`

Actual version 1.36. Coordinator Sonoff dongle E

**Comment by shanec42** [comment]
> Does anyone here have this error with SONOFF Zigbee dongle-P?
> 
> I am trying to understand if this is an isolated issue with ConBee2/RaspBee2. If so then it's something else I need to resolve with my SONOFF Zigbee dongle-P.

Yes.  I ran into the errors while running the "Sonoff Zigbee 3.0 USB Dongle Plus" (idVendor=10c4, idProduct=ea60) which I believe is identical.

**Comment by remcotjeerdsma** [comment]
Migrated my Zigbee network on a Conbee 2 from Deconz to Zigbee2Mqtt this weekend. Now none of my lamps work anymore because of this. Seems to have started after an unintended shutdown of HassOS and with it Zigbee2Mqtt.

**Comment by majkers** [comment]
I've just migrated from Conbee II to Sonoff dongle P and after abour 18 hours just got an error:

`error 2024-04-25 12:02:45: Publish 'set' 'state' to 'gniazdko_xiaomi' failed: 'Error: ZCL command 0x00158d0002347282/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 18793 - 1 - 158 - 6 - 11 after 10000ms)'`

You can see in my previous post https://github.com/Koenkk/zigbee2mqtt/issues/22189#issuecomment-2053533255 with Conbee that the error was a bit different but more or less the same. So it is not a matter of dongle I guess

**Comment by vxav** [comment]
Same issue after downgrading to `1.36.0` and `1.35.3`. It seems to be somewhat transient as it works again after a moment.

```
Zigbee2MQTT:error 2024-04-26 15:15:14: Publish 'set' 'state' to 'Light Ceiling Kitchen' failed: 'Error: Command 0xa4c1387e52c34552/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 17076 - 1 - 26 - 6 - 11 after 10000ms)'

Zigbee2MQTT:info  2024-04-26 15:15:14: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'Light Ceiling Kitchen' failed: 'Error: Command 0xa4c1387e52c34552/1 genOnOff.off({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Timeout - 17076 - 1 - 26 - 6 - 11 after 10000ms)'","meta":{"friendly_name":"Light Ceiling Kitchen"},"type":"zigbee_publish_error"}'
```

**Comment by Matrix-aas** [comment]
Same problem.
There are 3 Aqara switches, and the “Sonoff zigbee 3.0 usb dongle plus-e” coordinator, after switching to the “MultiPAN RCP” firmware, Zigbee2MQTT began to behave incorrectly with the switches. After restarting the application, it works fine for a couple of minutes, after which errors begin and it becomes impossible to control the switches.
I tried rolling back the coordinator firmware back to ZESP, but nothing changed.
Zigbee2MQTT latest stable version.

_I don’t understand deeply, but I suspect that maybe the switches go to sleep and there is some possibility of waking them up at certain intervals? (re-query as at startup?)
Previously, this problem appeared occasionally, but was solved on its own; there were simply on/off delays of about 10 seconds. This didn't happen often._

https://www.zigbee2mqtt.io/devices/WS-EUK01.html#aqara-ws-euk01
https://www.zigbee2mqtt.io/devices/WS-EUK02.html#aqara-ws-euk02

```
[Error] [2024-04-26 19:45:16] Publish 'set' 'state' to 'Office Switcher' failed: 'Error: ZCL command 0x54ef44100022553f/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 47174 - 1 - 18 - 6 - 11 after 10000ms)'
[Error] [2024-04-26 19:45:23] Received undefined command from '0'
[Error] [2024-04-26 19:45:36] Publish 'set' 'state' to 'Office Switcher' failed: 'Error: ZCL command 0x54ef44100022553f/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 47174 - 1 - 19 - 6 - 11 after 10000ms)'
[Error] [2024-04-26 19:45:56] Publish 'get' 'state' to 'Office Switcher' failed: 'Error: ZCL command 0x54ef44100022553f/1 genOnOff.read(["onOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 47174 - 1 - 20 - 6 - 1 after 10000ms)'
```

**Comment by delphijb** [comment]
**[solved for me]**
I had the same problem, with a Conbee II, HAOS (thinkclient) and Z2M 1.36.1
I solved my problem by upgrading the firmware of my Conbee II key to the latest version (0x26780700)

If this solution helps anyone :-)

**Comment by galant-ho** [comment]
> Having similar issue with my Aqara E1 Roller Shade Driver starting last week. Thought it was my setting issue so repair it several times. The E1 paired successfully, able to control the blind for certain times until the next day, lost control from HA.
> 
> `2024-04-17 08:03:54Publish 'set' 'state' to 'E1-blind' failed: 'Error: ZCL command 0x54ef4410009ff334/1 genAnalogOutput.write({"presentValue":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 47747 - 1 - 208 - 13 - 4 after 10000ms)'`

To give an update here... my issue seemed to be resolved by adding a good router near to my Aqara E1 blind.  Aqara appears to be non Zigbee 3.0 standard in which not so compatible with other brand router.
I've got a Aqara smart switch with neutral wire, installed it a few feet away from the E1 solved the problem.
Running pretty well for 3 days straight.

**Comment by mhzawadi** [comment]
Thanks for your report, I have just got the update installed (https://community.home-assistant.io/t/how-to-update-conbee-ii-on-hassio-with-deconz-phoscon-integration/402826/12) helped a lot.

I did get an error on boot up

```
Error 2024-05-01 20:10:15Publish 'set' 'state' to '00 - light - hall' failed: 'Error: ZCL command 0x540f57fffe20798e/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (5))'
```

**Comment by trozman** [comment]
Similar: suddenly my zigbee network is not working anymore (after 2 years of solid performance).
Errors: ... MAC channel access failure' (225)
... Error: ZCL command ...
(using Sonoff USB dongle plus)

**Comment by XerxesFB** [comment]
Similar problem since update to ha 2024.5 and 5.2

Using donlge SONOFF USB Dongle plus E

Publish 'set' 'state' to 'Plug Levoit Luftreiniger' failed: 'Error: ZCL command 0xa4c138167ce8ca96/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 13021 - 1 - 21 - 6 - 11 after 10000ms)'
 seems that only the few last added plugs have the problem

**Comment by BurningTheSky** [comment]
Same issue for me. 
Sonoff P dongle
Zigbee2MQTT version: 1.37.0
HA Core 2024.5.2
HA Supervisor 2024.04.4 

```
Publish 'set' 'state' to 'Toilet and Under Stairs Switch' failed: 'Error: ZCL command 0x54ef44100076d47e/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 37191 - 1 - 255 - 6 - 11 after 10000ms)'
```

**Comment by NoAdO** [comment]
Same problem with LLKZMK11LM for about 4 weeks for now, sometimes work but sometimes i get "Timeout - 12367 - 1 - 198 - 6 - 11 after 10000ms" "Timeout - 12367 - 1 - 183 - 6 - 11 after 10000ms" etc. Already tried to restart, recreate container, re-pair device. I have 20 devices in the network and this one worked perfectly before, but have lags now. Other devices do not seem to be affected. 
Zigbee2MQTT (docker): 1.37.0
HA Core (docker) 2024.5.2
SONOFF ZB Dongle-P
Zigbee device model lumi.relay.c2acn01
```
[2024-05-08 00:20:46] error:  z2m: Publish 'set' 'state' to 'ZB Relay Bath' failed: 'Error: ZCL command 0x00158d000428ad57/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 12367 - 1 - 198 - 6 - 11 after 10000ms)'
```

**Comment by majkers** [comment]
It would be nice if someone from developers write something about possible cause or fix...

**Comment by trozman** [comment]
> Same issue for me. Sonoff P dongle Zigbee2MQTT version: 1.37.0 HA Core 2024.5.2 HA Supervisor 2024.04.4
> 
> `Publish 'set' 'state' to 'Toilet and Under Stairs Switch' failed: 'Error: ZCL command 0x54ef44100076d47e/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 37191 - 1 - 255 - 6 - 11 after 10000ms)'`

Have you tried to update the Sonoff dongle firmware to 20230507? It solved the issue for me.

**Comment by BurningTheSky** [comment]
> > Same issue for me. Sonoff P dongle Zigbee2MQTT version: 1.37.0 HA Core 2024.5.2 HA Supervisor 2024.04.4
> > `Publish 'set' 'state' to 'Toilet and Under Stairs Switch' failed: 'Error: ZCL command 0x54ef44100076d47e/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 37191 - 1 - 255 - 6 - 11 after 10000ms)'`
> 
> Have you tried to update the Sonoff dongle firmware to 20230507? It solved the issue for me.

I haven't, do I have to repair all devices after a firmware upgrade?

**Comment by BurningTheSky** [comment]
> > > > Same issue for me. Sonoff P dongle Zigbee2MQTT version: 1.37.0 HA Core 2024.5.2 HA Supervisor 2024.04.4
> > > > `Publish 'set' 'state' to 'Toilet and Under Stairs Switch' failed: 'Error: ZCL command 0x54ef44100076d47e/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 37191 - 1 - 255 - 6 - 11 after 10000ms)'`
> > > 
> > > 
> > > Have you tried to update the Sonoff dongle firmware to 20230507? It solved the issue for me.
> > 
> > 
> > I haven't, do I have to repair all devices after a firmware upgrade?
> 
> No, I didn't repair. I just switched routers (smart sockets) off - and then on (pulled them out of the wall sockets) after the FW update. This was necessary to get rid of errors.

I had to repair some light switches but not remove them from z2m so not too bad. All sorted and working for me now though, thanks!

**Comment by kovu94** [comment]
Same issue here, started today. I have around 100 zigbee devices and the Home Assistant Skyconnect Stick.

Publish 'set' 'state' to 'EG Schlafzimmer Schalter Wand' failed: 'Error: ZCL command 0xa4c13899e3d176ef/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 11242 - 1 - 67 - 6 - 11 after 10000ms)'

It's a Moes Wall-Switch:

Zigbee-Modell
    TS0011
Zigbee-Hersteller
    _TZ3000_hhiodade
Beschreibung
    Wall light switch (1 gang)

Tried to remove and reset the switch. It's discovered/connected but I can't turn it on or off.
Checked for a firmware update for the Skyconnect stick, but on the homepage they say that no update is available.
Beside this - not important - switch, at the moment everything else works fine.

My versions (HA running on a Intel NUC):
Core 2024.5.2
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1

I just installed the Operating System Update to 12.3 with a clean reboot. Switch is still not working.

**Comment by openshwprojects** [comment]
Same issue on SNZB-04
```
Info 2024-05-09 18:15:08Configuring '0x842e14fffe00c3bd'
Error 2024-05-09 18:15:30Failed to configure '0x842e14fffe00c3bd', attempt 1 (Error: ZCL command 0x842e14fffe00c3bd/1 genBasic.read(["manufacturerName","zclVersion","appVersion","modelId","powerSource",65534], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)) at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:412:23) at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:766:28) at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:401:29) at Object.configureMagicPacket (/app/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:380:9) at configure (/app/node_modules/zigbee-herdsman-converters/src/devices/tuya.ts:2096:13) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:160:21) at Configure.configure (/app/lib/extension/configure.ts:121:13) at Immediate.<anonymous> (/app/lib/extension/configure.ts:74:17))
```

**Comment by asd2003ru** [comment]
Same error. Sometimes commands slip through with a delay.

**Comment by j-paulus** [comment]
Started having this problem with one specific device: "TRADFRI control outlet. E1603/E1702/E1708" after the recent major update in z2m.
Coordinator is Sonoff Dongle-e with 7.4.2 [GA] FW, ezsp driver, problem happening with both z2m 1.37.0 and now 1.37.1.

Error message in log is:
```
[2024-05-10 08:27:16] error: 	z2m: Publish 'set' 'state' to 'Ikea Plug' failed: 'Error: ZCL command 0xb43a31fffe54afc0/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Delivery failed for {"profileId":260,"clusterId":6,"sourceEndpoint":1,"destinationEndpoint":1,"options":4160,"groupId":0,"sequence":100})'
```

Prior to the update the dongle was using the original 6-series FW and ember driver, and the network was solid.

**Comment by kovu94** [comment]
Weird, today I received an update for Z2M

Zigbee2MQTT version
[1.37.1]
Coordinator type
EmberZNet
Coordinator revision
7.4.1 [GA]

After a deletion of the switch and a new pair, not it works fine again. 
Fingers crossed 😊

**Comment by galant-ho** [comment]
Those who has been having this issue tried to upgrade Z2M to 1.37.1confimed issue resolved?

**Comment by j-paulus** [comment]
@galant-ho As mentioned in my earlier message, I am having this problem also with 1.37.1. 

I tried re-pairing the problematic device, but the error keeps on appearing.

**Comment by rw-django-fan-2020** [comment]
Finally I solved my problem. I had to change the config "channel" from 11 (default) to 15.

**Comment by Tonio16** [comment]
> Those who has been having this issue tried to upgrade Z2M to 1.37.1confimed issue resolved?

I have the sonoff P dongle with zignee2mqtt 1.37.1 and I’have the issue. Zigbee2mqtt is running on a LXC. 
I also notice that ota are not working.

Antoine

**Comment by AxxlFoley** [comment]
> Finally I solved my problem. I had to change the config "channel" from 11 (default) to 15.

I tried the same .. did not solve the issue for me

**Comment by rw-django-fan-2020** [comment]
> > Finally I solved my problem. I had to change the config "channel" from 11 (default) to 15.
> 
> Good this worked for you ... But is this a stable fix for a longer period ? I tried the same .. did not solve the issue for me
> 
> I tried a lot :
> 
>     * update to 1.37.1
> 
>     * channel switch to 15
> 
>     * move to ember
> 
>     * update firmware of my Sonoff-dongle-e to latest 7.4.30
> 
> 
> Issue keeps apperaing .. so i do not think it is solved.

Did you repair your zigbee devices? Channel changing means repairing.
https://www.zigbee2mqtt.io/guide/configuration/zigbee-network.html#permit-join

If you did repair and it does not work try the channels 20 or 25.

I guess I got these issue because I had to change my device and location of the zigbee adapter. It is now closer to my wlan router. And zigbee and wifi signals can cause interferences.

**Comment by trozman** [comment]
> Good this worked for you ... But is this a stable fix for a longer period ? I tried the same .. did not solve the issue for me
> 
> I tried a lot :
> 
> * update to 1.37.1
> * channel switch to 15
> * move to ember
> * update firmware of my Sonoff-dongle-e to latest 7.4.30
> 
> Issue keeps apperaing .. so i do not think it is solved.

After updating fw on the dongle, did you reset the routers?
This was a crucial step for me. After (only)updating fw (Sonoff P), it was worse. Then I unplugged and plugged back all the mains-powered Zigbee devices and suddenly all of the errors were gone.

**Comment by shanec42** [comment]
I've now updated to 1.37.1, and everything appears (knock on wood) to have returned to normal.

**Comment by galant-ho** [comment]
Few things I would like to bring this up hopefully could help some of you to resolve this issue.
I had such problem solely to my Aqara E1 blind motor around second week April.

Then I added a Aqara smart switch (with neutral) near to where my E1 installed, it resolved the problem for a while.  Yea just for a while and it gave out issue again.  This time I noticed E1 doesn't pair with the smart switch as router.  Completely no idea why.

I decided to move a IKEA smart outlet right near to where the smart switch was (same room), pair it to Z2M.  E1 connected to it with very strong LQI.  I also wondered battery of E1 dropped to 50% would also trigger this problem.  Hoped not the case.

**Comment by NoAdO** [comment]
For me issue was solved when i disconnected NAS for a long period because of replacing UPS battery and forgot to connect 2 routers to power. No problem for about 2 weeks for now. I can guess the problem is related to self-calibration routes throung devices, so if we break the network (switch channel, stick update, no power for long time etc.) routes may create another way and problem will be "magically" solved. 

If you still have such troubles, try to power off single devices for a period of time and look for errors. If you found traitor, think what you can do with it. I have an old cc2531 stick so if the problem returns, i'm going to open another Z2M instance with traitor device and cc2531 and look will this fix my problem.

**Comment by GWsmart** [comment]
Please HELP!!!
Similaire issue with conbee 2 on rpi4 8gb
flash new firmware on conbee2 without a result
Repair most of divices was good! Everything works, 
Than i made a new HA update and i have the same: Error: ZCL command! 
radio channel z2m: 11 wlan: 11
Before 05/2024 it works over one year!
What can i do to solve the problem

**Comment by ArbiterGR** [comment]
I've been experiencing the same thing. Using ember driver and latest non-edge version of z2m.

**Comment by GWsmart** [comment]
@ArbiterGR
witch logs do you mean?
`[2024-05-24 22:29:34] info: 	z2m: Zigbee: disabling joining new devices.
[2024-05-24 22:29:35] info: 	z2m: Connecting to MQTT server at mqtt://core-mosquitto:1883
[2024-05-24 22:29:36] info: 	z2m: Connected to MQTT server
[2024-05-24 22:29:36] info: 	z2m: Started frontend on port 8099
[2024-05-24 22:29:36] info: 	z2m: Zigbee2MQTT started!
[2024-05-24 22:30:02] error: 	z2m: Publish 'set' 'state' to 'licht/eg/hwr' failed: 'Error: ZCL command 0x001788010d43dfd6/11 genLevelCtrl.moveToLevelWithOnOff({"level":0,"transtime":30}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (3))'
`
This is an example from z2m addon...
Or do you need other logs?

**Comment by ArbiterGR** [comment]
> @ArbiterGR witch logs do you mean? `[2024-05-24 22:29:34] info: z2m: Zigbee: disabling joining new devices. [2024-05-24 22:29:35] info: z2m: Connecting to MQTT server at mqtt://core-mosquitto:1883 [2024-05-24 22:29:36] info: z2m: Connected to MQTT server [2024-05-24 22:29:36] info: z2m: Started frontend on port 8099 [2024-05-24 22:29:36] info: z2m: Zigbee2MQTT started! [2024-05-24 22:30:02] error: z2m: Publish 'set' 'state' to 'licht/eg/hwr' failed: 'Error: ZCL command 0x001788010d43dfd6/11 genLevelCtrl.moveToLevelWithOnOff({"level":0,"transtime":30}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (3))' ` This is an example from z2m addon...
> 
> Or do you need other logs?

I think you misunderstood me, all i'm saying is that i want to help the developers track the issue down and asking if they need any logs from me. Btw i'm getting the same ZCL command timeouts as you.

**Comment by GCRVL** [comment]
This sadly is still an issue on my Home Assistant Yellow.

**Comment by Patafoin** [comment]
Same here. I managed to make my device work by removing it with force deletion option on and adding it again. Worked some days and then the error appeared again.

**Comment by technoo10201** [comment]
Hello all, got the same issue few minutes ago after restarting my zigbee2mqtt docker container...

**Comment by NoAdO** [comment]
My problem was solved when i powered off both router valves for a while. Looks like some devices ruin the network and powering off or repaing rebuilds mesh and fixes problem, at least for some time

**Comment by nschllr** [comment]
I encountered the same problem after restarting my HA containers.  After rebooting the entire server, the problem persisted. However, it seems that I resolved it by updating the server's system (including some Docker updates) and performing another system reboot.

HA core: 2024.6.3
HA supervisor: 2024.06.0
Zigbee2mqtt: 1.38.0
Docker: 26.1.4

**Comment by sakcaj** [comment]
Same issue here, one device affected from what I see so far - 2 gang switch module (TS0002 / _TZ3000_lmlsduws)
There's delays, lack of responsiveness. 

TrueNas Scale: 24.04.1.1
HA core: 2024.6.3
HA supervisor: 2024.06.0
Zigbee2mqtt: [1.38.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.38.0) commit: [fe048e6](https://github.com/Koenkk/zigbee2mqtt/commit/fe048e6)
Docker: 26.1.4

```
2024-06-22 12:22:58Publish 'set' 'state' to 'Chandelier' failed: 'Error: ZCL command 0xa4c138039e236506/2 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 48268 - 2 - 42 - 6 - 11 after 10000ms)'
```
 
I've

**Comment by drupry** [comment]
Same problem here. I have problem with 2 Awox lights (btw both of them are the same but in Z2M appears as different models). I have tried ofc restart everything, repair both lights but still have this issue. First light identify itself as Awox 33957, model TLSR82xx, second light Awox 33955 model EGLO_ZM_TW. 

Core: 2024.6.4
Supervisor: 2024.06.2
Operating System: 12.4
Z2M: 1.38
coordinator: zStack3x0 rev. 20230507

I have 2 errors repeating
```Publish 'set' 'brightness' to 'koupelna stropní nad vanou' failed: 'Error: ZCL command 0xa4c138846224c888/1 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":450}, "timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 54809 - 1 - 50 - 8 - 11 after 10000ms)'```


and 


`Publish 'set' 'state' to 'koupelna stropní nad vanou' failed: 'Error: ZCL command 0xa4c138846224c888/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 54809 - 1 - 66 - 6 - 11 after 10000ms)'`

**Comment by Brax84** [comment]
Same problem, with HA on rasperry Pi3b+ conbee II

Core: 2024.6.4
Supervisor: 2024.06.2
Operating System: 12.4
Frontend: 20240610.1
Zigbee2mqtt: 1.38.0-1

Zigbee randomly work, randomly not work

**Comment by array81** [comment]
Same problem, any solution?

**Comment by lordbah** [comment]
Just started seeing this. On 1.39.0-1. HA 2024.7.1.

**Comment by LoulouCrypto** [comment]
> Just started seeing this. On 1.39.0-1. HA 2024.7.1.

I have the same problem on 1 device 

Any solutions?

**Comment by lordbah** [comment]
Rebooting the entire system brings things back to a working state for me, for a little while. Before long it gets hosed again.

SkyConnect 7.4.3 GA.

**Comment by iophobia** [comment]
Add me to the list. All routers will sporadically (every 10-14 days) become unavailable with that error. Only interim solution is restarting the HA host system. System runs on N100 box with HAOS and a ConBee II as coordinator.

Core 2024.7.1
Supervisor 2024.06.2
Operating System 12.4

**Comment by LoulouCrypto** [comment]
Maybe a fix. 
BTW, it worked for me 

With the last update, I had to UPDATE my Zigbee dongle and go on Ember driver : 
[https://github.com/Koenkk/zigbee2mqtt/discussions/21462](url)

I have a ZBDongle-E and i had to manually flash to the [ncp-uart-hw-v7.4.3.0-zbdonglee-115200.gbl](https://github.com/darkxst/silabs-firmware-builder/blob/main/firmware_builds/zbdonglee/ncp-uart-hw-v7.4.3.0-zbdonglee-115200.gbl) firmware 

I use this Web USB flasher : [https://darkxst.github.io/silabs-firmware-builder/](url)

Maybe try this for me now no error and everything works fine

**Comment by array81** [comment]
I use:
- Zigbee2MQTT 1.39.0
- ZBDongle-E with ncp-uart-hw-v7.4.3.0-zbdonglee-115200.gbl
- Ember driver

And this not solve my problems.

**Comment by rosicenko** [comment]
> I use:
> 
> * Zigbee2MQTT 1.39.0
> * ZBDongle-E with ncp-uart-hw-v7.4.3.0-zbdonglee-115200.gbl
> * Ember driver
> 
> And this not solve my problems.

Exactly same issue here

**Comment by coolspot18** [comment]
> Add me to the list. All routers will sporadically (every 10-14 days) become unavailable with that error. Only interim solution is restarting the HA host system. System runs on N100 box with HAOS and a ConBee II as coordinator.
> 
> Core 2024.7.1 Supervisor 2024.06.2 Operating System 12.4 Z2M 1.39.0 (within HA addon)


I'm running 1.39.1 and I experienced this issue for the first time - restarting the add-on seemed to also fix it, I did not need a full reboot.

**Comment by markus-fischbacher** [comment]
Same here:
Home Assistant 2024.7.4 on RPi 5
ConBee2
Z2M 1.39.1
Zigbee RGB light (TS0503B)

**Comment by codedesperate** [comment]
I just started getting this on 1.39.1. rolled back to 1.39.0 but error persists :( Tried rebooting didn't help.

**Comment by Tvojm100** [comment]
> Same here: Home Assistant 2024.7.4 on RPi 5 ConBee2 Z2M 1.39.1 Zigbee RGB light (TS0503B)

My ZigBee network devices (20 odd) have been running fine for a couple of years. I actually last added a TS0503B and that works for me fine. This was a couple of days ago. But a few days before that, I added a QS-Zigbee-SEC01-U and that device gets the timeout error.

**Comment by NikoGrub** [comment]
Same issue with 1 smart plug with power monitoring.

**Comment by firstchair** [comment]
Also here

**Comment by Razor648** [comment]
i have the same issue since today.
Home Assistant 2024.7.4 on RPi 5
ZBDongle-E
Z2M 1.39.1

Devices not working : 
ZBMINIL2, SNZB-04

```shell
zigbee2mqtt  | [2024-08-22 22:48:01] error:     z2m: Publish 'set' 'state' to 'Lumière Parking Garage ' failed: 'Error: ZCL command 0x0ceff6fffe1704ce/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Delivery failed for {"profileId":260,"clusterId":6,"sourceEndpoint":1,"destinationEndpoint":1,"options":4160,"groupId":0,"sequence":230})'
```

**Comment by maxifaxi** [comment]
same issue since last week
Raspberry 4
Z2M add on 1.39.1
zStack3x0 20230507

Device E2112 IKEA, interview fails with various errors.
- Error: ZCL command
- no active endpoints

Tried channels 11, 15, 20 and 25
With / Without USB 2.0 cable
On USB 3.0 and 2.0 port
Different locations in the house

The device is recognized and I see the picture of the device in the dashboard but the interview fails.

Is there any update from developer side? Is this bug worked on?

**Comment by bartj12** [comment]
![IMG_0545](https://github.com/user-attachments/assets/2a392231-afc8-4936-852a-451c7a9f72d7)

as a temporary fix I’m restarting Z2M twice a day (when no automations are running).

**Comment by xjikka** [comment]
I use SZLB-06. After the update to 2.5.2, my devices started disconnecting and stopped responding - "Publish set state to ... failed". I tried flashing it to 0.9.9, it was better, but it did the same thing (after a few hours the device stopped responding). So I did a flash to 2.3.6 (0.9.9 to 2.3.6  can be done over USB only). After flashing and restarting the Zigbee firmware returned to version 20221226 and since then /it was about a month ago/ everything is ok again. 
If anyone has problems with disconnecting SZLB-06, it's useless to try 0.9.9., just try to return it to 2.3.6 (and thus return Zigbee to 20221226).

**Comment by nmusatov** [comment]
I confirm that downgrade zigbee to version 20221226 solved the same issue for my ZigStar Olizig coordinator regardless of x2m version.

**Comment by SayAndre** [comment]
I just lost the connection to my INNR SP120 plugs after the update. 
How can I downgrade without destroying the connection to all other devices ? I tried to just restore a older backup but then, the addon never starts again, updating it back to 1.40.1 makes it work again, but the INNR SP120 Plugs are still not working anymore.

**Comment by mremedi2023** [comment]
Same here, you need to restart m2qtt permanently

**Comment by nmusatov** [comment]
> Same here, you need to restart m2qtt permanently

Full HomeAssistant restart (including mqtt) didn't resolve the issue for me

**Comment by Baael** [comment]
After a year I updated zigbee2mqtt in perfectly working network of devices, and now nothing is working correctly anymore. I am spammed by this error. It seems it is random, not related to any specific device.

**Comment by bricololo44** [comment]
Similar problem for me, after upgrade to Zigbee2MQTT 1.40.1
Module TS0003 => Recognised as "TS0003_switch_module" : Working Good
Module TS0002 => Recognised as "TS0003_basic" : NOT WORKING since 1.40.1 ( Error ZCL genOnOff)
Module TS0004 => Recognised as "TS0004_switch_module" : NOT WORKING since 1.40.1 ( Error ZCL genOnOff)
Module are recognized but error during switching
![Screenshot_error_Z2MQTT](https://github.com/user-attachments/assets/50f24ec7-5128-4e72-bcec-6f779a89ea66)

**Comment by MairusuPawa** [comment]
Impacted as well

![image](https://github.com/user-attachments/assets/135222b8-04d1-44a7-a5d4-7650d60a0805)

**Comment by leocotes** [comment]
Hello guys. 

I have the same issue. I try to use ember with last firmware and zstack, and i have the same problem:

Products: [ZB-TD5-RCW-GU10](https://www.zigbee2mqtt.io/devices/ZB-TD5-RCW-GU10.html#moes-zb-td5-rcw-gu10)

![image](https://github.com/user-attachments/assets/6ec62d7f-6ae4-4ace-8453-ce3faf3c9881)

**Comment by infinicode** [comment]
I can confirm the issue with a Sonoff ZBDongle-P running Zigbee2MQTT v1.40.1, after upgrading the firmware to the latest version.

- With firmware CC1352P2_CC2652P_launchpad_coordinator_20240710.hex the problem is present.
- Downgrading to CC1352P2_CC2652P_launchpad_coordinator_20230507.hex solves the issue.

**Comment by jLemmings** [comment]
I have the exact same issue in my network. 

Coordinator: SLZB-06, Firmware version: 20240710 v2.5.6
zigbee2mqtt: 1.40.1

```
[2024-10-07 17:16:34] error: 	z2m: Publish 'set' 'color_temp' to 'Office Light' failed: 'Error: ZCL command 0xa4c1382e9dd2da3e/1 lightingColorCtrl.moveToColorTemp({"colortemp":370,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Timeout - 12765 - 1 - 3 - 768 - 11 after 10000ms)'
[2024-10-07 17:16:57] error: 	z2m: Publish 'set' 'color_temp' to 'Office Light' failed: 'Error: ZCL command 0xa4c1382e9dd2da3e/1 lightingColorCtrl.moveToColorTemp({"colortemp":370,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Timeout - 12765 - 1 - 4 - 768 - 11 after 10000ms)'
```

**Comment by xjikka** [comment]
Here my results after about 2 months of testing.

Coordinator: SLZB-06M

Zigbee2mqtt: 1.40.1 + ESP 2.3.6. + Zigbee 20221216 - after 1 month was everything  OK

I've tried update zigbee2mqtt: 1.40.2 - OK
I've tried update ESP to 2.5.6 - OK

I've tried update Zigbee to 20240710 - problem is back. 
I've tried downgrade Zigbee to 20230507 - problem is gone, everything OK

After one week  zigbee2mqtt: 1.40.2 + ESP 2.5.6. + Zigbee 20230507- everything  still OK

**`I suggest to try downgrade Zigbee to 20230507 or older. Everything other (ESP, Zigbee2mqtt) does not matter.`**

**Comment by RNDMizer** [comment]
> Here my results after about 2 months of testing.
> 
> Coordinator: SLZB-06
> 
> Zigbee2MQTT: 1.40.1 + ESP 2.3.6. + Zigbee 20221216 - after 1 month was everything OK
> 
> I've tried update Zigbee2MQTT: 1.40.2 - OK I've tried update ESP to 2.5.6 - OK
> 
> I've tried update Zigbee to 20240710 - problem is back. I've tried downgrade Zigbee to 20230507 - problem is gone, everything OK
> 
> After one week Zigbee2MQTT: 1.40.2 + ESP 2.5.6. + Zigbee 20230507- everything still OK
> 
> **`If anyone has "Publish failed" issues, I recommend trying to downgrade Zigbee to 20230507 or older. Everything other (ESP, Zigbee2MQTT) doesn't matter.`**

Sorry for being daft, how do I downgrade the Zigbee version? I can't find results on Google.

**Comment by xjikka** [comment]
Hi, see screenshots

 

XJ

**Comment by xjikka** [comment]
Someone asked me how to downgrade Zigbee, here's how to do it on SZLB-06 via web admin

![1 - 2024-10-09 19_57_52-Firmware update - SLZB-06 Zigbee Ethernet POE USB Adapter and 6 more pages - Per](https://github.com/user-attachments/assets/5c1525e8-7927-4783-abd6-84b2573e036b)
![2 - 2024-10-09 20_00_29-Firmware update - SLZB-06 Zigbee Ethernet POE USB Adapter and 6 more pages - Per](https://github.com/user-attachments/assets/f7a54591-7822-4935-9254-f0d8842c4700)
![3 - 2024-10-09 19_56_44-Firmware update - SLZB-06 Zigbee Ethernet POE USB Adapter and 6 more pages - Per](https://github.com/user-attachments/assets/c74e8a2e-046f-4aa9-a99a-4da7c9e5d5ac)

**Comment by majkers** [comment]
Downgrading to CC1352P2_CC2652P_launchpad_coordinator_20230507 doesn't solve the problem for me with my Sonoff ZBDongle-P running Zigbee2MQTT v1.40.2

**Comment by majkers** [comment]
Since this issue is closed, I think noone will help us. Can someone reopen this issue?

**Comment by paveltsytovich** [comment]
We can`t reopen this issue, have no permission. I suggest to create new issue. How could create new issue with full describe issue?

**Comment by majkers** [comment]
@rw-django-fan-2020 can You reopen this issue since it is not fixed?

**Comment by majkers** [comment]
OK I decided to open new issue https://github.com/Koenkk/zigbee2mqtt/issues/24375. Please reposrt your problems there from now on
