### ISSUE TITLE
Third Reality 3RTHS24BZ Temp and Humidity Shows as Mains Powered Instead of Battery

### ISSUE THREAD

**Issue by jmedemar** [Koenkk/zigbee2mqtt#22914]
### What happened?

The Third Reality 3RTHS24BZ Temp and Humidity Sensors show as Mains Powered Instead of Battery Powered. This may be causing the errors upon startup shown below, because zigbee2mqtt cannot connect to the sensors until they wake up. Once the sensors wake up, there are no more errors in the log.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2796508/a84243ba-cb57-418a-bbae-8b65615f0946)

```
Info 2024-06-03 11:25:21Configuring 'Living Room Hallway Sensor'
Info 2024-06-03 11:25:22Configuring 'Main Bath Sensor'
Error 2024-06-03 11:25:26Failed to configure 'Living Room Hallway Sensor', attempt 1 (Error: Bind 0x282c02bfffe3a766/1 genPowerCfg from '0xdc8e95fffe0b6126/1' failed (Delivery failed for {"profileId":0,"clusterId":33,"sourceEndpoint":0,"destinationEndpoint":0,"options":4416,"groupId":0,"sequence":177}) at EmberOneWaitress.deliveryFailedFor (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\adapter\oneWaitress.ts:96:31) at EmberAdapter.onMessageSentDeliveryFailed (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\adapter\emberAdapter.ts:540:30) at Ezsp.emit (node:events:513:28) at Ezsp.ezspMessageSentHandler (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\ezsp\ezsp.ts:3960:18) at Ezsp.callbackDispatch (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\ezsp\ezsp.ts:797:18) at Ezsp.tick (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\ezsp\ezsp.ts:451:22) at listOnTimeout (node:internal/timers:569:17) at processTimers (node:internal/timers:512:7))
Info 2024-06-03 11:25:29Received network/route error ROUTE_ERROR_INDIRECT_TRANSACTION_EXPIRY for "39970".
Info 2024-06-03 11:25:30Configuring 'Basement Bath Sensor'
Info 2024-06-03 11:25:30Received network/route error ROUTE_ERROR_INDIRECT_TRANSACTION_EXPIRY for "39970".
Error 2024-06-03 11:25:31Failed to configure 'Main Bath Sensor', attempt 1 (Error: Bind 0x282c02bfffe39aa7/1 genPowerCfg from '0xdc8e95fffe0b6126/1' failed (Delivery failed for {"profileId":0,"clusterId":33,"sourceEndpoint":0,"destinationEndpoint":0,"options":4416,"groupId":0,"sequence":179}) at EmberOneWaitress.deliveryFailedFor (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\adapter\oneWaitress.ts:96:31) at EmberAdapter.onMessageSentDeliveryFailed (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\adapter\emberAdapter.ts:540:30) at Ezsp.emit (node:events:513:28) at Ezsp.ezspMessageSentHandler (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\ezsp\ezsp.ts:3960:18) at Ezsp.callbackDispatch (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\ezsp\ezsp.ts:797:18) at Ezsp.tick (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\ezsp\ezsp.ts:451:22) at listOnTimeout (node:internal/timers:569:17) at processTimers (node:internal/timers:512:7))
Info 2024-06-03 11:25:32Received network/route error ROUTE_ERROR_INDIRECT_TRANSACTION_EXPIRY for "39970".
Info 2024-06-03 11:25:33Received network/route error ROUTE_ERROR_INDIRECT_TRANSACTION_EXPIRY for "43858".
Error 2024-06-03 11:25:35Failed to configure 'Basement Bath Sensor', attempt 1 (Error: Bind 0x282c02bfffe3a768/1 genPowerCfg from '0xdc8e95fffe0b6126/1' failed (Delivery failed for {"profileId":0,"clusterId":33,"sourceEndpoint":0,"destinationEndpoint":0,"options":4416,"groupId":0,"sequence":180}) at EmberOneWaitress.deliveryFailedFor (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\adapter\oneWaitress.ts:96:31) at EmberAdapter.onMessageSentDeliveryFailed (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\adapter\emberAdapter.ts:540:30) at Ezsp.emit (node:events:513:28) at Ezsp.ezspMessageSentHandler (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\ezsp\ezsp.ts:3960:18) at Ezsp.callbackDispatch (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\ezsp\ezsp.ts:797:18) at Ezsp.tick (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\ezsp\ezsp.ts:451:22) at listOnTimeout (node:internal/timers:569:17) at processTimers (node:internal/timers:512:7))
Info 2024-06-03 11:25:37Received network/route error ROUTE_ERROR_INDIRECT_TRANSACTION_EXPIRY for "43858".
Info 2024-06-03 11:25:38Received network/route error ROUTE_ERROR_INDIRECT_TRANSACTION_EXPIRY for "12732".
Info 2024-06-03 11:25:49Configuring 'Basement Bath Sensor'
Info 2024-06-03 11:25:54Received network/route error ROUTE_ERROR_MANY_TO_ONE_ROUTE_FAILURE for "58914".
Error 2024-06-03 11:25:54Failed to configure 'Basement Bath Sensor', attempt 2 (Error: Bind 0x282c02bfffe3a768/1 genPowerCfg from '0xdc8e95fffe0b6126/1' failed (Delivery failed for {"profileId":0,"clusterId":33,"sourceEndpoint":0,"destinationEndpoint":0,"options":4416,"groupId":0,"sequence":182}) at EmberOneWaitress.deliveryFailedFor (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\adapter\oneWaitress.ts:96:31) at EmberAdapter.onMessageSentDeliveryFailed (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\adapter\emberAdapter.ts:540:30) at Ezsp.emit (node:events:513:28) at Ezsp.ezspMessageSentHandler (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\ezsp\ezsp.ts:3960:18) at Ezsp.callbackDispatch (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\ezsp\ezsp.ts:797:18) at Ezsp.tick (C:\Program Files (x86)\HomeSeer HS4\Data\ZigbeePlus\zigbee2mqtt\node_modules\zigbee-herdsman\src\adapter\ember\ezsp\ezsp.ts:451:22) at listOnTimeout (node:internal/timers:569:17) at processTimers (node:internal/timers:512:7))
```

### What did you expect to happen?

The sensors should show as battery powered in the front end and that the log doesn't show errors connecting to these sensors before they wake up.

### How to reproduce it (minimal and precise)

Pair sensor. Reboot zigbee2mqtt, watch log for errors within a couple minutes.

### Zigbee2MQTT version

1.37.1

### Adapter firmware version

7.4.3

### Adapter

Sonoff Dongle-E

### Setup

Installed through Homeseer on Windows 11 Pro

**Comment by Skirmisher** [comment]
Seeing this issue with the same device using ZBDongle-E with Z2M 1.38.0. It was previously reported correctly as battery-powered on 1.36.

**Comment by marc-gist** [comment]
I'm also getting errors like:
```
Failed to configure 'thirdreality_temp_hum_sensor', attempt 1 (Error: Bind 0x282c02bfffe39964/1 genPowerCfg from '0x00124b0021cc4303/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Object.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:691:28 at processTicksAndRejections (node:internal/process/task_queues:95:5) at Queue.execute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Endpoint.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:464:13) at setupAttributes (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:75:13) at configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:112:17) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/index.ts:172:21) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:121:13) at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:174:17))
```
wonder if it is related.

**Comment by jmedemar** [comment]
Still an issue. Anything else I can get to help someone take a look into this?

**Comment by glassbase** [comment]
Just got 2 of these for BF. Seeing same issue.

**Comment by triosniolin** [comment]
I have 5 of these and am having the same problem with them all...

**Comment by peterwup** [comment]
Same here

**Comment by LBTHR333** [comment]
I just bought 8 of these, same issue.

**Comment by cerrsys** [comment]
+1

**Comment by jmedemar** [comment]
This is still an issue.

**Comment by jmedemar** [comment]
@chris-1243, I see you fixed this same issue with a different Third Reality sensor here #27210 . Any chance you could take a look at this one too?

**Comment by chris-1243** [comment]
It should be fixed in the latest-dev or in the next official release when accepted and merged by the dev team

**Comment by francoisp59** [comment]
On June 23rd I'm still seeing this issue in Home Assistant. Do we know if the solution has been pushed?

**Comment by 3reality-support** [comment]
@francoisp59 Upgrade the product to the latest version 1.00.40 and try again

![Image](https://github.com/user-attachments/assets/3f395b4a-2bff-4c7b-ae9f-8b741fa749c8)

**Comment by francoisp59** [comment]
@3reality-support As you suggested I've updated the firmware to v1.00.40 however it still showing as plugin power. In zigbee2mqtt I've tried to do a new interview but got no response. Do I need to remove it and re-add it?

![Image](https://github.com/user-attachments/assets/26b372cc-f7e2-47e6-b29a-253ee2882fef)

**Comment by 3reality-support** [comment]
@francoisp59 yes，remove it and re-add it

**Comment by francoisp59** [comment]
I've removed it, pushed the button on the side for 10 seconds and
zigbee2mqtt found it again but it's still showing as a plugin device.

**Comment by 3reality-support** [comment]
@francoisp59 First, delete the device, then restart z2m, and finally add the device(Please ensure that there are no external converters related to 3RTHS24BZ locally)

**Comment by francoisp59** [comment]
Thanks, that worked.

**Comment by felldo** [comment]
I had the same issue.

The suggestion didn't help directly but this is what I did:

- Restarting Z2M
- Removing the device
- Resetting the device
- Continuously pushing the button each second
- Removing the battery

note that the order of the list above is arbitrary. After trying 30 minutes with every possible combination of the steps above it started to work (for now). But removing the battery was an important step as far as I've noticed (when the sensor was in paring mode, or after pairing).
