### ISSUE TITLE
Wrong firmware flashed on IKEA LED2201G8, bulbs do only flash now, offline

### ISSUE THREAD

**Issue by MaxRower** [Koenkk/zigbee2mqtt#23325]
### What happened?

Today new a firmware upgrade for IKEA bulbs was offered, so I started to upgrade the corresponding bulbs.
Sometime later I noticed my LED2201G8 in the basement do flash every few seconds. They are offline, factory reset does not work.
After looking for the cause, I noticed the new 3.0.21 is not for the LED2201G8, but only for my other LED2107C4, which do work fine after the upgrade.
Since the firmware versions of both bulbs types where the same before, I think, there has to be some sort of error by IKEA? Or is it z2m?

### How to reproduce it (minimal and precise)

n/a

### Zigbee2MQTT version

1.38.0 commit: fe048e6

### Adapter firmware version

20221226

### Adapter

Sonoff USB P

### Setup

docker in lxc container

### Debug log

Logs for LED2201G8:
[2024-07-11 13:33:44] info:     z2m: Update available for 'Keller Lampe 2'
[2024-07-11 13:33:44] info:     z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Keller Lampe 2', payload '{"brightness":254,"color_mode":"xy","color_options":{"execute_if_off":true},"last_seen":"2024-07-11T13:33:44+02:00","linkquality":200,"power_on_behavior":"on","state":"OFF","update":{"installed_version":50331664,"latest_version":50331681,"state":"available"},"update_available":null}'
[2024-07-11 13:33:44] info:     z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"Keller Lampe 2","updateAvailable":true},"status":"ok","transaction":"izs9s-2"}'
[2024-07-11 13:33:44] info:     z2m: Update available for 'Keller Lampe 1'
[2024-07-11 13:33:44] info:     z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Keller Lampe 1', payload '{"brightness":254,"color_mode":"xy","color_options":{"execute_if_off":true},"last_seen":"2024-07-11T13:33:43+02:00","linkquality":196,"power_on_behavior":"on","state":"OFF","update":{"installed_version":50331664,"latest_version":50331681,"state":"available"},"update_available":null}'
[2024-07-11 13:33:44] info:     z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"Keller Lampe 1","updateAvailable":true},"status":"ok","transaction":"izs9s-1"}'

Logs for LED2107C4:
[2024-07-11 13:52:20] info:      z2m:mqtt: MQTT publish: topic 'fkg/Schlafzimmer Nachtkästchenlampe rechts', payload '{"action":"off","brightness":1,"color_mode":"color_temp","color_options":null,"color_temp":370,"last_seen":"2024-07-11T13:52:20+02:00","linkquality":144,"power_on_behavior":"on","state":"OFF","update":{"installed_version":50331664,"latest_version":50331681,"state":"available"},"update_available":null}'

**Comment by MaxRower** [comment]
Corresponding entries in http://fw.ota.homesmart.ikea.net/feed/version_info.json
Maybe the wrong entry is already removed?

{"fw_binary_url":"http://fw.ota.homesmart.ikea.net/global/GW1.0/01.21.031/bin/zingo_ws-0x2200-3.0.21-prod.ota.ota.signed","fw_file_version_LSB":33,"fw_file_version_MSB":768,"fw_filesize":307758,"fw_image_type":8704,"fw_manufacturer_id":4476,"fw_type":2},
{"fw_binary_url":"http://fw.ota.homesmart.ikea.net/global/GW1.0/01.21.031/bin/zingo_ws_soc-0x2206-3.0.21-prod.ota.ota.signed","fw_file_version_LSB":33,"fw_file_version_MSB":768,"fw_filesize":306714,"fw_image_type":8710,"fw_manufacturer_id":4476,"fw_type":2}

**Comment by Bkrickl** [comment]
I also flashed of my LED2201G8 to the newest version.
It is till working for me but now when i change the brightness the temperature is reset to some default value.

**Comment by CV8R** [comment]
Same problem - is there a way to roll the firmware back or is the bulb dead?

**Comment by sverrevh** [comment]
Came here to comment the same. Seems that 3.0.10 broke the bulb. @Koenkk can you prevent others from flashing this firmware to their bulbs asap?

**Comment by Bkrickl** [comment]
I also flashed two of my LED2201G8 and it seems to work fine for me.
I am currently on Z2M 1.36.1.

The only thing i needed to do was to re add the device because it had some strange behaviour (everytime i increased/decrease the brightness the color temp was reseted to some default value)

**Comment by MaxRower** [comment]
> I also flashed two of my LED2201G8 to 3.0.21 and it seems to work fine for me. I am currently on Z2M 1.36.1.
> 
> The only thing i needed to do was to re add the device because it had some strange behaviour (everytime i increased/decrease the brightness the color temp was reseted to some default value)

Maybe you have a different hardware revision of the bulb? I bought mine not even a month ago. I will take a close look at the bulb itself.

**Comment by phrozen77** [comment]
Errr.. sh... upgrade is in progress right now (z2m: 1.36.1) - i guess i'll find out what's in store for me as somehow stopping the upgrade is probably a worse idea than potentially bricking one bulb?

**Comment by MaxRower** [comment]
> Errr.. sh... upgrade is in progress right now (z2m: 1.36.1) - i guess i'll find out what's in store for me as somehow stopping the upgrade is probably a worse idea than potentially bricking one bulb?

I'd turn it off now, before it is at 100%. It happens all the time an update can't be finished, because someone turns the switch off.

**Comment by phrozen77** [comment]
Lets see what happens - switched the bulb off, Z2M still pretends the update is in progress...

**Comment by MaxRower** [comment]
The problem seems to exist when using the tradfri gateway as well, there's a reddit post as well, with my comments:
https://www.reddit.com/r/tradfri/comments/1e0ohmc/why_are_my_lamps_in_disco_mode/

**Comment by MaxRower** [comment]
> Lets see what happens - switched the bulb off, Z2M still pretends the update is in progress...
> 
> Edit: red popup came up, saying that the device didn't request any further data and called the update off...
> 
> Edit2: everything still seems to work correctly - update was only at 3.5%ish or something tho...

You're a lucky man!

**Comment by phrozen77** [comment]
Indeed! I need to level up to a "wise man" tho - read sh*t about updates before clicking any damn buttons :D

**Comment by MaxRower** [comment]
> Indeed! I need to level up to a "wise man" tho - read sh*t about updates before clicking any damn buttons :D

Well, this seems to be part of our education to "wise man".

**Comment by Bkrickl** [comment]
> > I also flashed two of my LED2201G8 to 3.0.21 and it seems to work fine for me. I am currently on Z2M 1.36.1.
> > The only thing i needed to do was to re add the device because it had some strange behaviour (everytime i increased/decrease the brightness the color temp was reseted to some default value)
> 
> Maybe you have a different hardware revision of the bulb? I bought mine not even a month ago. I will take a close look at the bulb itself.

I bought mine like 3-4 month ago.
Here is a screenshot of my bulb which is updated and working.

![Bildschirmfoto 2024-07-12 um 10 52 20](https://github.com/user-attachments/assets/92ea48d9-0464-4050-ae4b-9d8daa5b1790)

**Comment by phrozen77** [comment]
> After looking for the cause, I noticed the new 3.0.21 is not for the LED2201G8, but only for my other LED2107C4, which do work fine after the upgrade.

Just for the record: the LED2201G8 is the only lightbulb i've got on my Zigbee network... So, z2m (or Ikea, rather) addresses this bulb with that firmware update...

**Comment by enbyted** [comment]
I had the update offered for LED2201G8, however after re-triggering the update check a few minutes ago the update disappeared, so I guess the issue is resolved now?

**Comment by AndreasFlies** [comment]
Same here. Bought today. Old firmware was 3.0.8 (still shown in zigbee2mqtt)

**Comment by enbyted** [comment]
> Same here. Bought today. Old firmware was 3.0.8 (still shown in zigbee2mqtt)

Latest valid firmware for LED2201 is 3.0.10, so if you have 3.0.8 then you should see the update. See the release notes page: https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html

**Comment by wakuwaku** [comment]
Same here today. Slow flashing cold white light after updating my 2 LED2201G8 bulbs. Home Assistant/zigbee2mqtt has no control anymore after the update.

If they a bricked, how to swamp them for new bulbs at IKEA ?

**Comment by robertnisipeanu** [comment]
Well, just upgraded mine today and it's bricked. Sadly found out too late about this github issue.

Is there any way to reflash it or do I have to try convince IKEA to exchange the bulbs?

**Comment by bmork** [comment]
Ouch.  Same experinece here.  Interestingly enough, I updated two LED2201G8 from 3.0.10 to  3.0.21 and one them is working fine, while the other is blinking continuously.  They were bought together but are probably from different batches, since they came with different firmware revisions originally.

**Comment by Meckslo** [comment]
> Well, just upgraded mine today and they're bricked. Sadly found out too late about this github issue.
> 
> Is there any way to reflash it or do I have to try convince IKEA to exchange the bulbs?

My devices were bricked yesterday by the upgrade. I went to IKEA today and exchanged them. They accepted them without any issues. However, it didn't seem like the saleswoman was aware of the error.

**Comment by wakuwaku** [comment]
Just wonder if you get the same issue when installing the new bulbs. If we get new LED2201G8 and (auto) update them, do we repeat the issue?

**Comment by Meckslo** [comment]
> Just wonder if you get the same issue when installing the new bulbs. If we get new LED2201G8 and (auto) update them, do we repeat the issue?

I now have firmware 3.0.8 on the new bulbs. Currently, no new update is being offered through zigbee2mqtt.

**Comment by wakuwaku** [comment]
IKEA has confirmed to sent me 2 new LED2201G8 bulbs. 
I have just called customer service and explained them on internet there are bulb owners complaining about their bulbs has been bricked after the (auto) firmware update and leave them with out-of-control flashing bulbs.

Hope the "wrong" firmware is removed.

**Comment by sverrevh** [comment]
I only updated one LED2201G8 I had. I just returned the bricked bulb to IKEA and bought a new one. This one has firmware 2.4.5. Zigbee2mqtt still wants to update it to 3.0.21 (I think?, HomeAssistant lists it as 50331681) and also for the other LED2201G8 the update that bricks them is still available.

**Comment by fldc** [comment]
Found this thread after one of my bulbs starting blinking after a firmware update, my newest LED2201G8 IKEA bulb survived this update while an older one did not?

**Comment by MaxRower** [comment]
Maybe we should document, which bulbs survive the firmware update, and which do not? On my two bulbs, there are numbers printed, that differ somewhat, so maybe this relates to a hardware revision? Numbers are following the text "TRADRFI WS".
Those do not work with firmware 3.0.21, and had firmware 3.0.10 before the attempted upgrade:
2346 50050
2337 50050

I already contaced IKEA support for Austria, and they said, I should return the bulbs in the shop.

**Comment by bmork** [comment]
Can't check my working LED2201G8 right now, but the failing one is
2347 50050

ieee addresses might be an interesting variable as well?  My two LED2201G8 bulbs use different address series/OUIs
failing: 0x881a14fffexxxxxx
working: 0x980c33fffexxxxxx

**Comment by fldc** [comment]
> Can't check my working LED2201G8 right now, but the failing one is
> 
> 2347 50050
> 
> 
> 
> ieee addresses might be an interesting variable as well?  My two LED2201G8 bulbs use different address series/OUIs
> 
> failing: 0x881a14fffexxxxxx
> 
> working: 0x980c33fffexxxxxx
> 
> 
> 
> 
> 
> 

The failed ones were all 0x881, but I also have a 0xb43522fffexxxxxx which updated fine.

**Comment by sverrevh** [comment]
I bought two lamps at the same time, returned the other one that broke during the update already. Remaining one indeed starts with 0x811a1.....

**Comment by Bkrickl** [comment]
Yesterday they released a new firmware update for these bulbs: https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html

Someone already checked if this updated is working?

**Comment by vincentkoevoets** [comment]
> Yesterday they released a new firmware update for these bulbs: https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html
> 
> Someone already checked if this updated is working?

I would love to, but the bulbs are no longer reachable so how would we do - that? Mine appear to be completely bricked.

**Comment by lukasgierth** [comment]
I was one of the lucky ones where my bulp is still working with 3.0.10 and the update to the broken 3.0.21 never run through.
Would be able to test it, but can i see somewhere in zigbee2mqtt if the version it wants to update to is actually 3.0.22? I dont see anything useful in the Logs section. Don't want to risk my device trying to update to the definitely not working 3.0.21...

**Comment by bmork** [comment]
> Would be able to test it, but can i see somewhere in zigbee2mqtt if the version it wants to update to is actually 3.0.22? 

If you use the z2m web frontend:  Select the "state" tab on the device page.  It will  display the available version as "latest_version" under "update".  For example from my LED2201G8 currently running 3.0.21 (the lucky one that survived):
```
{
    "brightness": 198,
    "color_mode": "color_temp",
    "color_temp": 370,
    "linkquality": 18,
    "state": "OFF",
    "update": {
        "installed_version": 50331681,
        "latest_version": 50331682,
        "state": "available"
    },
    "color_options": null,
    "power_on_behavior": null,
    "update_available": null
}
```

Now those numbers are a bit difficult to read.  You need to convert them to hex to make any sense out of it:
```
50331681 = 0x3000021
50331682 = 0x3000022
```

If you run Home Assistant , then it will also report that decimal number as the available version.

**Comment by lukasgierth** [comment]
<img src="https://github.com/user-attachments/assets/f8e84803-a281-433c-8139-22796f213945" width="400" />

Update ran through without problems, LED works absolutely fine with v3.0.22.

**Comment by bmork** [comment]
And to add another success:  I went and got a LED2201G8 instead of the LED2103G5 mistake (starting to know my way between the "Returns" and "Trådfri" departments now :-).

The new LED2201G8 came with version 2.4.5. Updated it to 3.0.22 and it still works.

**Comment by sverrevh** [comment]
Did someone already manage to update their LED2201G8 with address 0x881... successfully to 3.0.22?

**Comment by McFlyPartages** [comment]
WARNING, I've updated to 50331682 (3.0.22) for LED2201G8 but I'm having the same problem, so I think it's best to wait.

**Comment by McFlyPartages** [comment]
> I already updated 10 of my bulbs an no issues so far. But bad to hear that it is not working for you.

Yes, it's weird, I'll see if the bulb reference is the same as the Z2MQTT tonight.

**Comment by m42j** [comment]
Only have a single samplepoint.
LED2201G8 with IEEE Address 0x881a...
Updated fw 3.0.10 to 50331682/3.0.22 and it started blinking, ZCL commands timeout. =7

**Comment by vincentkoevoets** [comment]
I might have stumbled onto something. Today I swapped my 6 bricked bulbs at the store for new ones. I paired them all in Z2M and everything worked fine. Then I went forward with updating, and from these 6 only 5 succeeded. The IEEE's were all seemingly random, the succeeded ones started with:
- 0x60ef
- 0x8c6f
- 0x980c
- 0x8c6f
- 0x8c6f
And the failed one started with 0xb0c7. So I'm starting to thing it has really nothing to do with the IEEE's. 
The thing that stood out for me was the firmware version prior to updating. The one that failed was the only one that was on version 3.0.8, while all the ones that succeeded were on version 2.4.5. I could see that for all the bulbs the offered firmware was the latest 3.0.22. This made me think that the problem maybe lies in the prior firmware version? The one that is present when the update starts? I don't know how that could make any sense but the different firmware version was the only thing that stood out.

**Comment by McFlyPartages** [comment]
In my case, it's only the LED2201G8s that have had this problem.

Here are the IEEE addresses, they were all 3.10 before or 3.08 before the update.
* 0x28dba7fffecfee8b
(0xD4CD)
* 0x28dba7fffea9e67b
(0xF26C)
* 0x881a14fffe13e037
(0x0E36)
* 0x881a14fffe2323d0
(0xE012)
* 0x881a14fffe36d8ee
(0x0DB0)
* 0x28dba7fffea9c8b9
(0xA81A)

![Capture d’écran du 2024-07-19 15-06-50](https://github.com/user-attachments/assets/22a495f8-a538-4102-9112-895154fe2b58)
![Capture d’écran du 2024-07-19 15-06-25](https://github.com/user-attachments/assets/f02fb173-1c63-445f-ab33-632f4f437e0a)
![Capture d’écran du 2024-07-19 15-05-33](https://github.com/user-attachments/assets/cb925720-2313-47df-b4b6-565986be9bc0)

**Comment by LeoeLeoeL** [comment]
Same device different bugs?
https://github.com/Koenkk/zigbee2mqtt/issues/21820

**Comment by jnswb** [comment]
Updated yesterday 3 bulbs to 3.0.22 and everything works fine.

**Comment by vincentkoevoets** [comment]
> In my case, it's only the LED2201G8s that have had this problem.
> 
> Here are the IEEE addresses, they were all 3.10 before or 3.08 before the update.
> 
> * 0x28dba7fffecfee8b
>   (0xD4CD)
> * 0x28dba7fffea9e67b
>   (0xF26C)
> * 0x881a14fffe13e037
>   (0x0E36)
> * 0x881a14fffe2323d0
>   (0xE012)
> * 0x881a14fffe36d8ee
>   (0x0DB0)
> * 0x28dba7fffea9c8b9
>   (0xA81A)
> 
> ![Capture d’écran du 2024-07-19 15-06-50](https://private-user-images.githubusercontent.com/44530252/350403771-22a495f8-a538-4102-9112-895154fe2b58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NTY1MzgsIm5iZiI6MTcyMTU1NjIzOCwicGF0aCI6Ii80NDUzMDI1Mi8zNTA0MDM3NzEtMjJhNDk1ZjgtYTUzOC00MTAyLTkxMTItODk1MTU0ZmUyYjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDEwMDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MDQzMjFjY2ZiMjRmODZmNGZhMTE0OTMxNmIzZWU0ZTA1OWZmMjQzNTNmZDczNzU1Nzg3MGY2ZDJmNTc2NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yf7WcH5KUzoXyyySOTP6R0cmyHfXBzqMdCi3SjVSDRU) ![Capture d’écran du 2024-07-19 15-06-25](https://private-user-images.githubusercontent.com/44530252/350403781-f02fb173-1c63-445f-ab33-632f4f437e0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NTY1MzgsIm5iZiI6MTcyMTU1NjIzOCwicGF0aCI6Ii80NDUzMDI1Mi8zNTA0MDM3ODEtZjAyZmIxNzMtMWM2My00NDVmLWFiMzMtNjMyZjRmNDM3ZTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDEwMDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzY2I1MDQ1N2VkYmI5ZTk0NWI3Yjc3ODczYzVhMmIzZjQzMWUyNWM0ZDk1NTljN2RkODIyNjEyNjYyYzRlZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ZKcWIC2z2jZ2u3Hfo7WggObMnFQIJzCBnVCrAOf59E) ![Capture d’écran du 2024-07-19 15-05-33](https://private-user-images.githubusercontent.com/44530252/350403790-cb925720-2313-47df-b4b6-565986be9bc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NTY1MzgsIm5iZiI6MTcyMTU1NjIzOCwicGF0aCI6Ii80NDUzMDI1Mi8zNTA0MDM3OTAtY2I5MjU3MjAtMjMxMy00N2RmLWI0YjYtNTY1OTg2YmU5YmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDEwMDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YzQ1MGMxY2E5NWJkN2EzMmE2YzA3NTUwZGQwYzM3MWIyNjIwZGJmNzllZWFlYTlkNjBlM2IwNjA1NDhlYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1DR8ZSaffkFO9GqelOBKangf6muKjYrIT2BQus7c0Sc)

So it begins to look more like some sort of russian roulette now. I don't see anything else that sets the failing ones apart from the ones that do successfully update. Could it be something in the update sequence or circumstances? I know from experience these bulbs need to be very close to the coordinator while pairing, maybe they need to be just as close while updating? These might be the cheapest bulbs on the market, but they sure also seem to be the pickiest.

**Comment by m42j** [comment]
> So it begins to look more like some sort of russian roulette now. I don't see anything else that sets the failing ones apart from the ones that do successfully update. Could it be something in the update sequence or circumstances? I know from experience these bulbs need to be very close to the coordinator while pairing, maybe they need to be just as close while updating? These might be some of the cheapest bulbs on the market, but they sure also seem to be the pickiest.

I read McFly's list as failed lights, so IEEE 0x881a would fall in line with other failed lights,  no? (And adding 0x28db to the possibly troublesome ones.) IEEE range could indicate hardware revisions/production runs, that's why it's interesting to me. But only IKEAs supplier(s) actually know if that's the case.

**Comment by G-glop** [comment]
I got a replacement bulb with fw 3.0.8 and OTA immediately killed it, don't know what version was offered because it doesn't show in the log.

**Comment by fldc** [comment]
> I got a replacement bulb with fw 3.0.8 and OTA immediately killed it, don't know what version was offered because it doesn't show in the log.
> 
> Could we not be making e-waste?

Looks like bulbs shipping with 3.0.8 is the ones bricking, that was the case here at least.

**Comment by sverrevh** [comment]
> Did someone already manage to update their LED2201G8 with address 0x881... successfully to 3.0.22?

To answer my own question, just updated my 0x881.. Bulb to 3.0.22 from 3.0.10 without issues.

**Comment by LeoeLeoeL** [comment]
> To answer my own question, just updated my 0x881.. Bulb to 3.0.22 from 3.0.10 without issues.

I made the same but contunue to suffer about "spontaneous illuminations"

**Comment by vincentkoevoets** [comment]
> > I got a replacement bulb with fw 3.0.8 and OTA immediately killed it, don't know what version was offered because it doesn't show in the log.
> > Could we not be making e-waste?
> 
> Looks like bulbs shipping with 3.0.8 is the ones bricking, that was the case here at least.

That might be it. I returned my last bricked bulb yesterday and got a new one, this on again has 3.0.8. I think I will keep this one just the way it is for now, just to be sure.

**Comment by G-glop** [comment]
Update: one of the bulbs i've previously updated to 3.0.22 just started flashing after i messed with the "Execute if off" setting.

**Comment by sverrevh** [comment]
@G-glop thanks, I had the same. With that setting on the light goes on, goes off and goes on again when turning on. After disabling this is not happening anymore

**Comment by Belaial** [comment]
Add me to the list of failed bulbs.... found this thread to late :disappointed: 

I have 3 x LED2201G8 and all are bricked now, bought them 2 weeks ago

0x28dba7fffe5fb1ff
0x881a14fffe0ea0a6
0x28dba7fffe5ff182

They all had 3.0.8 from factory, update was to 3.0.22, one bulb managed to report the correct version before it died it seems but the other two are still showing 3.0.8, all are offline now and just flashing white / orange, re-pairing does not work..... feels great.....


![image](https://github.com/user-attachments/assets/1860bfc7-4117-43fa-a032-bbca406f5221)

**Comment by LeoeLeoeL** [comment]
I don't understand why these bulbs have so many different behaviours.

**Comment by vincentkoevoets** [comment]
It remains a mystery indeed. Today I updated my last 3.0.8, expecting it to fail but it upgraded without problems. It did took some precautions, like turning off the 'Execute if off' setting in Z2M, and putting the bulb right next to the Zigbee coordinator. So maybe that helped, but either way there is no way to know for sure I'm afraid.

**Comment by LeoeLeoeL** [comment]
I can pair these bulbs to Z2M or Deconz and they work for a little time.
Then they start to switch on without any command or they leave the network.
Under Hue bridge they have the opposite behaviour.
Sometimes when i want to switch them on they appear on in HA or Hue app but they stay off. To fix it I have to power them off.

**Comment by Belaial** [comment]
Spent a few hours troubleshooting this last night but they are truly bricked, nothing I tested brings them back or puts them in paring mode again, worst part is there is no IKEA where I live so will be a month before I can get them replaced.

This is the first time ever I had any issues at all with a Z2M OTA of any kind, amazed it turned out to be a big player like IKEA.

Also reading on Reddit there are even people with IKEAs own hub having these issues so..... yeah..... I don't think this is related to Z2M at all.

**Comment by Belaial** [comment]
Came to think of the title on this issue "Wrong firmware flashed on IKEA LED2201G8", do we actually know this or was this the assumption when the issue first started?

Looking at the release notes here for the version I flashed yesterday https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html

```
Release Version: 1.27.1.1
16th July 2024
New features and changes in Accessories:
TRÅDFRI white spectrum bulb E27 (3.0.22)
Product ID: LED2201
◆ Bug fixes.
```

It does seem to be a planned release for the correct hardware type, so I guess the title is old and not updated on this issue.

**Comment by LeoeLeoeL** [comment]
I really don't know what that release fixed.
Nothing changed for me.

**Comment by Belaial** [comment]
Just sad when companies more and more just list "Bug fixes" or along those lines instead of actually telling what they are fixing.

I never had any issues on 3.0.8 for those 10 minutes I got to use the bulbs :smile: But once I saw the OTA notice I just updated one at a time since I never had OTA issues before.

**Comment by happyjaxx** [comment]
Well...
I bet my neighbors love me by now:
Installed a 0x881a 3.08 LED2201G8 and launched the OTA around midnight... it probably finished, since the lamp has been offline for 7 hours and from the camera I can see it blinking ...
Bummer

**Comment by LeoeLeoeL** [comment]
After this:
![image](https://github.com/user-attachments/assets/bd1ac7fc-8e2c-4e7c-9d8f-3b199a08bfc6)
that didn't fix anything...
Now:
![image](https://github.com/user-attachments/assets/3e5e17a0-b3c9-4145-a7d1-ee0d0e860177)
Tonight I update them but... I don't feel so optimistic.

**Comment by vincentkoevoets** [comment]
![ab67616d0000b273950359444321d635b59838b3.jpeg](https://github.com/user-attachments/assets/1e6cb5ea-2cf7-4f7b-95d7-a91bc11d613e)

**Comment by LeoeLeoeL** [comment]
After 2 hours I was unable to update.
The first bulb left the network immediately while the second one reached at its best 58% of update and then reset itself.

**Comment by Belaial** [comment]
> After 2 hours I was unable to update. The first bulb left the network immediately while the second one reached at its best 58% of update and then reset itself.

The one that left the network, is it working again or did the update brick it?


I have not gotten my bulbs replaced yet (no IKEA where I live so takes some time....)

I won't update the next ones I get before it's 100% confirmed the update really works.....

**Comment by LeoeLeoeL** [comment]
> The one that left the network, is it working again or did the update brick it?

Now the 2 bulbs are connected again to the Hue bridge.
> I have not gotten my bulbs replaced yet (no IKEA where I live so takes some time....)

I lost the receipt of purchase, I don't know if Ikea will change without that.
> I won't update the next ones I get before it's 100% confirmed the update really works.....

Reading this thread I realized these devices have many different behaviour for different users, I think you'll never read a 100%.
Speaking about 100%, yesterday night, a LED2201 reached 99.54% of update processing and then stopped and reported a failed update. :-(

**Comment by vincentkoevoets** [comment]
Flashed 6 bulbs from 3.0.22 to 3.0.23 without any problems.

**Comment by LeoeLeoeL** [comment]
> Flashed 6 bulbs from 3.0.22 to 3.0.23 without any problems.

And are they working normally?

**Comment by vincentkoevoets** [comment]
> > Flashed 6 bulbs from 3.0.22 to 3.0.23 without any problems.
> 
> And are they working normally?

Haha yes, without any problems. I didn't even have to move the bulbs closer to the coordinator. Just updated, all good. But as mentioned by yourself, this is no guarantee that it will work for you. We don't know why and maybe never will, but that's the way it is.

**Comment by Belaial** [comment]
> > > Flashed 6 bulbs from 3.0.22 to 3.0.23 without any problems.
> > 
> > 
> > And are they working normally?
> 
> Yes, without any problems. I didn't even have to move the bulbs closer to the coordinator. Just updated, all good. But as mentioned by yourself, this is no guarantee that it will work for you. We don't know why and maybe never will, but that's the way it is.

Ok, sounds good.... I mean better :) As you say, we will never know.

If your bulbs works normally for a few months maybe I will take the risk to upgrade later also (still not gotten them replaced), I saw on Reddit somewhere that people also got broken bulbs all of a sudden long after updating, fingers crossed it wont happen to you.
