### ISSUE TITLE
Zigbee2MQTT error when changing settings - BUG in version 1.40.0-1 on presence sensor TY_24G_Sensor_V2 / _TZE204_ztqnh5cg 

### ISSUE THREAD

**Issue by alexvaltchev** [Koenkk/zigbee2mqtt#23857]
### What happened?

I have a presence sensor [TY_24G_Sensor_V2 1](https://www.zigbee2mqtt.io/devices/TY_24G_Sensor_V2.html#ihseno-ty_24g_sensor_v2) which stopped working when I updated my Zigbee2MQTT on Sep 1, 2024 from version 1.39.1-1 to 1.40.0-1

The device started showing as Offline and trying to change ANY setting gives this error: 
```
z2m: EventBus error 'Publish/mqttMessage': Cannot read properties of undefined (reading 'some')
```

Here is a link with screenshots in Home Assistant Community. Reverting back to 1.39.1-1 works fine. [LINK](https://community.home-assistant.io/t/zigbee2mqtt-error-when-changing-settings/766774)

I am attaching debuging log after reverting to the older version where it works. OR do I need to update again to the latest version then give debug log?

### What did you expect to happen?

I expect to work just how it was working until now. I need to be able to change every setting without getting errors.

### How to reproduce it (minimal and precise)

Update to the latest version of Z2M 1.40.0-1 and try to change settings like Maximum Distance and etc on device https://www.zigbee2mqtt.io/devices/TY_24G_Sensor_V2.html#ihseno-ty_24g_sensor_v2)
The icon is also not correct. 

The actual device is this: https://smarthomescene.com/reviews/new-tuya-24ghz-zigbee-presence-sensor-review/

![Screenshot_5](https://github.com/user-attachments/assets/03487017-98eb-4d93-a4be-07151a2066c5)

Here is the error message when trying to change any setting:
![2b4d8a95bdcf2735d4de5c555473aa2721c9b2fd](https://github.com/user-attachments/assets/3b5af008-f46b-47f0-89b0-4108c084ca00)

### Zigbee2MQTT version

1.40.0-1

### Adapter firmware version

 7.4.3 [GA]

### Adapter

HomeAssistant SkyConnect  

### Setup

I have mini PC and using HA OS directly installed to it.

### Debug log

[log.log](https://github.com/user-attachments/files/16887083/log.log)

**Comment by alexvaltchev** [comment]
I have those as well but since they are (set and forget) I have not touch them for a long time, so I did not notice. But the one I mentioned above is new and I was still tweaking it and I notice it... I hope an update comes soon to fix all this.

**Comment by jesse-kaufman** [comment]
That’s fixed in the dev branch

**Comment by alexvaltchev** [comment]
So next month update on October 1st all should be good. I will stick with the older version until then, it works. Thanks
P.S. What are the pros and cons using the Dev branch compared to the regular one?

**Comment by mrbean27123** [comment]
> That’s fixed in the dev branch

I'm using Z2M Edge and nothing has changed, still the same errors. Or the Edge version needs to be updated somehow, because since the main version 1.40.0 was released, I have not had any updates in Edge

**Comment by jesse-kaufman** [comment]
It's at least fixed in the latest-dev docker image (1.40.0-dev commit: 557b17a) .. maybe you're on the HA add-on that hasn't been updated yet?

**Comment by jesse-kaufman** [comment]
> So next month update on October 1st all should be good. I will stick with the older version until then, it works. Thanks P.S. What are the pros and cons using the Dev branch compared to the regular one? IS it called "Zigbee2MQTT Edge" ? or

https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html

**Comment by Koenkk** [comment]
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/23821

I will make a hotfix release in the coming days.
