### ISSUE TITLE
Tuya PA-44Z Smoke Det Fails to reset Alarm and PPM State

### ISSUE THREAD

**Issue by ckglobalroaming** [Koenkk/zigbee2mqtt#24945]
### What happened?

When Test or trigger Tuya PA-44Z the device reports SMOKE:{TRUE} and PPM:{VALUE} however when the device returns to normal state, Z2M does not refect the normal state values. both SMOKE and PPM remain at the alarmed states indefinitley.

### What did you expect to happen?

When Test or trigger Tuya PA-44Z the device reports SMOKE:{TRUE} and PPM:{VALUE}. When the device returns to normal state, Z2M reports the normal state values  SMOKE:{FALSE} and PPM:0

### How to reproduce it (minimal and precise)

Spray test smoke, get alarm, observe alarm states in Z2M. Clear smoke, values remain in Z2M hours later.
I would expect to be able to resolve this with Zigbee Endpoint/Cluster/repintervals but this is TUYA notZigbee.
Any assistance appreciated. I purchased 20 of these damn things so i could hook them to Homeassistant and they are no value if they stay in alarm...

### Zigbee2MQTT version

1.41.0

### Adapter firmware version

20221226 (best stability)

### Adapter

CC2652P SLZB-06 Ethernet

### Setup

Homeassistant

**Comment by ckglobalroaming** [comment]
Device is normal for hours but still reports

```
[2024-11-28 10:49:59] debug:    z2m: Received Zigbee message from 'Smoke Detector Garage', type 'attributeReport', cluster 'genBasic', data '{"modelId":"TS0601"}' from endpoint 1 with groupID 0
[2024-11-28 10:49:59] info:     z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Smoke Detector Garage', payload '{"battery":100,"device_fault":0,"last_seen":"2024-11-28T10:49:59+10:00","linkquality":131,"silence":false,"smoke":true,"smoke_concentration":100,"test":false}'
```

**Comment by alex1702** [comment]
I have exactly the same problem and don't know whether it's due to zigbee2mqtt or the smoke detectors themselves. If it is due to the smoke detectors, is it possible to reset the status after a certain time?

**Comment by ckglobalroaming** [comment]
Bump. Smoke detectors. Assistance please

**Comment by Poci** [comment]
Same problem here, both SMOKE and PPM remain at the alarmed states indefinitely.

**Comment by Poci** [comment]
> It seems to be due to the smoke detectors, someone else has also bought such models but from a different dealer and they work. I then ordered these too and complained to aliexpress about the others. The status of the new ones is reset correctly. But I have only tested one out of 8 so far.
> 
> Purchased from: https://a.aliexpress.com/_ExTZED6
> 
> But I still think it would be good to have a workaround for these strangely behaving ones.

Mine detector is this one https://vi.aliexpress.com/item/1005005855776130.html

**Comment by mjenda** [comment]
> It seems to be due to the smoke detectors, someone else has also bought such models but from a different dealer and they work. I then ordered these too and complained to aliexpress about the others. The status of the new ones is reset correctly. But I have only tested one out of 8 so far.
> 
> Purchased from: https://a.aliexpress.com/_ExTZED6
> 
> But I still think it would be good to have a workaround for these strangely behaving ones.

I've recently received a device from the same seller, and encountered the same issue. The only way to fix it was to reconnect it to the network.

During testing (by putting out the match near the sensor), I discovered that the device gets stuck only if I press the mute button, which is inevitable because the buzzer is very loud. However, if I tolerate the noise and avoid pressing the mute button, it eventually resets to normal operation on its own.

**Comment by ckglobalroaming** [comment]
Pulled them all out sent them back. Lesson learnt.

On 26 Dec 2024, at 7:19 am, Marek Jenda ***@***.***> wrote:

﻿

It seems to be due to the smoke detectors, someone else has also bought such models but from a different dealer and they work. I then ordered these too and complained to aliexpress about the others. The status of the new ones is reset correctly. But I have only tested one out of 8 so far.

Purchased from: https://a.aliexpress.com/_ExTZED6

But I still think it would be good to have a workaround for these strangely behaving ones.

I've recently received a device from the same seller, and encountered the same issue. The only way to fix it was to reconnect it to the network.

During testing (by putting out the match near the sensor), I discovered that the device gets stuck only if I press the mute button, which is inevitable because the buzzer is very loud. However, if I tolerate the noise and avoid pressing the mute button, it eventually resets to normal operation on its own.

**Comment by Gorgue** [comment]
I'm the same issue

**Comment by efranulic** [comment]
Yes, I have this issue too

**Comment by efranulic** [comment]
> It seems to be due to the smoke detectors, someone else has also bought such models but from a different dealer and they work. I then ordered these too and complained to aliexpress about the others. The status of the new ones is reset correctly. But I have only tested one out of 8 so far.
> 
> Purchased from: https://a.aliexpress.com/_ExTZED6
> 
> But I still think it would be good to have a workaround for these strangely behaving ones.

I think this could be tested connecting the smoke detector directly to Tuya app and checking if it behaves like when connected to z2m.

**Comment by henkiejan1** [comment]
Have 4 of this sensors and the concentration wil still  report a value after smoke is detected. But when i removed the battery press few times on the test button and installed the battery again it's back to zero. If i press the test button just for test it will test correctly and press quicly again and it will mute. But test and it will also correctly back to normal. But the silence button in Z2M does  nothing and does not work...

**Comment by HolgerReimers** [comment]
> Have 4 of this sensors and the concentration wil still report a value after smoke is detected. But when i removed the battery press few times on the test button and installed the battery again it's back to zero. 


That helped and worked for me as well. Thank you!

**Comment by cypherbits** [comment]
Same issue on the latest version. Plus the self-test action not working with error message 'Error: No datapoint defined for 'self_test''

**Comment by HeinMelissen** [comment]
I've got 9 of these smoke detectors. Use normal 9v (alkaline) batteries, but they drain within 2 months.
Is this a problem with these smoke detectors, or do I need an update (OTA or something)

**Comment by alvarokrn** [comment]
I have the same problem. I did a test with real smoke and it still show smoke concentration 20ppm

**Comment by alvarokrn** [comment]
Is this solved?

**Comment by alvarokrn** [comment]
Commenting just to keep the ticket open

**Comment by SmOeL-swdev** [comment]
Same issue here with this smoke detector (_TZE284_rccxox8p), via MQTT there is a set topic which can be used to reset and let the device reports its entire status, however for such a device this should be done automaticly. Otherwise the workaround would need to be that the report is requested upon a certain interval

**Comment by cypherbits** [comment]
No activity does not mean it is fixed.

**Comment by ckglobalroaming** [comment]
Not resolved.

**Comment by SmOeL-swdev** [comment]
> No activity does not mean it is fixed.

Nothing to add! Good comment

**Comment by nicopeet911** [comment]
Same here, after wachting a youtube reviewer succesfully ingrating this smoke detecter in Z2M I myself bought 7x the PA-44Z, they all work, even the mute button in Z2M when alarm goes ON, but only problem is the statuses of smoke detection, PPM value and Test button don't reset. 

After testing with vapour smoke smoke detection state changes to True, but no matter what I try is does not get back at false state. Same goes for PPM status, and test button status, once test button is pressed on the device itself status changes to True, and stays True. When pressing the test bottom once more, status change to False for a split second followed by True en remains True without ever going back to False. Even resetting the device Z2M front End.

Only thing that works is rejoining the smoke alarm to the Zigbee network by "permitting joining" and pressing the button for 10 seconds on the smoke alarm.

**Comment by EmielWavin** [comment]
> After testing with vapour smoke smoke detection state changes to True, but no matter what I try is does not get back at false state. Same goes for PPM status, and test button status, once test button is pressed on the device itself status changes to True, and stays True. When pressing the test bottom once more, status change to False for a split second followed by True en remains True without ever going back to False. Even resetting the device Z2M front End.
> 
> Only thing that works is rejoining the smoke alarm to the Zigbee network by "permitting joining" and pressing the button for 10 seconds on the smoke alarm.

I've noticed that (using MQTT explorer for instance), you can set some of the registers e.g. smoke detection false (don't remember exactly) to make it reset, but I don't want to overwrite these device settings in order to reset.
Stil waiting on a solution TBH.

**Comment by alvarokrn** [comment]
No activity does not mean it is fixed.

**Comment by alvarokrn** [comment]
No activity does not mean it is fixed.

**Comment by nicopeet911** [comment]
No issue is still remaining, same as from I started this thread. But learned to life with it for now. As long as smoke is detected, and they don’t falsely trigger them selves I’m happy (enough) with them. Resetting them is 5 minutes and my house does not burn down that often luckily. Still would be nice if Zigbee2Mqtt could solve this issue on there end?

**Comment by SmOeL-swdev** [comment]
> No issue is still remaining, same as from I started this thread. But learned to life with it for now. As long as smoke is detected, and they don’t falsely trigger them selves I’m happy (enough) with them. Resetting them is 5 minutes and my house does not burn down that often luckily. Still would be nice if Zigbee2Mqtt could solve this issue on there end?

You've reported the issue and multiple others facing the same issue, as you can see in this thread. You figured a workable solution for you while the others don't so that incentive enough to get this fixed

**Comment by alvarokrn** [comment]
It still isn't fixed

**Comment by ZTHawk** [comment]
@SmOeL-swdev How to do a reset via MQTT Explorer (mqtt topic)?

**Comment by SmOeL-swdev** [comment]
> [@SmOeL-swdev](https://github.com/SmOeL-swdev) How to do a reset via MQTT Explorer (mqtt topic)?

Don't exactly remember which topic. Its a long time ago and not much progress with has been made with this as you can see.
I believe I was able to do reset on the alert value, so that it reset to its 'normal value'. Play around with MQTT Explorer, that should give some results.

Good luck.

**Comment by tjuanma** [comment]
Same problem here with 3 of my 4 devices. DAMN
