### ISSUE TITLE
Samsung Smartthings Multipurpose sensor (2018 model) (IM6001-MPP01) not reporting most sensors

### ISSUE THREAD

**Issue by Nickno95** [Koenkk/zigbee2mqtt#25277]
### What happened?

The device is not reporting most of its sensors. I tried resetting and repairing but the exposes are still mostly missing. 

If I try and reconfigure it, it throws these errors:

`z2m: Failed to configure '0x286d970001087d60', attempt 6 (Error: ZCL command 0x286d970001087d60/1 genPollCtrl.write({"longPollInterval":3600}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Status 'READ_ONLY') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:350:28) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:956:26) at Endpoint.write (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:393:9) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/smartthings.ts:309:13) at Configure.configure (/app/lib/extension/configure.ts:130:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:57:21) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:211:17))`

`Failed to configure (ZCL command 0x286d970001087d60/1 genPollCtrl.write({"longPollInterval":3600}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Status 'READ_ONLY'))`

These are not reporting anything:
- battery (Null %)
- moving (Null)
- X axis (Null)
- Y axis (Null)
- Z axis (Null)

These are working:
- temperature
- contact
- battery low
- tamper
- linkquality

The power item under the about tab is a blinking red %.

I tried opening and closing the contact for 20 seconds like the notes for it say here: https://www.zigbee2mqtt.io/devices/IM6001-MPP01.html

### What did you expect to happen?

The battery, moving, x_axis, y_axis, z_axis sensors to expose their values.

### How to reproduce it (minimal and precise)

Reset and pair device.

### Zigbee2MQTT version

1.42.0

### Adapter firmware version

0x264a0700

### Adapter

ConBee II

### Setup

docker container

### Debug log

[log.log](https://github.com/user-attachments/files/18214571/log.log)

**Comment by Fabianreisinger1998** [comment]
Same Problem for me

**Comment by dewmgaze** [comment]
Same issue here with two of these sensors.  Moved from ZHA to Z2M in hopes of gaining tilt sensors.  In ZHA the "Moving" sensor worked, and tilt values did not exist as state values but did fire off events.

**Comment by natefelt** [comment]
Still an issue in 2.0.0.

**Comment by Koenkk** [comment]
Assuming this has been fixed by https://github.com/Koenkk/zigbee-herdsman-converters/pull/8676, thanks @natefelt !

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

After updating make sure to re-configure the device by pressing the yellow refresh button.

**Comment by toxic0berliner** [comment]
hmmm, sorry to bother, but seems it's not solved, I have the device, I a running it with zigbee2mqtt edge which seems to be running  `/app/node_modules/.pnpm/zigbee-herdsman-converters@23.0.0/` so I believe https://github.com/Koenkk/zigbee-herdsman-converters/pull/8676 is included with `const payloadX = reporting.payload("x_axis", 10, constants.repInterval.MINUTE, 1);` for example.
Sadly, even deleting then re-adopting the device, I still see null for most of the sensors...

Should I reopen an issue ? Do you think I might be doing something wrong ?

**Comment by coasttech** [comment]
> hmmm, sorry to bother, but seems it's not solved, I have the device, I a running it with zigbee2mqtt edge which seems to be running `/app/node_modules/.pnpm/zigbee-herdsman-converters@23.0.0/` so I believe [Koenkk/zigbee-herdsman-converters#8676](https://github.com/Koenkk/zigbee-herdsman-converters/pull/8676) is included with `const payloadX = reporting.payload("x_axis", 10, constants.repInterval.MINUTE, 1);` for example. Sadly, even deleting then re-adopting the device, I still see null for most of the sensors...
> 
> Should I reopen an issue ? Do you think I might be doing something wrong ?

Same issue here as well.

**Comment by tomburridge** [comment]
I was having this exact issue (xyz, moving and battery sensors all reporting null). Gave up after several repairing attempts, was getting consistent 'failed to configure' errors.

Decided to give ZHA a go, so shut down Z2M, paired there, movement and other sensors started reporting fine. Went back to Z2M for a bit just to begin the process of moving all my other zigbee devices across - and saw the sensors were suddenly reporting xyz and movement properly in Z2M too.

Thought I was perhaps going a bit mad, but repeated the process with four more of the same sensor with the same outcome. Initially pair in Z2M, null sensors, then pair in ZHA, restart Z2M and they work as expected.

Something weird with pairing clearly going on, but hopefully this helps as a workaround for anyone else with this issue.

**Comment by toxic0berliner** [comment]
Hmmm, I was full of hope so I tried, added a new radio to my home assistant set it up with zha paired the device, zha always a pain as usual, finally managed to get it paired but temperature reports none and no other sensor not even door closed/opened... Repair against z2m still same behavior. Are you using a single radio? Cause I never had the same radio and devices work both with zha and z2m...
Seems to me whatever worked for tom doesn't survive a repairing on a new channel or coordinator.

**Comment by tomburridge** [comment]
I used the same radio in ZHA as Z2M, using the 'keep radio settings' when setting up ZHA.

From memory ZHA took a few mins before the sensor was reporting properly, but once it was I was able to shut down ZHA, start up Z2M and the sensor reported fine - no repair needed.

I think you're right that this fix wouldn't survive a repair.

**Comment by thepiecesofme** [comment]
Also having this issue. Aeotec Multisensor is successfully interviewed but the configuration process fails. Oddly, the previous version of the sensor works fine (SmartThings Multisensor) and everything is reported fine.

Like the others, contact & temp is fine but everything else reports “null”. I’ve tried re-interviewing, re-configuring, removing and re-pairing again. Nothing works. I’ve not yet tried the ZHA trick as I don’t currently use both. 

I am running the latest Z2M & HAOS as of today.
