### ISSUE TITLE
TS0001 _TZ3000_jsfzkftc - won't return energy, power, current & voltage

### ISSUE THREAD

**Issue by chanwee77** [Koenkk/zigbee2mqtt#25426]
### What happened?

Buy a new 20A switch with power monitor but it do not show any energy info after paired. It showed TS0001 instead of TS0001_power

Here's the info
Zigbee Model : TS0001
Zigbee Manufacturer : _TZ3000_jsfzkftc
Manufacturer : Tuya

External definition
![image](https://github.com/user-attachments/assets/0f580fb0-ae2c-40f0-9e9a-3d4d137c6a79)

### What did you expect to happen?

I expected it to report Power, Current, Voltage & Energy. I can turn the relay on and off, adjust the switch type and power outage memory. I can even adjust "Settings (specific)" options such as power, current and voltage calibration

### How to reproduce it (minimal and precise)

pair it

### Zigbee2MQTT version

1.42.0-2

### Adapter firmware version

6.10.3.0 build 297

### Adapter

ezsp

### Setup

HA Raspberry Pi 4B

**Comment by Koenkk** [comment]
Fixed!

> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) tomorrow

**Comment by chanwee77** [comment]
updated Zigbee2MQTT to 2.0.0-1 but still having the same issue
![image](https://github.com/user-attachments/assets/214196cf-9d35-497b-b192-3a725fb1aaa2)

**Comment by Koenkk** [comment]
Sorry I did not merge https://github.com/Koenkk/zigbee-herdsman-converters/pull/8556 yet, will do it later today.
