### ISSUE TITLE
Tuya ZY-M100-S_2 illuminance not change

### ISSUE THREAD

**Issue by Diegocampy** [Koenkk/zigbee2mqtt#27005]
### What happened?

After the latest update 2.2.1.1  All 5 of my presence sensors continue to work, but then do not update the lighting value.

### Zigbee2MQTT version

2.2.1

### Adapter firmware version

7.4.4.0

### Adapter

EZSP v13

### Setup

Add-on

**Comment by blackst225** [comment]
Same happend to me on Tuya Presence. They still availiable but no triggers work at all

**Comment by Scialla** [comment]
I've two presence sensors, one at 5.8 GHz and one at 24 GHz. Only 5.8 sensor have same problem with `illuminance`

**Comment by Biero1** [comment]
I have the same problem.
After the update the illumination sensor is frozen. Presence sensor Tuya ZY-M100-S_2, _TZE204_qasjif9e

**Comment by Koenkk** [comment]
Should be fixed in the dev branch.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by timmo65** [comment]
I can confirm this is fixed in the edge version -  I had  3x ZY-M100-S_1s which were always ok and 3x ZY-M100-S_2s with illuminance stuck  on 2.2.1.1 (or unknown when repaired) - back working now - thanks

**Comment by saunus00** [comment]
Zigbee2MQTT version: 2.2.1-1 two ZY-M100-S_2 devices.
on one I have Illuminance 0lx and the other Illuminance 1lx so it still doesn't work.

**Comment by kyrgorsh** [comment]
same problem. However, I have not installed edge version. waiting for release.

**Comment by naevtamarkus** [comment]
I've got the same problem.
Apparently, someone tried the dev branch and didn't work either, see here:
https://github.com/Koenkk/zigbee2mqtt/issues/27062

**Comment by lukaszzyla** [comment]
For me illuminance works on both stable and edge HA addons.
check my problem here - for me, the presense is frozen.
https://github.com/Koenkk/zigbee2mqtt/issues/27212
I did install 2.2.0 in docker as recommended but then presence is always true (frozen in true opposed to frozen in null)
Any idea if this is the same issue?
I only bought this sensor and was wondering if it works as motion sensor at all?

**Comment by naevtamarkus** [comment]
Hi all! Just wanted to say that 2.3.0 fixed it for me. Thanks!

**Comment by gedekai** [comment]
It's true, 2.3.0 fixed it. Everything works fine now!

**Comment by Diegocampy** [comment]
I Confirm, all work fine, now!

**Comment by lukaszzyla** [comment]
I am in the unlucky team then, because for me it is still the same.
The funny thing is that illuminance was always working for me together with distance.
but the presence is either true or none
I have removed and readded the device so many times an many different versions of z2m.
I was hoping that 2.3.0 fixes it for me like for rest of you but unfortunatelly - no difference.
mqtt broker:

![Image](https://github.com/user-attachments/assets/15463c06-4ec8-41d1-a0a8-89fee62ab73e)


z2m:
When I add the device it is being interviewed and reports success.
But then presence is frozen on null or true.
nobody's at home for an hour or so and:

![Image](https://github.com/user-attachments/assets/0a024c9b-bb8b-493d-9e75-ead2e2589604)

![Image](https://github.com/user-attachments/assets/0fc87070-b692-4760-859d-c70028382d07)

![Image](https://github.com/user-attachments/assets/a0d99f2e-2e49-460c-aeca-af1e94ab0536)

![Image](https://github.com/user-attachments/assets/7ee5dcad-380f-44e2-b925-c66e1992d119)

Illuminance levels are far away from my knx sensors that report several thousands lux compared to 2-3 lx from tuya.
Any ideas what to do next?
It never worked for me as I bought it 2 or 3 weeks ago.
Do you think this could be faulty device?
I do not have tuya gateway to check with native app.

**Comment by Bogdis** [comment]
Same sensor here but for me the Presence and range doesn't work or kinda not working. The Presence works sometimes if I set the range to maximim. The range sensor dosen't work at all for me it says unknown.
