### ISSUE TITLE
Invalid value for number (sensitivity)

### ISSUE THREAD

**Issue by markg85** [Koenkk/zigbee2mqtt#27357]
### What happened?

The error that shows in home assistant logging:
```
2025-05-08 15:11:28.183 ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.breath_sensor_presence_sensitivity: 0 (range 1.0 - 10.0)
2025-05-08 15:11:28.183 ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.breath_sensor_move_sensitivity: 0 (range 1.0 - 10.0)
```

It's this sensor / device:
```
z2m: breath_sensor (0xe498bb1945e563e4): ZY-M100-24GV3 - Tuya 24G MmWave radar human presence motion sensor（added distance switch） (Router)
```

This is the faulty payload:
```
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/breath_sensor', payload '{"detection_distance_max":5.25,"detection_distance_min":1.5,"distance":1.2,"find_switch":"ON","illuminance":49,"linkquality":123,"move_sensitivity":0,"presence":true,"presence_sensitivity":0,"presence_timeout":1,"state":"move"}'
```

Given the HA error above, the `move_sensitivity` probably has to be 1.0.
Same for `presence_sensitivity`.

### Zigbee2MQTT version

2.3.0

### Adapter firmware version

Irrelevant

### Adapter

Irrelevant

### Setup

Irrelevant

**Comment by KingAdeCode** [comment]
Having the same issue

<img width="650" alt="Image" src="https://github.com/user-attachments/assets/0ae84e64-9c6f-45de-b796-9c9491b8c187" />

**Comment by KingAdeCode** [comment]
<img width="1522" alt="Image" src="https://github.com/user-attachments/assets/4c3ea41c-3a93-4bdc-b65c-4ce05d86e813" />

**Comment by KingAdeCode** [comment]
The device: https://www.zigbee2mqtt.io/devices/ZY-M100-24GV3.html#tuya-zy-m100-24gv3

**Comment by KingAdeCode** [comment]
I temporarily fixed this by setting all configurations above "0.". Check my configuration here:

<img width="1046" alt="Image" src="https://github.com/user-attachments/assets/a397573c-0291-4f3d-a3c2-266fdf387d33" />

**Comment by sanketgroup** [comment]
But even if we set value to above zero on these sliders, the values go back to 0 after few seconds/minutes.

**Comment by Molier** [comment]
duplicate of #24049 ?

**Comment by Molier** [comment]
I fixed it with this automation you can find in the other issue : https://github.com/Koenkk/zigbee2mqtt/issues/24049#issuecomment-3126377297

**Comment by markg85** [comment]
This issue still persists.

It's not a thing that breaks which is ironically unfortunate else you would have noticed and fixed it.
Just start home assistant and monitor the logs and you'll see this.
