### ISSUE TITLE
[TS011F / _TZ3000_ww6drja5] Girier JR-ZPM01 LED Indicator Mode not working

### ISSUE THREAD

**Issue by Bjk8kds** [Koenkk/zigbee2mqtt#28384]
### What happened?
LED Indicator Mode not working, or no effect on the device.
Is the LED indicator mode not working or commands being ignored?
Is this feature available on the Girier JR-ZPM01?

### What did you expect to happen?
LED Indicator Mode works, or is removed from the configuration if this feature does not exist.

### How to reproduce it (minimal and precise)
Just change the LED Indicator Mode.

### From frontend
```
[2025-08-26 12:04:02] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/ZB Plug Gr', payload '{"child_lock":"UNLOCK","countdown":0,"current":0,"energy":0,"indicator_mode":"off/on","last_seen":"2025-08-26T12:04:02+07:00","linkquality":174,"power":0,"power_outage_memory":"off","state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"voltage":219.8}'
[2025-08-26 12:04:02] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/ZB Plug Gr', payload '{"child_lock":"UNLOCK","countdown":0,"current":0,"energy":0,"indicator_mode":"on/off","last_seen":"2025-08-26T12:04:02+07:00","linkquality":174,"power":0,"power_outage_memory":"off","state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"voltage":219.8}'
[2025-08-26 12:04:05] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/ZB Plug Gr', payload '{"child_lock":"UNLOCK","countdown":0,"current":0,"energy":0,"indicator_mode":"on/off","last_seen":"2025-08-26T12:04:05+07:00","linkquality":174,"power":0,"power_outage_memory":"off","state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"voltage":219.8}'
[2025-08-26 12:04:05] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/ZB Plug Gr', payload '{"child_lock":"UNLOCK","countdown":0,"current":0,"energy":0,"indicator_mode":"on","last_seen":"2025-08-26T12:04:05+07:00","linkquality":174,"power":0,"power_outage_memory":"off","state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"voltage":219.8}'
[2025-08-26 12:04:08] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/ZB Plug Gr', payload '{"child_lock":"UNLOCK","countdown":0,"current":0,"energy":0,"indicator_mode":"on","last_seen":"2025-08-26T12:04:08+07:00","linkquality":178,"power":0,"power_outage_memory":"off","state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"voltage":219.8}'
[2025-08-26 12:04:08] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/ZB Plug Gr', payload '{"child_lock":"UNLOCK","countdown":0,"current":0,"energy":0,"indicator_mode":"off/on","last_seen":"2025-08-26T12:04:08+07:00","linkquality":178,"power":0,"power_outage_memory":"off","state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"voltage":219.8}'
[2025-08-26 12:04:08] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/ZB Plug Gr', payload '{"child_lock":"UNLOCK","countdown":0,"current":0,"energy":0,"indicator_mode":"off/on","last_seen":"2025-08-26T12:04:08+07:00","linkquality":174,"power":0,"power_outage_memory":"off","state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"voltage":219.8}'
```
### From add-on
```
[2025-08-26 12:05:40] debug: 	z2m: Received Zigbee message from 'ZB Plug Gr', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsCurrent":0}' from endpoint 1 with groupID 0
[2025-08-26 12:05:40] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/ZB Plug Gr', payload '{"child_lock":"UNLOCK","countdown":0,"current":0,"energy":0,"indicator_mode":"off/on","last_seen":"2025-08-26T12:05:40+07:00","linkquality":178,"power":0,"power_outage_memory":"off","state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"voltage":219.8}'
[2025-08-26 12:05:42] debug: 	z2m:mqtt: Received MQTT message on 'zigbee2mqtt/0xa4c1381370aa00bf/set' with data '{"indicator_mode":"on"}'
[2025-08-26 12:05:42] debug: 	z2m: Publishing 'set' 'indicator_mode' to 'ZB Plug Gr'
[2025-08-26 12:05:42] debug: 	zh:controller:endpoint: ZCL command 0xa4c1381370aa00bf/1 genOnOff.write({"tuyaBacklightMode":3}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false})
```

### Details
os: `#1 SMP PREEMPT_DYNAMIC Wed Aug 13 08:52:04 UTC 2025 - 6.12.41-haos - x64`
node: `v22.16.0`
zigbee2mqtt: `2.6.0` (`unknown`)
zigbee-herdsman: `5.0.4`
zigbee-herdsman-converters: `24.11.0`
adapter: `ZStack3x0` `{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20250321,"transportrev":2}`
#### Device
software_build_id: `1.0.5`
date_code: `undefined`
endpoints:
```json
{"1":{"bindings":[],"clusters":{"input":["genBasic","genIdentify","genGroups","genScenes","genOnOff","genTime","57344","seMetering","haElectricalMeasurement","touchlink","6280"],"output":["genOta"]},"configured_reportings":[],"scenes":[]}}
```
##### Health
time: `Tue Aug 26 2025 11:47:56 GMT+0700`
process.uptime_sec: `262226`
```json
{"leave_count":0,"messages":160,"messages_per_sec":0.2943,"network_address_changes":0}
```

**Comment by Bjk8kds** [comment]
I think I missed it when searching for similar issues. similar issue #28190

**Comment by Bjk8kds** [comment]
Additionally, found error log:
```
[2025-08-26 14:26:39] error: 	z2m: Failed to configure 'ZB Plug Gr', attempt 1 (Error: ZCL command 0xa4c1381370aa00bf/1 haElectricalMeasurement.configReport([{"attribute":"activePower","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":10}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Status 'INVALID_DATA_TYPE')
    at Endpoint.checkStatus (/app/node_modules/.pnpm/zigbee-herdsman@5.0.4/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:372:28)
    at Endpoint.zclCommand (/app/node_modules/.pnpm/zigbee-herdsman@5.0.4/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:1005:26)
    at Endpoint.configureReporting (/app/node_modules/.pnpm/zigbee-herdsman@5.0.4/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:727:9)
    at Object.activePower (/app/node_modules/.pnpm/zigbee-herdsman-converters@24.11.0/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:205:5)
    at configure (/app/node_modules/.pnpm/zigbee-herdsman-converters@24.11.0/node_modules/zigbee-herdsman-converters/src/devices/tuya.ts:6837:17)
    at Object.configure (/app/node_modules/.pnpm/zigbee-herdsman-converters@24.11.0/node_modules/zigbee-herdsman-converters/src/index.ts:363:21)
    at Configure.configure (/app/lib/extension/configure.ts:123:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:252:17))
[2025-08-26 14:26:52] error: 	z2m: Failed to configure 'ZB Plug Gr', attempt 2 (Error: ZCL command 0xa4c1381370aa00bf/1 haElectricalMeasurement.configReport([{"attribute":"activePower","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":10}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Status 'INVALID_DATA_TYPE')
    at Endpoint.checkStatus (/app/node_modules/.pnpm/zigbee-herdsman@5.0.4/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:372:28)
    at Endpoint.zclCommand (/app/node_modules/.pnpm/zigbee-herdsman@5.0.4/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:1005:26)
    at Endpoint.configureReporting (/app/node_modules/.pnpm/zigbee-herdsman@5.0.4/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:727:9)
    at Object.activePower (/app/node_modules/.pnpm/zigbee-herdsman-converters@24.11.0/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:205:5)
    at configure (/app/node_modules/.pnpm/zigbee-herdsman-converters@24.11.0/node_modules/zigbee-herdsman-converters/src/devices/tuya.ts:6837:17)
    at Object.configure (/app/node_modules/.pnpm/zigbee-herdsman-converters@24.11.0/node_modules/zigbee-herdsman-converters/src/index.ts:363:21)
    at Configure.configure (/app/lib/extension/configure.ts:123:13)
    at Immediate.<anonymous> (/app/lib/extension/configure.ts:66:17))
```

**Comment by mrmaximas** [comment]
The best way to fix the problem is to connect the device to the native Tuya hub and sniff the traffic.

**Comment by Bjk8kds** [comment]
> The best way to fix the problem is to connect the device to the native Tuya hub and sniff the traffic.

@mrmaximas Sorry, but this Girier is not compatible with Tuya hub/app, I have tried it and it was rejected, it is even written in the product description.
![Screenshot_2025-08-31-09-51-56-469-edit_com.alibaba.aliexpresshd.jpg](https://github.com/user-attachments/assets/04382836-961a-41c1-be77-720c94346db5)

**Comment by git-greatguy** [comment]
Hello,
Same here, just got 2 of these from china !

Led indicators are always on (purple ?, red and blue ?) and z2m controls has no effect on that.

I also have bad "current" values too. 32A for 3W ? as an electrician, i cant approve that math.

<img width="247" height="585" alt="Image" src="https://github.com/user-attachments/assets/11cde2d1-0516-4cbc-803f-e5f8d641bb06" />

<img width="976" height="985" alt="Image" src="https://github.com/user-attachments/assets/5c681b1b-262b-4935-b3ef-736974fee212" />

**Comment by Bjk8kds** [comment]
> I also have bad "current" values too. 32A for 3W ? as an electrician, i cant approve that math.

This issue is due to a code error/failure. https://github.com/Koenkk/zigbee2mqtt/issues/28198
It will be fixed in a future release.

**Comment by andrei-lazarov** [comment]
This may be a stupid answer.. Did you try rebooting the device? 
On my switch modules, the indicator mode setting only applies after a power-cycle.

**Comment by Bjk8kds** [comment]
> This may be a stupid answer.. Did you try rebooting the device? 
> On my switch modules, the indicator mode setting only applies after a power-cycle.

Yep. Didn't work for my device.

**Comment by Bjk8kds** [comment]
I'm curious. Has anyone connected the device to Sonoff Zigbee gateway/hub and eWeLink app? Does the mode indicator feature work or not?

**Comment by Suxsem** [comment]
Same issue. I don't have the original hub to check if the feature is available or not

**Comment by Bjk8kds** [comment]
> This may be a stupid answer.. Did you try rebooting the device? On my switch modules, the indicator mode setting only applies after a power-cycle.

@andrei-lazarov 
Just to clarify, is your device `_TZ3000_ww6drja5`? can you provide a screenshot?

**Comment by andrei-lazarov** [comment]
> is your device `_TZ3000_ww6drja5`? 

No.. I just said what I noticed on 'switch modules', like the [AVATTO ZWSM16](https://www.zigbee2mqtt.io/devices/ZWSM16-1-Zigbee.html).

**Comment by Bjk8kds** [comment]
> > is your device `_TZ3000_ww6drja5`? 
> 
> No.. I just said what I noticed on 'switch modules', like the [AVATTO ZWSM16](https://www.zigbee2mqtt.io/devices/ZWSM16-1-Zigbee.html).

Ok, thanks.
I think specifically this device doesn't have controllable indicator that can be controlled via zigbee. Maybe hardwired or something like that.

**Comment by Bjk8kds** [comment]
It should be fixed in PR
https://github.com/Koenkk/zigbee-herdsman-converters/pull/10417

**Comment by NestorRV** [comment]
@Bjk8kds - The PR you linked says that it was released in `zigbee-herdsman-converters`'s version 25.50.0 but I do have 25.59.0 and I'm still seeing this issue (see all the versions in attached image). Am I missing anything?

![image](https://github.com/user-attachments/assets/c29d3cf9-1b1e-4f3b-b3db-abf11b1f1ff2)

**Comment by andrei-lazarov** [comment]
@NestorRV In this case, 'issue fixed' meant 'useless option removed'.
See the title of the PR

**Comment by NestorRV** [comment]
> @NestorRV In this case, 'issue fixed' meant 'useless option removed'.
> See the title of the PR

@andrei-lazarov yeah, but I do still see the options in the z2m settings page for the device. That's why I asked!

**Comment by andrei-lazarov** [comment]
Right, I see this PR is wrong:
`indicatorMode: (manufacturerName) => manufacturerName === "_TZ3000_ww6drja5",`

But it's fixed in the latest converters:
`indicatorMode: (manufacturerName) => manufacturerName !== "_TZ3000_ww6drja5",`

So you should no longer see the option in the next release (Z2M 2.6.4 - December 1st) 🙂

**Comment by NestorRV** [comment]
> Right, I see this PR is wrong:
> `indicatorMode: (manufacturerName) => manufacturerName === "_TZ3000_ww6drja5",`
> 
> But it's fixed in the latest converters:
> `indicatorMode: (manufacturerName) => manufacturerName !== "_TZ3000_ww6drja5",`
> 
> So you should no longer see the option in the next release (Z2M 2.6.4 - December 1st) 🙂 

Do you have a link to the correct PR? Thanks! @andrei-lazarov

**Comment by andrei-lazarov** [comment]
It's this commit: https://github.com/Koenkk/zigbee-herdsman-converters/commit/1a02ba1da2122279c901d7d286b5e50438bf1327
Fixing this issue: https://github.com/Koenkk/zigbee2mqtt/issues/29447 (caused by this PR)

**Comment by NestorRV** [comment]
> It's this commit: https://github.com/Koenkk/zigbee-herdsman-converters/commit/1a02ba1da2122279c901d7d286b5e50438bf1327
> Fixing this issue: https://github.com/Koenkk/zigbee2mqtt/issues/29447 (caused by this PR)

Cool, thanks! I'll keep an eye on 1st Dec release to see what we get! @andrei-lazarov

**Comment by Bjk8kds** [comment]
@NestorRV 
As @andrei-lazarov said above, I'll just add.
This issue should have been fixed by https://github.com/Koenkk/zigbee-herdsman-converters/pull/10417, but Koenkk's commit
(comment) https://github.com/Koenkk/zigbee-herdsman-converters/pull/10417#issuecomment-3419877918
(commit) https://github.com/Koenkk/zigbee-herdsman-converters/commit/f7d3deb621f35510640a3b24da337433c2719bcc seems to have backwards logic, and instead removes the `IndicatorMode` on other devices.
It was fixed by commit https://github.com/Koenkk/zigbee-herdsman-converters/commit/044f76c9fea978fe0bac4c32cc8a3b4c39d5a73a this month.
You can also see the comments in this 2.6.3 release. https://github.com/Koenkk/zigbee2mqtt/discussions/29397#discussioncomment-14869805

**Comment by NestorRV** [comment]
> @NestorRV 
> As @andrei-lazarov said above, I'll just add.
> This issue should have been fixed by https://github.com/Koenkk/zigbee-herdsman-converters/pull/10417, but Koenkk's commit
> (comment) https://github.com/Koenkk/zigbee-herdsman-converters/pull/10417#issuecomment-3419877918
> (commit) https://github.com/Koenkk/zigbee-herdsman-converters/commit/f7d3deb621f35510640a3b24da337433c2719bcc seems to have backwards logic, and instead removes the `IndicatorMode` on other devices.
> It was fixed by commit https://github.com/Koenkk/zigbee-herdsman-converters/commit/044f76c9fea978fe0bac4c32cc8a3b4c39d5a73a this month.
> You can also see the comments in this 2.6.3 release. https://github.com/Koenkk/zigbee2mqtt/discussions/29397#discussioncomment-14869805

So just to confirm: the 1st of December release will fix the issue (rather than delete the option to control the leds) so we will be able to control the led behaviour on this type of plugs? @Bjk8kds

**Comment by Bjk8kds** [comment]
> So just to confirm: the 1st of December release will fix the issue (rather than delete the option to control the leds) so we will be able to control the led behaviour on this type of plugs? [@Bjk8kds](https://github.com/Bjk8kds)

Sorry, I think I misspoke. But the device `JR-ZPM01 (_TZ3000_ww6drja5)` itself doesn't have controllable indicator, so this PR https://github.com/Koenkk/zigbee-herdsman-converters/pull/10417 removes that option.
