### ISSUE TITLE
[TS0601/_TZE204_rtrmfadk] TRV801 detected as TRV601

### ISSUE THREAD

**Issue by SH1FT-W** [Koenkk/zigbee2mqtt#28458]
### What happened?
My thermostat **Tuya TRV801** (see [TRV801 docs](https://www.zigbee2mqtt.io/devices/TRV801.html)) is incorrectly detected as **TRV601**.  
Because of this, Zigbee2MQTT shows the wrong model name and icon.

### What did you expect to happen?
The device should be detected and exposed as **TRV801**, not TRV601.

### How to reproduce it (minimal and precise)
- Pair a Tuya TRV801 with Zigbee2MQTT (version 2.6.1).
- After interview, device shows up as `TRV601`.

### Debug logs
*(see below for `exposes` and interview details)*

### Device details
os: `#1 SMP PREEMPT Wed Aug 13 08:59:29 UTC 2025 - 6.12.34-haos-raspi - arm64`  
node: `v22.16.0`  
zigbee2mqtt: `2.6.1` (`unknown`)  
zigbee-herdsman: `6.0.4`  
zigbee-herdsman-converters: `25.14.0`  
adapter: `EmberZNet` `{"build":0,"ezsp":13,"major":7,"minor":4,"patch":4,"revision":"7.4.4 [GA]","special":1,"type":170}`

#### Device
IEEE: `0xa4c13888b98c28bb`  
software_build_id: `undefined`  
date_code: ``

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by SH1FT-W** [comment]
Thanks a lot! 🙏 I just tried the dev branch and it’s working, but the device picture is still not loading from the database – I only see the Zigbee logo instead.

**Comment by Koenkk** [comment]
Added the picture!
