### ISSUE TITLE
Lot of errors from Tuya PJ-1203A

### ISSUE THREAD

**Issue by syntesys87** [Koenkk/zigbee2mqtt#28455]
### What happened?

From last update, I notice a lot of errors from Tuya PJ-1203A:

### Zigbee2MQTT version

2.6.1

### Adapter firmware version

8.0.2

### Adapter

Sonoff ZBDongle-E (ZigBee 3.0 USB Dongle Plus) – v2

### Setup

Z2M on Raspberry PI 5 16GB, HAOS

### Debug log

[log.log](https://github.com/user-attachments/files/22097128/log.log)

  '0xa4c138d8100e1a0a':
    friendly_name: Consumo Clima Induzione
    signed_power_b: true
    signed_power_a: true
    ac_frequency_calibration: 1
    homeassistant: {}
    optimistic: true
    qos: 0
  '0xa4c13854bfbb1f58':
    friendly_name: Consumo Casa Fotovoltaico
    ac_frequency_calibration: 1
    homeassistant: {}
    optimistic: true
    qos: 0
  '0xa4c138554cc92b21':
    friendly_name: Consumo Forno Microonde
    signed_power_a: true
    signed_power_b: true
    ac_frequency_calibration: 1
    homeassistant: {}
    optimistic: true
    qos: 0
  '0xa4c13831d78ec9a7':
    friendly_name: Consumo Frigo Cantina
    signed_power_a: true
    signed_power_b: true
    ac_frequency_calibration: 1
    homeassistant: {}
    optimistic: true
    qos: 0  
'0xa4c1389bf2e86240':
    friendly_name: Consumo UPS
    ac_frequency_calibration: 1
    homeassistant: {}
    optimistic: true
    qos: 0

**Comment by mnmarc** [comment]
I‘ve got also errors. Since updating Zigbee2MQTT Add-on from v2.6.0-1 to v2.6.1-1 on Home Assistant OS,
my PJ-1203A (`_TZE204_81yrt3lo`, 0xa4c138c6e459e106) started showing continuous time sync errors:

zhc:tuya: Failed to sync time with ‘0xa4c138c6e459e106’
(Error: ZCL command manuSpecificTuya.mcuSyncTime failed (Delivery failed for ‘42769’.))

With v2.6.0-1 this did not happen.  

Not sure if this is expected behavior after the recent timestamp improvements –  
but maybe the PJ-1203A does not support `mcuSyncTime` correctly?

Environment:
- Home Assistant OS (latest)
- Zigbee2MQTT Add-on v2.6.1-1
- Sonoff Dongle-E (latest)

**Comment by Koenkk** [comment]
Could you provide the debug log of this?

See [this](https://www.zigbee2mqtt.io/guide/configuration/logging.html) on how to enable debug logging.

**Comment by PeetersJan** [comment]
Same issue here.  I will post a log tonight.
Message for every PJ-1203A device in my ecosystem.
I can confirm the timestamp is indeed off with my local time, by minus two hours from CET

Same setup:
Home Assistant OS (latest)
Zigbee2MQTT Add-on v2.6.1-1
Sonoff Dongle-E (latest)

<img width="779" height="804" alt="Image" src="https://github.com/user-attachments/assets/ec32242c-abde-49d8-960c-973627a5bc77" />

**Comment by pticavorobey** [comment]
Messages keep coming in:

`"level":"error","message":"zhc:tuya: Failed to sync time with`

TS0601 (_TZE200_e9ba97vf)
TS0601 (_TZE284_81yrt3lo)

Zigbee2MQTT Add-on v2.6.1-1

**Comment by teslut** [comment]
Hello
I have exactly the same issues since the last update.
Perhaps it helps.
Thanks a lot for this great work.

**Comment by mnmarc** [comment]
this is the cleaned log, hope it will help….if you need more lines, let me know.

[2025-09-03 17:41:35] debug: zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=3 frmNum=2] Added to rxQueue
[2025-09-03 17:41:35] debug: zh:ember:ezsp: <=== [CBFRAME: ID=69:"INCOMING_MESSAGE_HANDLER" Seq=50 Len=46]
[2025-09-03 17:41:35] debug: zh:ember:ezsp: ezspIncomingMessageHandler: type=UNICAST apsFrame={"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1} messageContents=09bb02004c6604000100
[2025-09-03 17:41:35] debug: z2m: Received Zigbee message from 'Solar2', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"dp":102,"datatype":4,"data":{"type":"Buffer","data":[0]}}],"seq":19456}' from endpoint 1
[2025-09-03 17:41:35] debug: zh:ember:ezsp: <=== [CBFRAME: ID=63:"MESSAGE_SENT_HANDLER" Seq=50 Len=26]
[2025-09-03 17:41:35] debug: zh:ember:ezsp: ezspMessageSentHandler: status=ZIGBEE_DELIVERY_FAILED type=DIRECT indexOrDestination=42769
[2025-09-03 17:41:35] error: zhc:tuya: Failed to sync time with '0xAABBCCDDEEFF0011' (Error: ZCL command failed (Delivery failed for '42769'))

**Comment by Koenkk** [comment]
Fixed!

> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by teslut** [comment]
Dear Koenkk

I have switched to the Dev version but I still have this error with many Tuya devices.
like with the [PJ-1203A](https://www.zigbee2mqtt.io/devices/PJ-1203A.html#tuya-pj-1203a)

zhc:tuya: Failed respond to version response '0xa4c138e35d3f1407' (Error: ZCL command 0xa4c138e35d3f1407/1 manuSpecificTuya.mcuVersionRequest({"seq":2}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":29070,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":169},"zclSequence":141,"commandIdentifier":11} timed out after 10000ms))
Or for this device
https://www.zigbee2mqtt.io/devices/ME201WZ.html#tuya-me201wz

Should I do another update ?

Thanks for all your great work.
Have a nice day

**Comment by Koenkk** [comment]
Also fixed that one.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by JNow01** [comment]
Hello,
I'm sorry but I also still get loads of "mcuSyncTime" errors with the Dev version and 3 out of 5 [Cafago valves](https://www.zigbee2mqtt.io/devices/TS0601_thermostat_4.html#tuya-ts0601_thermostat_4) :
```
[2025-09-06 16:41:18] error: 	zhc:tuya: Failed to sync time with '0xa4c1380b4e2269c9' (Error: ZCL command 0xa4c1380b4e2269c9/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[104,188,72,8,104,188,100,40]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Delivery failed for '3401'.))
[2025-09-06 16:41:21] error: 	zhc:tuya: Failed to sync time with '0xa4c138b442aa4702' (Error: ZCL command 0xa4c138b442aa4702/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[104,188,72,12,104,188,100,44]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Delivery failed for '33556'.))
[2025-09-06 16:41:25] error: 	zhc:tuya: Failed to sync time with '0xa4c1382913b655dd' (Error: ZCL command 0xa4c1382913b655dd/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[104,188,72,17,104,188,100,49]},
```

I would be very grateful if you could bring the fix to those devices.
I can provide further logs if needed.
All big thumbs up for your great work @Koenkk !
J.

**Comment by Koenkk** [comment]
Let's continue in https://github.com/Koenkk/zigbee2mqtt/issues/28486

**Comment by PeetersJan** [comment]
Same here, since a few days, and for every PJ-1203A device, the error changed to the below.
I am currently on Operating system version 16.1 and will now update for 16.2.

zhc:tuya: Failed respond to version response '0xa4cxxxxxeb637b2c' (Error: ZCL command 0xa4cxxxxxeb637b2c/1 manuSpecificTuya.mcuVersionRequest({"seq":2}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":49055,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":43},"zclSequence":200,"commandIdentifier":11} timed out after 10000ms))

<img width="325" height="330" alt="Image" src="https://github.com/user-attachments/assets/f6cc68e3-d788-49b8-a56c-463e5a86f36e" />

**Comment by PeetersJan** [comment]
After update to firmware 16.2: no cigar.
The "failed to sync time" error is back :

zhc:tuya: Failed to sync time with '0xa4cxxxxx85edf3e' (Error: ZCL command 0xaxxxxx2585edf3e/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[48,83,40,103,48,83,68,135]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":1535,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":162},"zclSequence":31,"commandIdentifier":11} timed out after 10000ms))

<img width="326" height="352" alt="Image" src="https://github.com/user-attachments/assets/78682667-213c-4784-98c5-389085727278" />

**edit** The update seems to work, at least to some extend.  The "Failed respond to version" is gone.  However, the "Failed to sync time" is back but less often than before.  Only once per minute on average where it used to be flooding my screen.

**Comment by Koenkk** [comment]
@PeetersJan are you on the latest dev branch?

> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by PeetersJan** [comment]
My bad !
Now I am and everything is peach!

<img width="662" height="104" alt="Image" src="https://github.com/user-attachments/assets/39c8f94f-b519-46b5-91a9-c8f274c5736e" />

**Comment by true9741** [comment]
since moving to version [2.6.1] commit: [e9889e5d20e8911550d5231bc0349567cc2bb9ce] I am having failed to sync time in the Device type: TS0601 Zigbee Manufacturer: _TZE204_mrffaamu

<img width="2516" height="839" alt="Image" src="https://github.com/user-attachments/assets/70d7b898-ee6e-4141-acda-25c661b0c925" />

I have taken the following debug information of one of my devices:

[2025-09-15 12:12:20] debug:    zh:controller:endpoint: Error: ZCL command 0x943469fffe12cf51/1 manuSpecificTuya.dataQuery({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Timeout - 11543 - 1 - 228 - 61184>
    at Object.start (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/utils/waitress.ts:68:23)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:659:47)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:691:28)
    at /app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:439:20
    at Queue.execute (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20)
    at ZStackAdapter.sendZclFrameToEndpoint (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:437:16)
    at Request.send (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:86:25)
    at Endpoint.sendRequest (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:358:20)
    at Endpoint.zclCommand (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:1048:28)
    at Endpoint.command (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:811:23)
[2025-09-15 12:12:20] error:    zhc:tuya: Failed to query '0x943469fffe12cf51' on interval (Error: ZCL command 0x943469fffe12cf51/1 manuSpecificTuya.dataQuery({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) faile>

Thanks for your help.

**Comment by tonioni** [comment]
Previously quickly mentioned ME201WZ still causes mcuVersionRequest errors in dev version (and makes whole network almost unusable), adding "respondToMcuVersionResponse: false" to tuya.js ME201WZ section fixes it.

0xa4c13899aed50edf = ME201WZ (_TZE284_kyyu8rbj)

data/log/2025-09-24.09-59-18/log.log:[2025-09-24 10:00:19] error:       zhc:tuya: Failed respond to version response '0xa4c13899aed50edf' (Error: ZCL command 0xa4c13899aed50edf/1 manuSpecificTuya.mcuVersionRequest({"seq":2}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":22206,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":192},"zclSequence":77,"commandIdentifier":11} timed out after 10000ms))

**Comment by Koenkk** [comment]
@tonioni disabled it for the _TZE284_kyyu8rbj

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by pompilir** [comment]
I get this error with a tuya thermostat TS0601 _TZE204_xnbkhhdr (Wall thermostat)

`[2025-12-02 20:37:59] error:    zhc:tuya: Failed respond to version response '0xa4c138ccff178d6c' (Error: ZCL command 0xa4c138ccff178d6c/1 manuSpecificTuya.mcuVersionRequest({"seq":2}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":43593,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":228},"zclSequence":37,"commandIdentifier":11} timed out after 10000ms))
`
My log is full of these warnings and I get z2m restart 1-2 times per day. I'm using z2m 2.6.3

**Comment by Koenkk** [comment]
@pompilir fixed!

> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by pompilir** [comment]
> [@pompilir](https://github.com/pompilir) fixed!
> 
> > Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

Thanks a lot for your support!

**Comment by pompilir** [comment]
Hi,
I'm still having this error with the Wall thermostat (ZWT198/ZWT100-BH). It happens less often then before the patch but it's still there. Here the log file

> [2026-03-03 10:29:20] error: 	zhc:tuya: Failed to sync time with '0xa4c138ccff178d6c' (Error: ZCL command 0xa4c138ccff178d6c/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[105,166,169,231,105,166,183,247]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":15762,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":109},"zclSequence":77,"commandIdentifier":11} timed out after 10000ms))
[2026-03-03 10:29:31] error: 	zhc:tuya: Failed to sync time with '0xa4c138ccff178d6c' (Error: ZCL command 0xa4c138ccff178d6c/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[105,166,169,241,105,166,184,1]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":15762,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":115},"zclSequence":79,"commandIdentifier":11} timed out after 10000ms))

Thanks in advance for your support!
