### ISSUE TITLE
Failed to sync time manuSpecificTuya.mcuSyncTime

### ISSUE THREAD

**Issue by u15jtau** [Koenkk/zigbee2mqtt#28486]
### What happened?

I'm experiencing frequent time sync issues in Zigbee2MQTT when using the SLZB-MR4 (EFR32MG26) adapter with firmware version 20240602. These messages appear in the Zigbee2MQTT log continuously to the point I'm getting multiple per second.

Environment
Zigbee2MQTT version: 2.6.1
Node.js version: 18.20.8
npm version: 10.8.2
OS: Ubuntu 24.04.3 LTS (noble)
Running in: Proxmox VM (Ubuntu guest)
MQTT broker: [insert broker name/version]
Zigbee adapter: SLZB-MR4
Chipset: EFR32MG26
Adapter firmware: 20240602
Adapter type (Z2M config): ember

Coordinator Info
Coordinator type: ember
Firmware version: 20240602
Network state: Running
Zigbee2MQTT DB: Clean/fresh install (no previous devices or database)
Adapter connected via ethernet.

Zigbee Network
Total devices: 59
Repeater devices: 50+
Signal strength (LQI): Most devices have LQI ≥ 120
Network health: Stable, no routing issues, no pairing loss
Given the high repeater count and strong LQI across the network, this appears not to be caused by network instability or interference.

Problem Behavior
Time sync errors appear in logs every few minutes
No device dropouts or visible loss of communication
No pairing loss
Issue started immediately on clean install
Survives reboots, adapter reconnects, and restarts

zhc:tuya: Failed to sync time with '0xa4c138ad92360951' (Error: ZCL command 0xa4c138ad92360951/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[48,75,178,196,48,76,63,100]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Delivery failed for '36257'.))

What I’ve Tried
Clean install of Ubuntu 24.04.3 LTS
Clean install of Zigbee2MQTT 2.6.1
Flashed latest firmware (20240602) to SLZB-MR4
Downgraded Node.js from v22 to v18 LTS
Reinstalled dependencies via npm ci
Enabled debug logging
Restarted Zigbee2MQTT and VM

Let me know what else you need and I'd be happy to provide the relevant information.

The main device I have is https://www.zigbee2mqtt.io/devices/ZMS-206US-4.html#zemismart-zms-206us-4

### What did you expect to happen?

I expect that the message is not shown and the time is synced.  

### How to reproduce it (minimal and precise)

This started from the moment I added the first device.

### Zigbee2MQTT version

2.6.1

### Adapter firmware version

20240602

### Adapter

SLZB-MR4

### Setup

Intel NUC with proxmox on an unbuntu server.

### Device `database.db` entry

{"id":16,"type":"Router","ieeeAddr":"0xa4c138e18df4b70e","nwkAddr":32042,"manufId":4417,"manufName":"_TZE204_wwaeqnrf","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"~K0i~K0iK0iK0iK0i�K0i�K0i�K0i","65506":56,"65508":0,"65534":0,"modelId":"TS0601","manufacturerName":"_TZE204_wwaeqnrf","powerSource":1,"zclVersion":3,"dateCode":"","appVersion":74}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"dateCode":"","zclVersion":3,"interviewCompleted":true,"interviewState":"SUCCESSFUL","meta":{"configured":332242049},"lastSeen":1756951491547}

**Comment by Koenkk** [comment]
Could you provide the debug log of this?

See [this](https://www.zigbee2mqtt.io/guide/configuration/logging.html) on how to enable debug logging.

**Comment by enigmaspb** [comment]
Same spam error in log - device Moes BHT-002

[2025-09-05 02:24:27] error:    zhc:tuya: Failed to sync time with '0xb0c7defffec56b9f' (Error: ZCL command 0xb0c7defffec56b9f/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[104,186,31,54,104,186,73,102]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Timeout - 9736 - 1 - 11 - 61184 - 11 after 10000ms))

**Comment by Koenkk** [comment]
Please provide the complete debug log (I need more than just the error)

See [this](https://www.zigbee2mqtt.io/guide/configuration/logging.html) on how to enable debug logging.

**Comment by elalitarek** [comment]
Have the same error, consumed 35 gigs free space and that's how i notifed it : 

[2025-09-05 22:36:57] debug: 	zh:ember: ~~~> [ZCL to=0xa4c1385a2f02a562:51430 apsFrame={"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":0} header={"frameControl":{"reservedBits":0,"frameType":1,"direction":0,"disableDefaultResponse":false,"manufacturerSpecific":false},"transactionSequenceNumber":240,"commandIdentifier":36}]

[2025-09-05 22:36:57] debug: 	zh:ember:ezsp: ===> [FRAME: ID=52:"SEND_UNICAST" Seq=179 Len=34]

[2025-09-05 22:36:57] debug: 	zh:ember:uart:ash: ---> [FRAME type=DATA frmTx=3 frmRx=5](ackRx=3)

[2025-09-05 22:36:57] debug: 	zh:controller:endpoint: Error: ZCL command 0xa4c1385a2f02a562/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[48,78,6,92,48,78,34,124]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":51430,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":185},"zclSequence":239,"commandIdentifier":11} timed out after 10000ms)

    at Object.start (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/adapter/ember/adapter/oneWaitress.ts:196:23)

    at EmberOneWaitress.startWaitingFor (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/adapter/ember/adapter/oneWaitress.ts:220:50)

    at /app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:2035:55

    at processTicksAndRejections (node:internal/process/task_queues:105:5)

    at runNextTicks (node:internal/process/task_queues:69:3)

    at processImmediate (node:internal/timers:453:9)

    at Queue.execute (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20)

    at EmberAdapter.sendZclFrameToEndpoint (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1971:16)

    at Request.send (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:86:25)

    at Endpoint.sendRequest (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:358:20)

[2025-09-05 22:36:57] error: 	zhc:tuya: Failed to sync time with '0xa4c1385a2f02a562' (Error: ZCL command 0xa4c1385a2f02a562/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[48,78,6,92,48,78,34,124]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":51430,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":185},"zclSequence":239,"commandIdentifier":11} timed out after 10000ms))

**Comment by u15jtau** [comment]
Hi
Log file attached.

[log.log](https://github.com/user-attachments/files/22182343/log.log)

**Comment by Koenkk** [comment]
Fixed it!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by JNow01** [comment]
Hi,
Still getting mcuSyncTime errors this morning with the latest dev release for [these devices](https://www.zigbee2mqtt.io/devices/TS0601_thermostat_4.html#tuya-ts0601_thermostat_4) :

`[2025-09-07 10:08:42] error: 	zhc:tuya: Failed to sync time with '0xa4c1382913b655dd' (Error: ZCL command 0xa4c1382913b655dd/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[104,189,61,129,104,189,89,161]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":54031,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":104},"zclSequence":150,"commandIdentifier":11} timed out after 10000ms))
[2025-09-07 10:08:55] error: 	zhc:tuya: Failed to sync time with '0xa4c138b442aa4702' (Error: ZCL command 0xa4c138b442aa4702/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[104,189,61,141,104,189,89,173]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":33556,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":143},"zclSequence":155,"commandIdentifier":11} timed out after 10000ms))
[2025-09-07 10:08:57] error: 	zhc:tuya: Failed to sync time with '0xa4c138b7789bcd97' (Error: ZCL command 0xa4c138b7789bcd97/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[104,189,61,143,104,189,89,175]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":9956,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":162},"zclSequence":157,"commandIdentifier":11} timed out after 10000ms))`

Perhaps they were not targeted by the fix ?
Have a nice day !

**Comment by Koenkk** [comment]
@JNow01 

- could you provide the debug log of this?
- I'm afraid I cannot disable the time sync of this device, otherwise the device wouldn't have the time which is required for the schedule.

**Comment by teslut** [comment]
Hello, I still have the problem, with the latest dev branch version.

Have a nice day

**Comment by peletonduwer** [comment]
The same problem here, continuous error messages from Tuya devices in Zigb2mqtt. So much that my entire ZigBee network is disrupted.

**Comment by Koenkk** [comment]
With what device?

**Comment by peletonduwer** [comment]
> With what device?

Hi, 

It's the Tuya PJ-1203A (zigbee smart energy meter). I have 2 of these devices and both have the same problem. The 0xa4c.....f42c and 0xa4c....f959 (both PJ-1203A devices)

[2025-09-16 23:32:00] error: 	zhc:tuya: Failed to sync time with '0xa4c138c35092f42c' (Error: ZCL command 0xa4c138c35092f42c/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[48,92,147,189,48,92,175,221]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Delivery failed for '7997'.))
[2025-09-16 23:32:04] error: 	zhc:tuya: Failed to sync time with '0xa4c138c35092f42c' (Error: ZCL command 0xa4c138c35092f42c/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[48,92,147,189,48,92,175,221]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Delivery failed for '7997'.))
[2025-09-16 23:32:06] error: 	zhc:tuya: Failed respond to version response '0xa4c1385bd8d4f959' (Error: ZCL command 0xa4c1385bd8d4f959/1 manuSpecificTuya.mcuVersionRequest({"seq":2}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":25050,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":132},"zclSequence":79,"commandIdentifier":11} t

**Comment by ansantos** [comment]
I have this same error with this device: https://www.zigbee2mqtt.io/devices/PJ-1203A.html#tuya-pj-1203a

HAOS 16.2 running on RPi 4.
Zigbee2MQTT 2.6.1-1
Sonoff Zigbee dongle - E with Ember 7.4.5.0

zhc:tuya: Failed respond to version response '0xa4c1384e31082f59' (Error: ZCL command 0xa4c1384e31082f59/1 manuSpecificTuya.mcuVersionRequest({"seq":2}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":29572,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":179},"zclSequence":133,"commandIdentifier":11} timed out after 10000ms))

**Comment by reflectivecode** [comment]
My environment:
```
Zigbee2MQTT version 2.6.1 (dockerized)
Coordinator type ZStack3x0
Coordinator revision  20250321
Total devices: 61
```

I have three of these energy monitors.
```
Zigbee Model TS0601
Zigbee Manufacturer _TZE204_81yrt3lo
Manufacturer Tuya
Model PJ-1203A
```

All throwing that error:
```
error: zhc:tuya: Failed to sync time with '0xa4c138077008e020' (Error: ZCL
command 0xa4c138077008e020/1
manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[48,93,179,137,48,93,109,57]},
{"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false})
failed (Timeout - 9362 - 1 - 180 - 61184 - 11 after 10000ms))
```

```
error: zhc:tuya: Failed to sync time with '0xa4c138e25103c300' (Error: ZCL
command 0xa4c138e25103c300/1
manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[48,93,150,35,48,93,79,211]},
{"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false})
failed (Timeout - 6457 - 1 - 155 - 61184 - 11 after 10000ms))
```

```
error: zhc:tuya: Failed to sync time with '0xa4c138c66988ddf0' (Error: ZCL
command 0xa4c138c66988ddf0/1
manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[48,93,146,205,48,93,76,125]},
{"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false})
failed (Timeout - 8570 - 1 - 105 - 61184 - 11 after 10000ms))
```

**Comment by Koenkk** [comment]
For `PJ-1203A` it's fixed on the dev branch.

> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by bedouinvert** [comment]
Hello,
Same thing here with _TZE204_ltwbm23f
@Koenkk Do you know how to enable time Sync in external converter ?
Since 2.6.1 andreypuhovsky_sstefanowski_mod--TZE204_ltwbm23f-beta6.js converter is invalid caused by onEvent: tuya.onEvent is not a function which seems related to device network Sync !

**Comment by Koenkk** [comment]
Time sync is enabled out of the box, no external converter needed.

**Comment by bedouinvert** [comment]
> Time sync is enabled out of the box, no external converter needed.

So, if i disable tuya.onEvent line in the external extendeur, time Sync will work for my TRV ?

**Comment by Koenkk** [comment]
For `_TZE204_ltwbm23f` you can remove the external converter since it's supported out of the box in z2m 2.6.2 (including time sync)

**Comment by mdpatryk** [comment]
Hello, i have the same problem with Moes SFL02-Z-1 - (_TZE200_stvgmdjz), SFL02-Z-2 - (_TZE200_uenof8jd), SFL02-Z-3 - (_TZE200_zo0cfekv), and I think SFL02-Z-4, too but I don't have device, and I don't know its fingerprint. I have about 40 devices 1, 2, 3- gang, and its spamming a lot of errors every one minute 

`[15.10.2025, 22:40:21] zhc:tuya: Failed to sync time with '0xa4c13828242e9986' (Error: ZCL command 0xa4c13828242e9986/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[48,130,195,43,48,130,223,75]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":335,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":113},"zclSequence":222,"commandIdentifier":11} timed out after 10000ms))
[15.10.2025, 22:40:27] zhc:tuya: Failed to sync time with '0xa4c138a3c862a7a4' (Error: ZCL command 0xa4c138a3c862a7a4/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[48,130,195,49,48,130,223,81]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":33099,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":121},"zclSequence":224,"commandIdentifier":11} timed out after 10000ms))`

@Koenkk Can You help with this, please ? Because of this errors traffic my MQTT web is lagging as much as I can't use it. 
Thanks for Your reply :)

**Comment by Koenkk** [comment]
@mdpatryk pushed a fix, let me know if it works.

> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by mdpatryk** [comment]
> [@mdpatryk](https://github.com/mdpatryk) pushed a fix, let me know if it works.
> 
> > Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

Yes, it works great! Thanks a lot Master

**Comment by alkandery75** [comment]
Hi,
I'm facing same issue with MOES SFL02-Z- switches and unable to control them.

How can I disable mcuSyncTime ?

Also, I'm unable to control newly added switches:

z2m: Failed to configure 'Base Kitchen Corridor', attempt 3 (Error: ZCL command 0xa4c13891bf1e4021/1 genBasic.read(["manufacturerName","zclVersion","appVersion","modelId","powerSource",65534], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Delivery failed for '13162'.) at EmberOneWaitress.deliveryFailedFor (/app/node_modules/.pnpm/zigbee-herdsman@6.3.2/node_modules/zigbee-herdsman/src/adapter/ember/adapter/oneWaitress.ts:100:31) at EmberAdapter.onMessageSent (/app/node_modules/.pnpm/zigbee-herdsman@6.3.2/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:458:42) at Ezsp.emit (node:events:518:28) at Ezsp.ezspMessageSentHandler (/app/node_modules/.pnpm/zigbee-herdsman@6.3.2/node_modules/zigbee-herdsman/src/adapter/ember/ezsp/ezsp.ts:5082:14) at Ezsp.callbackDispatch (/app/node_modules/.pnpm/zigbee-herdsman@6.3.2/node_modules/zigbee-herdsman/src/adapter/ember/ezsp/ezsp.ts:734:26) at Ezsp.onAshFrame (/app/node_modules/.pnpm/zigbee-herdsman@6.3.2/node_modules/zigbee-herdsman/src/adapter/ember/ezsp/ezsp.ts:387:22) at UartAsh.emit (node:events:518:28) at Immediate.<anonymous> (/app/node_modules/.pnpm/zigbee-herdsman@6.3.2/node_modules/zigbee-herdsman/src/adapter/ember/uart/ash.ts:1192:45) at processImmediate (node:internal/timers:485:21))

**Comment by Koenkk** [comment]
@alkandery75 its fixed in the latest dev


> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by JNow01** [comment]
> [@JNow01](https://github.com/JNow01)
> 
>     * could you provide the debug log of this?
> 
>     * I'm afraid I cannot disable the time sync of this device, otherwise the device wouldn't have the time which is required for the schedule.

Hello @Koenkk, sorry for such a late reply - [here's the full debug log](https://pastebin.com/R0biAEM2).
Thanks!

**Comment by Koenkk** [comment]
I see most of the time it succeeds, is the time of `Bureau - radiateur` correct?

**Comment by JNow01** [comment]
Well the thing is, I can't find any "date" or "time" property, or any way to display the internal time on the valve... And the [user guide](https://manuals.plus/ae/1005006070061141) doesn't give a clue either. There's only a "last seen" attribute, which, I guess, is not internal but relates to Z2M's clock :

```
{
    "battery": 75,
    "boost_heating": "OFF",
    "comfort_temperature": 19,
    "current_heating_setpoint": 12,
    "eco_temperature": 17,
    "fault_alarm": {
        "battery_low": false,
        "error": 2
    },
    "frost_protection": "OFF",
    "last_seen": "2025-11-09T16:40:56.610Z",
    "linkquality": 200,
    "local_temperature": 18.5,
    "preset": "manual",
    "scale_protection": "ON",
    "system_mode": "off",
    "battery_low": null,
    "child_lock": null,
    "device": {
        "applicationVersion": 73,
        "dateCode": "",
        "friendlyName": "Bureau - radiateur",
        "hardwareVersion": 1,
        "ieeeAddr": "0xa4c1382913b655dd",
        "manufacturerID": 4417,
        "manufacturerName": "_TZE204_pcdmj88b",
        "model": "TS0601_thermostat_4",
        "networkAddress": 54031,
        "powerSource": "Battery",
        "stackVersion": 0,
        "type": "EndDevice",
        "zclVersion": 3
    },
    "error": null,
    "holiday_temperature": null,
    "local_temperature_calibration": null,
    "schedule_friday": null,
    "schedule_monday": null,
    "schedule_saturday": null,
    "schedule_sunday": null,
    "schedule_thursday": null,
    "schedule_tuesday": null,
    "schedule_wednesday": null
}
```

**Comment by Koenkk** [comment]
If you set a time based schedule, does that work? I guess it uses time for that.

**Comment by nocin** [comment]
Hi, 

had a few network crashes the last 2 weeks. When searching in the logs, in seems to start with `zhc:tuya: Failed to sync time`.

```
[2025-11-18 23:22:53] error: 	zhc:tuya: Failed to sync time with '0xa4c138befdec3790' (Error: ZCL command 0xa4c138befdec3790/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[105,28,241,180,105,28,255,196]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'Timeout' (9999)))
[2025-11-18 23:23:05] error: 	zhc:tuya: Failed to sync time with '0xa4c1381ceab7515f' (Error: ZCL command 0xa4c1381ceab7515f/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[105,28,241,191,105,28,255,207]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:05] error: 	zhc:tuya: Failed to sync time with '0xa4c1381ceab7515f' (Error: ZCL command 0xa4c1381ceab7515f/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[105,28,241,192,105,28,255,208]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:09] warning: 	z2m: Failed to ping 'Kleiner Flur B3' (attempt 1/2, ZCL command 0xb43a31fffe566e77/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:09] error: 	zhc:tuya: Failed to sync time with '0xa4c13849727e142e' (Error: ZCL command 0xa4c13849727e142e/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[105,28,241,206,105,28,255,222]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:10] error: 	zh:controller:device: Read response to 0x84fd27fffece7ef1 failed (ZCL command 0x84fd27fffece7ef1/1 genTime.readRsp({"localTime":816823380}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":79,"writeUndiv":false}) failed (Data request failed with error: 'Timeout' (9999)))
[2025-11-18 23:23:10] error: 	zh:controller:device: Read response to 0x84fd27fffece7ef1 failed (ZCL command 0x84fd27fffece7ef1/1 genTime.readRsp({"localTime":816823380}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":79,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:10] error: 	zh:controller:device: Read response to 0x84fd27fffece7ef1 failed (ZCL command 0x84fd27fffece7ef1/1 genTime.readRsp({"localTime":816823381}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":79,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:10] error: 	zh:controller:device: Read response to 0x84fd27fffece7ef1 failed (ZCL command 0x84fd27fffece7ef1/1 genTime.readRsp({"localTime":816823381}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":79,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:10] error: 	zh:controller:device: Read response to 0x84fd27fffece7ef1 failed (ZCL command 0x84fd27fffece7ef1/1 genTime.readRsp({"localTime":816823381}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":79,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:10] error: 	zh:controller:device: Read response to 0x84fd27fffece7ef1 failed (ZCL command 0x84fd27fffece7ef1/1 genTime.readRsp({"localTime":816823381}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":79,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:10] error: 	zh:controller:device: Read response to 0x84fd27fffece7ef1 failed (ZCL command 0x84fd27fffece7ef1/1 genTime.readRsp({"localTime":816823381}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":79,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:10] error: 	zh:controller:device: Read response to 0x84fd27fffece7ef1 failed (ZCL command 0x84fd27fffece7ef1/1 genTime.readRsp({"localTime":816823382}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":79,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:10] error: 	zh:controller:device: Read response to 0x84fd27fffece7ef1 failed (ZCL command 0x84fd27fffece7ef1/1 genTime.readRsp({"localTime":816823382}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":79,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:10] error: 	zh:controller:device: Read response to 0x84fd27fffece7ef1 failed (ZCL command 0x84fd27fffece7ef1/1 genTime.readRsp({"localTime":816823382}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":79,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:11] error: 	zh:controller:device: Read response to 0x84fd27fffece7ef1 failed (ZCL command 0x84fd27fffece7ef1/1 genTime.readRsp({"localTime":816823383}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":79,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:11] error: 	zh:controller:device: Read response to 0x84fd27fffece7ef1 failed (ZCL command 0x84fd27fffece7ef1/1 genTime.readRsp({"localTime":816823383}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":79,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:11] error: 	zh:controller:device: Read response to 0x84fd27fffece7ef1 failed (ZCL command 0x84fd27fffece7ef1/1 genTime.readRsp({"localTime":816823383}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":79,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:11] error: 	zh:controller:device: Read response to 0x84fd27fffece7ef1 failed (ZCL command 0x84fd27fffece7ef1/1 genTime.readRsp({"localTime":816823383}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":79,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:11] error: 	zh:controller:device: Read response to 0x84fd27fffece7ef1 failed (ZCL command 0x84fd27fffece7ef1/1 genTime.readRsp({"localTime":816823383}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":79,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:12] warning: 	z2m: Failed to ping 'Kleiner Flur B3' (attempt 2/2, ZCL command 0xb43a31fffe566e77/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:14] error: 	zh:controller:device: Handling of poll check-in from 0x84b4dbfffecd36ad failed (ZCL command 0x84b4dbfffecd36ad/1 genPollCtrl.checkinRsp({"startFastPolling":0,"fastPollTimeout":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false,"sendPolicy":"immediate"}) failed (Data request failed with error: 'Timeout' (9999)))
[2025-11-18 23:23:14] error: 	zh:controller:device: Handling of poll check-in from 0x84b4dbfffecd36ad failed (ZCL command 0x84b4dbfffecd36ad/1 genPollCtrl.checkinRsp({"startFastPolling":0,"fastPollTimeout":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false,"sendPolicy":"immediate"}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:14] error: 	zh:controller:device: Handling of poll check-in from 0x84b4dbfffecd36ad failed (ZCL command 0x84b4dbfffecd36ad/1 genPollCtrl.checkinRsp({"startFastPolling":0,"fastPollTimeout":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false,"sendPolicy":"immediate"}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:25] error: 	z2m: Publish 'set' 'brightness' to 'Laterne Gartenpforte B3' failed: 'Error: ZCL command 0x842e14fffe40fe23/1 genLevelCtrl.moveToLevelWithOnOff({"level":14,"transtime":450}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241))'
[2025-11-18 23:23:25] error: 	z2m: Publish 'set' 'brightness' to 'Terrasse B3' failed: 'Error: ZCL command 0xf0d1b800001a1a41/1 genLevelCtrl.moveToLevelWithOnOff({"level":14,"transtime":225}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241))'
[2025-11-18 23:23:25] error: 	z2m: Publish 'set' 'brightness' to 'Laterne Haus Rückseite' failed: 'Error: ZCL command 0x187a3efffe6dd0e5/1 genLevelCtrl.moveToLevelWithOnOff({"level":14,"transtime":225}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241))'
[2025-11-18 23:23:25] error: 	z2m: Publish 'set' 'brightness' to 'Esszimmer Kühlschrank' failed: 'Error: ZCL command 0xa49e69fffea8f0f6/1 genLevelCtrl.moveToLevelWithOnOff({"level":3,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241))'
[2025-11-18 23:23:25] error: 	z2m: Publish 'set' 'brightness' to 'Laterne B1' failed: 'Error: ZCL command 0x2c1165fffe03a53f/1 genLevelCtrl.moveToLevelWithOnOff({"level":39,"transtime":225}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241))'
[2025-11-18 23:23:25] error: 	z2m: Publish 'set' 'color' to 'Esszimmer Kühlschrank' failed: 'Error: ZCL command 0xa49e69fffea8f0f6/1 lightingColorCtrl.moveToColor({"transtime":450,"colorx":44695,"colory":20644}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241))'
[2025-11-18 23:23:26] error: 	z2m: Publish 'set' 'brightness' to 'Weg zur Haustür B3' failed: 'Error: ZCL command 0xf0d1b800001a1952/1 genLevelCtrl.moveToLevelWithOnOff({"level":14,"transtime":225}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241))'
[2025-11-18 23:23:46] error: 	zh:controller:device: Read response to 0xa4c13896fd9a1f6b failed (ZCL command 0xa4c13896fd9a1f6b/1 genTime.readRsp({"localTime":816823427}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":183,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:46] error: 	zh:controller:device: Read response to 0xa4c13896fd9a1f6b failed (ZCL command 0xa4c13896fd9a1f6b/1 genTime.readRsp({"localTime":816823427}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":183,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:47] error: 	zh:controller:device: Read response to 0xa4c13896fd9a1f6b failed (ZCL command 0xa4c13896fd9a1f6b/1 genTime.readRsp({"localTime":816823427}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":183,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:47] error: 	zh:controller:device: Read response to 0xa4c13896fd9a1f6b failed (ZCL command 0xa4c13896fd9a1f6b/1 genTime.readRsp({"localTime":816823427}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":183,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:47] error: 	zh:controller:device: Read response to 0xa4c13896fd9a1f6b failed (ZCL command 0xa4c13896fd9a1f6b/1 genTime.readRsp({"localTime":816823427}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":183,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:23:47] error: 	z2m: Publish 'set' 'color' to 'Weg zur Haustür B3' failed: 'Error: ZCL command 0xf0d1b800001a1952/1 lightingColorCtrl.moveToColor({"transtime":225,"colorx":39255,"colory":25034}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241))'
[2025-11-18 23:23:48] error: 	z2m: Publish 'set' 'color' to 'Terrasse B3' failed: 'Error: ZCL command 0xf0d1b800001a1a41/1 lightingColorCtrl.moveToColor({"transtime":225,"colorx":39255,"colory":25034}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241))'
[2025-11-18 23:23:48] error: 	z2m: Publish 'set' 'color' to 'Laterne B1' failed: 'Error: ZCL command 0x2c1165fffe03a53f/1 lightingColorCtrl.moveToColor({"transtime":225,"colorx":39255,"colory":25034}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241))'
[2025-11-18 23:23:48] error: 	z2m: Publish 'set' 'color_temp' to 'Laterne Haus Rückseite' failed: 'Error: ZCL command 0x187a3efffe6dd0e5/1 lightingColorCtrl.moveToColorTemp({"colortemp":454,"transtime":225}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241))'
[2025-11-18 23:24:31] warning: 	z2m: Failed to ping 'Signal Repeater' (attempt 1/2, ZCL command 0x84fd27fffe6bddd5/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
[2025-11-18 23:24:34] warning: 	z2m: Failed to ping 'Signal Repeater' (attempt 2/2, ZCL command 0x84fd27fffe6bddd5/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'undefined' (241)))
```

0xa4c138befdec3790 = https://www.zigbee2mqtt.io/devices/TRV801_1.html#moes-trv801_1
0xa4c1381ceab7515f = https://www.zigbee2mqtt.io/devices/ZTH08.html#tuya-zth08
0xa4c13849727e142e = https://www.zigbee2mqtt.io/devices/TRV801_1.html#moes-trv801_1
0x84fd27fffece7ef1  = https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html#tuya-ts011f_plug_1

Never had any issue before with these devices.

**Comment by hamiller** [comment]
~I do have the same problem (spamming log with `zhc:tuya: Failed to sync time with ... (Error: ZCL command 0xa4c13877e086d539/1 manuSpecificTuya.mcuSyncTime`
I have these devices: https://www.zigbee2mqtt.io/devices/BHT-002_BHT-006.html#moes-bht-002%252Fbht-006~

Zigbee2Mqtt-Version 2.6.3-1

Nevermind: after disconnecting the dongle for 5minutes, everything went back to normal

**Comment by syldes81** [comment]
Same issue here with with TUYA [TH01Z ](https://www.zigbee2mqtt.io/devices/TH01Z.html#tuya-th01z).
It is not a thermostat, just a temperature/humidity sensor.
I'm using Zigbee dongle SLZB-MR4U with the EFR32MG26 as the Zigbee coordinator.

```
2025-11-24 15:51:53] error: 	zhc:tuya: Failed to sync time with '0xa4c1386c06dc289e' (Error: ZCL command 0xa4c1386c06dc289e/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[105,36,113,5,105,36,127,21]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Delivery failed for '16043'.))
[2025-11-24 15:51:59] error: 	zhc:tuya: Failed to sync time with '0xa4c1386c06dc289e' (Error: ZCL command 0xa4c1386c06dc289e/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[105,36,113,10,105,36,127,26]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Delivery failed for '16043'.))
[2025-11-24 15:52:10] error: 	zhc:tuya: Failed to sync time with '0xa4c1386c06dc289e' (Error: ZCL command 0xa4c1386c06dc289e/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[105,36,113,21,105,36,127,37]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Delivery failed for '16043'.))
[2025-11-24 15:58:32] error: 	zhc:tuya: Failed to sync time with '0xa4c1386c06dc289e' (Error: ZCL command 0xa4c1386c06dc289e/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[105,36,114,148,105,36,128,164]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Delivery failed for '16043'.))
[2025-11-24 16:01:02] error: 	zhc:tuya: Failed to sync time with '0xa4c1386c06dc289e' (Error: ZCL command 0xa4c1386c06dc289e/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[105,36,115,42,105,36,129,58]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Delivery failed for '16043'.))
```

Thanks for your help !

**Comment by wherzig** [comment]
I have the same Problem with 2.6.3 on homeassistant with adapter SLZB-06 each time I command to set the plug on or off:

```
[27.11.2025, 19:34:40] zhc:tuya: Failed to sync time with '0xa4c138b8bcbd20b7' (Error: ZCL command 0xa4c138b8bcbd20b7/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[105,40,153,164,105,40,167,180]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Timeout - 27257 - 1 - 36 - 61184 - 11 after 10000ms))
[27.11.2025, 19:35:22] zhc:tuya: Failed to sync time with '0xa4c138b8bcbd20b7' (Error: ZCL command 0xa4c138b8bcbd20b7/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[105,40,153,195,105,40,167,211]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Timeout - 27257 - 1 - 65 - 61184 - 11 after 10000ms))
[27.11.2025, 19:37:11] zhc:tuya: Failed to sync time with '0xa4c138b8bcbd20b7' (Error: ZCL command 0xa4c138b8bcbd20b7/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[105,40,154,12,105,40,168,28]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Timeout - 27257 - 1 - 147 - 61184 - 11 after 10000ms))

```
There is no problem getting the status of the Zigbee devices. Just to change status.

Thanks for your help!

**Comment by pompilir** [comment]
I get this error with a tuya thermostat TS0601 _TZE204_xnbkhhdr (Wall thermostat)

`[2025-12-02 20:37:59] error:    zhc:tuya: Failed respond to version response '0xa4c138ccff178d6c' (Error: ZCL command 0xa4c138ccff178d6c/1 manuSpecificTuya.mcuVersionRequest({"seq":2}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed ({"target":43593,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":228},"zclSequence":37,"commandIdentifier":11} timed out after 10000ms))
`
My log is full of these warnings and I get z2m restart 1-2 times per day. I'm using z2m 2.6.3

**Comment by wherzig** [comment]
Since I couldn't reliably turn off or turn off my TS011F plugs, I just downgraded from 2.6.3 to 2.7.0-1 (my backup). I was getting the  above error messages: "Failed to sync time with". There was no problem with reading the status of the TS011F plugs but turning them on or off did not work most of the times.

Now everything works well again.

**Comment by jeff114** [comment]
Hello
Same problem, I can read values from climats zwt100 and bht-00, but can't set anything on it:
Failed to sync time with '0x403059fffe953f15' (Error: ZCL command 0x403059fffe953f15/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[105,80,237,115,105,80,251,131]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Delivery failed for '15417'.))
Try to downgrade to 2.6.3 but nothing change.

**Comment by JNow01** [comment]
> If you set a time based schedule, does that work? I guess it uses time for that.

Hi, sorry again for this very late reply. Just to let you know, at the moment I've given up on this issue and bought Sonoff TRVZB instead. However, if anyone wants to spend time and have Z2M work properly with this model, I can give away one of [them](https://www.zigbee2mqtt.io/devices/TS0601_thermostat_4.html#tuya-ts0601-thermostat-4) - also known as BAB-1413Pro-E and sold [here](https://www.cafago.com/en/p-c-paa5463w-3.html)  - for free.
@Koenkk or any other dev around, just let me know if you're interested.
Season's greetings to everyone !

**Comment by wherzig** [comment]
> Since I couldn't reliably turn off or turn off my TS011F plugs, I just downgraded from 2.6.3 to 2.7.0-1 (my backup). I was getting the above error messages: "Failed to sync time with". There was no problem with reading the status of the NOUS A1Z plugs but turning them on or off did not work most of the times.
> 
> Now everything works well again.

Wrote it wrong. Downgraded from 2.7.0-1 to 2.6.1-1 now everything works since 28 days. Setting TS011F plugs works like a charm again. For me it looks like the code for NOUS A1Z (Zigbee model TS011F) has changed. With 2.7 even the device picture has changed to something different.

Will stay at this version as long as possible and do no update.

<img width="1012" height="217" alt="Image" src="https://github.com/user-attachments/assets/d506e7cd-7e49-4cf4-ae41-d9638e799899" />

And now my devices picture shows again like they look in reality:

<img width="969" height="69" alt="Image" src="https://github.com/user-attachments/assets/c2cb02be-09df-43b3-9c0d-5d40551b4295" />

**Comment by djderex** [comment]
I am encountering same issues on a fresh install of home assistant latest version as of 15.03.2026 , latest zigbee2mqtt version 2.9.1-1. The device that makes this logs flood is Zemismart ZMS-206US-1 (1 gang).  Please help !

Z2m Logs:

[2026-04-01 19:05:05] debug: 	z2m: Received Zigbee message from 'KitchenLight', type 'commandMcuSyncTime', cluster 'manuSpecificTuya', data '{"payloadSize":191}' from endpoint 1 with groupID 0
[2026-04-01 19:05:05] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2026-04-01 19:05:05] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=1](ackRx=0 frmTx=1)
[2026-04-01 19:05:05] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=1 frmNum=6](frmRx=6) Added to rxQueue
[2026-04-01 19:05:05] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=7](ackRx=1)
[2026-04-01 19:05:05] debug: 	zh:ember:ezsp: <=== [FRAME: ID=52:"SEND_UNICAST" Seq=208 Len=7]
[2026-04-01 19:05:05] debug: 	zh:ember:ezsp: ~~~> [SENT type=DIRECT apsSequence=5 messageTag=47 status=OK]
[2026-04-01 19:05:05] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2026-04-01 19:05:05] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=1](ackRx=1 frmTx=1)
[2026-04-01 19:05:05] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=1 frmNum=7](frmRx=7) Added to rxQueue
[2026-04-01 19:05:05] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=0](ackRx=1)
[2026-04-01 19:05:05] debug: 	zh:ember:ezsp: <=== [CBFRAME: ID=63:"MESSAGE_SENT_HANDLER" Seq=208 Len=22]
[2026-04-01 19:05:05] debug: 	zh:ember:ezsp: ezspMessageSentHandler: status=OK type=DIRECT indexOrDestination=55977 apsFrame={"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4352,"groupId":0,"sequence":5} messageTag=47
[2026-04-01 19:05:05] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2026-04-01 19:05:05] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=1](ackRx=1 frmTx=1)
[2026-04-01 19:05:05] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=1 frmNum=0](frmRx=0) Added to rxQueue
[2026-04-01 19:05:05] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=1](ackRx=1)
[2026-04-01 19:05:05] debug: 	zh:ember:ezsp: <=== [CBFRAME: ID=69:"INCOMING_MESSAGE_HANDLER" Seq=208 Len=35]
[2026-04-01 19:05:05] debug: 	zh:ember:ezsp: ezspIncomingMessageHandler: type=UNICAST apsFrame={"profileId":260,"clusterId":64529,"sourceEndpoint":1,"destinationEndpoint":1,"options":256,"groupId":0,"sequence":247} packetInfo:{"senderShortId":7295,"senderLongId":"0xffffffffffffffff","bindingIndex":255,"addressIndex":255,"lastHopLqi":116,"lastHopRssi":-71,"lastHopTimestamp":0} messageContents=18220a067023eb1e0000
[2026-04-01 19:05:05] debug: 	zh:controller: Received payload: clusterID=64529, address=7295, groupID=0, endpoint=1, destinationEndpoint=1, wasBroadcast=false, linkQuality=116, frame={"header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":34,"commandIdentifier":10},"payload":[{"attrId":28678,"dataType":35,"attrData":7915}],"command":{"ID":10,"name":"report","parameters":[{"name":"attrId","type":9},{"name":"dataType","type":8},{"name":"attrData","type":1000}]}}

**Comment by djderex** [comment]
Hi guys, i just noticed my Zemismart -206EU-1 is being seen as ZMS-206US-1 on zigbee2mqtt , and i do get this message above several time PER SECOND. Can anyone please help ? @Koenkk

**Comment by domcars0** [comment]
Hi,

Same errors here (every 2 hours) with a thermostat radiator Valve Mazda TR-M2Z (TS0601, _TZE284_k6rdmisz) , Z2M V2.9.2 , Coordinator "EmberZNet  8.0.2 [GA]"

error: 	zhc:tuya: Failed to sync time with '0xa4c138e25a1598ed' (Error: ZCL command 0xa4c138e25a1598ed/1 manuSpecificTuya.mcuSyncTime({"payloadSize":8,"payload":[49,115,60,207,49,115,88,239]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Delivery failed for '54708'.))
