### ISSUE TITLE
Invalid External Converter after 2.6.3 update

### ISSUE THREAD

**Issue by TLongstride** [Koenkk/zigbee2mqtt#29438]
### What happened?

Hi,

I have a custom converter that worked fine up to version 2.6.2, but it suddenly became invalid after the 2.6.3 update.

The log only says to check the converter.

I’ve checked the changelog but couldn’t find anything that might affect my external converter.

When I revert back to version 2.6.2, the converter works perfectly.

[https://github.com/TLongstride/THZReader/blob/main/Zigbee2MQTT/THZReader.js](https://github.com/TLongstride/THZReader/blob/main/Zigbee2MQTT/THZReader.js)

### Zigbee2MQTT version

2.6.3

### Adapter firmware version

not revelant

### Adapter

not revelant

### Setup

Addon Home Assitant

### Debug log

[2025-11-03 12:45:47] error: z2m: Failed to load external converter 'THZReader.js'. Check the code for syntax error and make sure it is up to date with the current Zigbee2MQTT version.

[2025-11-03 12:45:47] error: z2m: Invalid external converter 'THZReader.js' was ignored and renamed to prevent interference with Zigbee2MQTT. (Cannot read properties of undefined (reading 'options'))

**Comment by chris-1243** [comment]
The converter provided via your link seems to have been corrected. It is perfectly working on 2.6.3.

Would you mind close this issue. Thanks.

**Comment by TLongstride** [comment]
Yes, I did.

**Comment by Berdi86** [comment]
I don't know what is still wrong, but I can't load any external converter. Tried several ones with copy paste. Always "invalid"

**Comment by TLongstride** [comment]
> I don't know what is still wrong, but I can't load any external converter. Tried several ones with copy paste. Always "invalid" 

With my product ?
