### ISSUE TITLE
Nous A7z smart Plug is detected as TS011F_plug_3 Tuya

### ISSUE THREAD

**Issue by TheBermud** [Koenkk/zigbee2mqtt#29448]
### What happened?

I purchased seven Nous smart plugs, model A7z. Three are recognized correctly, while the others are recognized and displayed as TS011F_plug_3
Tuya. After restarting Zigbee2mqtt, only one is recognized correctly, while all others are recognized as Tuya devices.
This also means that no firmware updates can be performed. 

### What did you expect to happen?

I hope that the smart plug is recognized correctly.

### Zigbee2MQTT version

2.6.3

### Adapter firmware version

20240716

### Adapter

zstack3x0

### Setup

I run zigbee2mqtt on Proxmox as an lxc container.  Coordinator ist SMLIGHT SLZB-06P7.
Maschine :#1 SMP PREEMPT_DYNAMIC PMX 6.14.11-4 (2025-10-10T08:04Z) - 6.14.11-4-pve - x64
CPU: 12th Gen Intel(R) Core(TM) i5-1260

**Comment by ps1noob** [comment]
Can confirm on my side, all my Nous A7Z (i own 3 of them) were recognized correctly with version 2.6.2, since version 2.6.3 they are recognized as Tuya TS011F_plug_3.

**Comment by Koenkk** [comment]
Fixed in latest dev.

> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by WoodenDuke** [comment]
I have 20 Nous A7Z plugs.

Five of the plugs are correctly identified as A7Z, all the others are identified as TS011F_plug_1.

So the problem still seems to exist.

Do I need to open a new issue for this?

**Comment by andrei-lazarov** [comment]
What's the ID of the plugs? _TZ3000_xxxxxxxx
Do they work correctly? Is it just the picture that's wrong?

**Comment by WoodenDuke** [comment]
Sorry, I wasn’t sure if this is the correct place to post… Thanks for your answer!

Here is the device information for my Nous A7Z as shown in Zigbee2MQTT:

Zigbee model:
TS011F
_TZ3008_reatplte

Model:
[TS011F_plug_1](https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html#tuya-ts011f_plug_1)
Smart plug with power monitoring (Tuya)

Firmware version:
66  
App: 0.0 build 0 | Stack: 0.0 build 66

The firmware of my other plugs (which were recognized as A7Z / TS011F / _TZ3210_rwmitwj4) is 82.  
Maybe this also contributes to the misidentification.

The switches seem to work correctly, but there is no OTA update available for version 82, for example, and the image shown in Z2M is not correct.

**Comment by andrei-lazarov** [comment]
- added https://github.com/Koenkk/zigbee-herdsman-converters/pull/11744

There are multiple firmware versions available for ts011f plugs. Search for `tl8258_plug` here:
https://github.com/Koenkk/zigbee-OTA/blob/master/index.json

I have no idea about compatibility and best version. If it works correctly, keep it as is.
Previously 192 was enabled for all plugs, but it wasn't supposed to be?
- https://github.com/Koenkk/zigbee-OTA/pull/1028

**Comment by WoodenDuke** [comment]
Thanks for the clarification and for the superfast addition of the detection fix, Andrei! 👍 

Good to know that the different firmware branches (66 vs. 82) are expected for TS011F-based plugs.
I’ll keep the current firmware for now, as long as it doesn’t cause any issues and as long as no clearly compatible version is available.

Thanks again for the quick fix and the explanation regarding the OTA configuration.

**Comment by rjblake** [comment]
Seems there is yet another version of the Nous A7Z. Mine are also showing as Tuya plug. Can these be added too:

TS011F
_TZ3008_1a8m8wd6

Model:
[TS011F_plug_1](https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html#tuya-ts011f_plug_1)
Smart plug with power monitoring (Tuya)

Firmware version:
66
App: 0.0 build 0 | Stack: 0.0 build 66

**Comment by andrei-lazarov** [comment]
Added, thanks for reporting!
- https://github.com/Koenkk/zigbee-herdsman-converters/pull/12473
