### ISSUE TITLE
Zigbee unstable since 2.6.3(?)

### ISSUE THREAD

**Issue by kambyte0** [Koenkk/zigbee2mqtt#29800]
### What happened?

I'm hesitant to report this issue, but I'm genuinely stuck and need help understanding what caused my previously stable Zigbee network to become unreliable.

I'm running the latest Home Assistant OS, and recently upgraded Z2M from 2.6.2 to 2.6.3 and updated my SLZB-06 coordinator firmware from 20240710 to 20250325, all within the same day. Since these updates, I'm experiencing widespread device instability.

My Tuya PIR sensors are showing odd behavior - their LEDs blink on motion detection, but the status no longer updates in Z2M. Re-pairing temporarily fixes the issue, but it recurs within days. My IKEA Parasoll devices keep dropping from the network, and Aqara devices are becoming unavailable as well.

I know what you might be thinking - that these devices are known for stability issues. However, this exact setup has been rock solid for 2 years with these same devices, so I don't believe this is an inherent device compatibility issue.

I've tried several troubleshooting steps: downgrading the firmware back to 20240710 (no improvement), switching to Zigbee channel 25 and re-pairing all battery devices (stable for about a day, then issues returned), and multiple device deletions and re-additions (no lasting improvement).

Some additional details: no new devices have been added since the issues began, battery levels are adequate, Z2M logs show no errors, and the network map shows affected devices as disconnected from routers (though some still report values intermittently). Interestingly, only end devices are affected while routers remain stable. Router coverage is good across all floors with multiple routers per floor.

Any guidance would be greatly appreciated. I'm really thinking that there might be an issue with 2.6.3?

### What did you expect to happen?

Stable setup, no dropping sensors.

### How to reproduce it (minimal and precise)

Unfortunately, no idea.

### Zigbee2MQTT version

2.6.3

### Adapter firmware version

ZStack3x0 / 20240710

### Adapter

SLZB-06 (CC2652P)

### Setup

Mini PC, proxmox, haos, Z2M over the add-on store.

### Debug log

no error in the log

**Comment by tjkgdd** [comment]
Yes, I'm having a similar problem too.

For some time now, after upgrading Zigbee2MQTT to version 2.6.3 or updating my SLZB-06, my Zigbee network has also been very unstable. It can restart once or twice a day, Zigbee2MQTT disconnects from the SLZB controller, and some devices lose connection. I either have to reset them or, in the case of mains-powered devices, unplug and plug them back in

zslb L core: v2.9.8 / zigbee: 20250325

Just downgraded from 3.1.3 to see if that problem persists on older version of slzb.

**Comment by JC38** [comment]
I’m also having an issue with version 2.6.3.
From the drawings below, we can see that CPU and network traffic increased. This started after upgrading from version 2.6.2 to 2.6.3.
When I review the logs, it appears that many messages are repeated.
The main consequence is a large number of timeouts or the HA scripts not running as expected. For example, lights switch on many seconds after a presence detector has detected someone.

Would it also be possible to have, in the interface, a counter of the messages published over a given period of time, the aim being to see if one or more devices are spamming the network?
<img width="1051" height="1106" alt="Image" src="https://github.com/user-attachments/assets/77549d76-b6b5-4714-8a72-a458f7adfea0" />

<img width="1494" height="1099" alt="Image" src="https://github.com/user-attachments/assets/f803718e-e76e-4784-b0c4-dc7cba00e36f" />

**Comment by mariusgoldberg** [comment]
Hi, I am experiencing the same issues as described above on 2.6.3. Not sure what the cause is but network gets unresponsive within minutes. I can still access and use zigbee2mqtt webinterface without obvious issues but all commands send to devices are receiving timeouts. Once I restart zigbee2mqtt from the webinterface everything works normal for a period of time until it breaks again. Also seeing duplicate messages in log.

However, since I also moved to a new flat with my setup and in that instance added quite a number of new devices / position of devices changed in relation to one another, I am not sure it was the update to 2.6.3 (which I updated to in the new flat) causing the issues or wether the network is unstable due to not completed re-setup of devices / introduction of new devices. But the issues described above are the same.

I will try to downgrade to 2.6.2 and see if that changes anything.

**Comment by vjenne** [comment]
Yes, same problem here. I just can't get my network to keep running for more than 24 hours. In the loggin I suddenly start to get a lot of errors from several devices, than complete chaos in the logging with repeating messages. After this I cant control my devices anymore. SLZB still report that 1 client is connected to the socket(i suppose this is zigbee2mqtt) but I think the communication between z2m en slzb is broken by then.

I had an slzb 06. I thought it was beacuase of this one going faulty so I bought an SLZB MR4U. But I have exactly the same issues. Already did a complete rejoin of my network and switched from channel 26 to 20.
Since I always thought it was beacause of the zigbee network itself I didn't try to downgrade to z2m 2.6.2, so thats what I'm trying to do this evening...

**Comment by kambyte0** [comment]
I think we're going to mix various issues into the same thread. 

For transparency: Initially I stated that I have a slzb 06m - however, its an slzb 06 (CC2652P) like many others here. Maybe there's a mismatch between FW / 2.6.3, I dont have any other explanation. Sidenote: The devices (the ones which are stable) are reacting pretty fast. No issues at all at the complete netword. I'm also more on the country side so I can exclude issues from others in the area. It has to be something around z2m / FW. I'm open to share any other information and doing further tests. However, not sure how as the devices are just dropping without any error somewhere.

**Comment by JC38** [comment]
Here is the fw info for my SLZB-06.
Just to compare with those having the same issues withe the same hardware

<img width="622" height="495" alt="Image" src="https://github.com/user-attachments/assets/4bdc9064-252a-4d63-bc0f-609e74151f56" />

**Comment by alkandery75** [comment]
Same issue for me, it's nightmare :
- Zigbee2MQTT Mesh is very slow 
- Automations stopped working
- Motion Sensors stopped working 
- IKEA Battery powered smart switches stopped working 
- Some Moes light switches starts disappearing from the setup
- Some IKEA Bulbs starts disappearing from the setup
- Permit Join is useless and doing nothing
- Can't add any new device to the setup

This is unbelievable, same issues with last month update as well, and system was unstable for more than 2 weeks. I'm start thinking to move away from Zigbee2MQTT and go for WiFi or Matter since Zigbee2MQTT is totally unstable and very noisy.

How to reproduce it (minimal and precise)
Enable "Permit join (all)" and push the pairing button on Tretakt: nothing happens

Zigbee2MQTT version
2.6.3-1

Adapter
SMLIGHT SLZB-06

Setup
Home assistant Yellow

**Comment by JC38** [comment]
So, could we say that people using SMLIGHT SLZB-06 are getting this problem ? Nobody else with a different controller but with a CC2652P chipset ?

**Comment by Tomcat86878** [comment]
I am having the same issue as well. Using Slaesh CC2652RB USB Stick with newest Z-Stack firmware (march 2025).

**Comment by lovwyr** [comment]
My System shows more or less the same behavior, but with an sonoff_zigbee_3.0_usb_dongle_plus.

**Comment by tjkgdd** [comment]
On November 24th, I downgraded zigbe2mqtt to version 2.6.2.1.

SLZB-06 downgraded ZigBee firmware to version 20240710.

I left SLZB OS at 3.1.3.

Everything works for now. Maybe it's a coincidence or luck. ;-)

**Comment by alkandery75** [comment]
> On November 24th, I downgraded zigbe2mqtt to version 2.6.2.1.
> 
> SLZB-06 downgraded ZigBee firmware to version 20240710.
> 
> I left SLZB OS at 3.1.3.
> 
> Everything works for now. Maybe it's a coincidence or luck. ;-)

I'll try this and check out.

**Comment by JC38** [comment]
Rollback to 2.6.2.1 done a few minutes ago. At the first sight, reactivity is back again and huge latency disappeared.

**Comment by alkandery75** [comment]
> Rollback to 2.6.2.1 done a few minutes ago. At the first sight, reactivity is back again and huge latency disappeared.

How to rollback if I didn't backup ?

**Comment by JC38** [comment]
If you have zigbee2mqtt into /opt/zigbee2mqtt, download zigbee2mqtt-2.6.2.tar.gz into /opt
then

systemctl stop zigbee2mqtt
cd /opt
cp -R /opt/zigbee2mqtt/data /opt/zigbee2mqtt/data-backup-$(date +%F-%H%M)
mv zigbee2mqtt zigbee2mqtt-old
tar xzf zigbee2mqtt-2.6.2.tar.gz 
mv zigbee2mqtt-2.6.2 zigbee2mqtt
cp -R zigbee2mqtt-old/data/* zigbee2mqtt/data/
cd zigbee2mqtt
npm install
systemctl start zigbee2mqtt
systemctl status zigbee2mqtt
journalctl -u zigbee2mqtt -f

**Comment by JC38** [comment]
FYI, after rolling back, everything is fine and CPU/memory have decreased

<img width="2080" height="1088" alt="Image" src="https://github.com/user-attachments/assets/b26e706b-79c7-410e-8e94-f67ec6ba84bc" />

**Comment by kambyte0** [comment]
While downgrading might (or does) solve the issue, it's still not solution. 

@Koenkk Anything we could do to gather more information? Ideally we can fix whatever got introduced in 2.6.3 to get it done in 2.6.4?

€ I dont think the FW SLZB-06 is the issue. I did the downgrade and others without any effect.

**Comment by matteovisotto** [comment]
Same problem for me with the Sonoff Zigbee Dongle-P. I had z2m in a dedicated raspberry pi 3 and initially I thought it was the SD card. Moved everything in a ProxMox VM but this does not solve the problem. Unstable network, lower link quality, and high resource consumption.

**Comment by erik3001** [comment]
I am having the same issue.  2.6.3 on a NUC and zigbee via SLZB-06 on LAN with the latest stable firmware.  It was rock solid for months using 92 zigbee devices, however the last couple of weeks intermitting issues and devices going offline .  Reverted yesterday to 2.6.2 and it seemed rock solid again.  Note, one of the changes I made months ago was to set transmit_power to 10 in the config, before that I was having similar issues.

**Comment by tjkgdd** [comment]
ok, downgrade zigbe2mqtt to 2.6.2, downgrade zigbe firmware on slzb-06 to 20240710 didn't help. Today all my buttons (sonoff and other ziggbe) just stop working. Just buttons. Strange. After full restart, HA and slzb-06 all working again. Overall, things are bad. Something breaks every day.

update:

1 hour later all crash again. :-/

**Comment by alkandery75** [comment]
I have exactly same issues now. Ikea switches and Motion Sensors stopped working.

Re-pairing takes ages and again same issue.

Golden advise:

If your Zigbee2MQTT System is working fine, then never ever update its components even though your version is 1.0 and they reach 9.0. Unless you have a major issue which can only be fixed by updating.

**Comment by vjenne** [comment]
Ok, finally! Downgrading to 2.6.2 also helped for me. I’ve put hours and hours into this. Out of desperation I even bought a new stick (SLZB MR4U). Tried countless combinations of core firmware versions and Zigbee firmware on the stick, but every single day the entire network would go down again. I use Docker, so for me it was just a simple adjustment. And it worked immediately. It’s been stable for 3 days now!

But now, indeed, the question is where things go wrong in 2.6.3. Hopefully Koenk is also aware of these findings?

**Comment by parholmdahl** [comment]
I also have same issues for some time. I have a Sonoff, and devices go offline intermittently. First I thought that some device had gone bad and burst the network with bad data,but can not see anything like that in the logs. Hope someone is finding the issue!

**Comment by Coldness00** [comment]
I'm experiencing same issue with devices that become unresponsive out of nowhere.
I have many device with low repported LQI but they are in a good mesh

Try powering off all devices + coordinators.

<img width="1048" height="527" alt="Image" src="https://github.com/user-attachments/assets/a0b11121-1709-4be0-a3ed-c27f199d59c6" />

<img width="2297" height="1174" alt="Image" src="https://github.com/user-attachments/assets/21a493c6-bb7a-45d4-abe4-59d186980878" />

<img width="2273" height="1271" alt="Image" src="https://github.com/user-attachments/assets/3a1f9d3f-8c3d-4bb9-96fc-6c4003fcc84a" />

<img width="2560" height="4605" alt="Image" src="https://github.com/user-attachments/assets/041d5c92-227c-4870-94a2-03112e88282b" />

**Comment by Koenkk** [comment]
Can somebody provide the debug logging of +- 10 hours on z2m 2.6.2 (responsive) and 2.6.3 (not responsive)?

**Comment by vjenne** [comment]
ah unfortunately my system also crashed this afternoon with 2.6.2 !!! 
I really don't know what to do now. Still, I was able to keep it online for multiple days with 2.6.2 but still not good enough. 

I've attached my log of today... I hope you can find  the trigger of the problem. At 12:54 I did a manual reset of the SLZB MR4U.

**Comment by erik3001** [comment]
> Can somebody provide the debug logging of +- 10 hours on z2m 2.6.2 (responsive) and 2.6.3 (not responsive)?

Is it ok to use 2.7.0?  I have 24+ debug logging of 2.6.2 and want to try the 2.7.0

**Comment by kambyte0** [comment]
Just a general update from my side: I kept 2.6.3 for some days and it was stable (?!). The only thing I've changed: Repowered my Tuya lamps ([CK-BL702-AL-01](https://www.zigbee2mqtt.io/devices/CK-BL702-AL-01.html#tuya-ck-bl702-al-01)).

So I thought lets give the latest 2.7.0 a go and since the release, its running fine. Honestly...no idea. Still no idea if it was just bad luck or whatever - but as its stable and devices wont drop off, I cant provide much information.

**Comment by t3ch-fr3ak** [comment]
I was running Z2M 2.6.2 until mid of November. Back then, I upgraded to 2.6.3 and after a few hours I ran into the same issues described aboved. There weren't really error messages, the log looked alright. I even tried to change the firmware of my Sonoff ZStack3x0 coordinator with no change, and reverted back afterwards. Only after downgrading to 2.6.2 everything was fine again. Yesterday, I installed 2.7.0 and my system is running for 23 hours without running into the issues of 2.6.2.

**Comment by vjenne** [comment]
I think I have some kind of other problem. Also wil 2.6.2 I have a complete shutdown every 24 hours. Just updated to 2.7.0. But I don't think this is going to solve the problem.
I use Z2M in a docker. Could that have anything to do with it?

**Comment by erik3001** [comment]
Running almost 48 hours with 2.7.0 and it is rock solid.  No devices went offline, responsiveness is good.

**Comment by drauziooppenheimer** [comment]
I was having the same problem, but upgrading to 2.7.1 seems to have fixed it. In my case, I think it was related to this issue: https://github.com/Koenkk/zigbee2mqtt/issues/29999, but I'm mentioning it here in case it might also be relevant.

I have a ZigStar UZG-01, and I noticed that when toggling my ThirdReality Smart Plugs with group commands, it was taking at least 5 seconds to turn them on sometimes. Turning them off was pretty quick, but when they turn on, they send a bunch of power-monitoring messages, which I think were slowing things down due to high disk write.

**Comment by parholmdahl** [comment]
After upgrading to 2.7 my problems disappeared also. I notice that the lqi
of some units are strangely low (in the middle of the house and connected
to live wire) but they stay connected now…

sön 7 dec. 2025 kl. 17:16 skrev Drauzio Oppenheimer <
***@***.***>:

**Comment by kambyte0** [comment]
I'm glad to hear that for most of the people here, issues are resolved by upgrading to the latest version. As I dont expect any more outcome of the log check i'll keep this issue tracker clean and close this one.

**Comment by Tomcat86878** [comment]
Hi everybody, 

Unfortunately after upgrading from 2.6.2 to 2.7.1 the problem came back, but just after letting it run for several hours. Please find the latest log files from 2.7.1 attached. I downgraded to 2.6.2 again and will post the log files after letting it run for a couple of hours. 

@kambyte0 Could you please reopen the issue?

HINT: I use Nous A1Z smart outlets and think they are rebranded Tuya devices and wonder if this is losely connected to this issue: [(https://github.com/Koenkk/zigbee2mqtt/issues/30106)]

[271_log.log](https://github.com/user-attachments/files/24061692/271_log.log)
[271_log1.log](https://github.com/user-attachments/files/24061691/271_log1.log)
[271_log2.log](https://github.com/user-attachments/files/24061693/271_log2.log)

**Comment by t3ch-fr3ak** [comment]
> Unfortunately after upgrading from 2.6.2 to 2.7.1 the problem came back, but just after letting it run for several hours. Please find the latest log files from 2.7.1 attached. I downgraded to 2.6.2 again 

Same for me. It went well for about 48 hours, then the issues of 2.6.3 occurred again. Today, it was very unresponsive, despite several restarts. Only after downgrading to 2.6.2 all issues got resolved. 

I also use a lot of Nous A1Z smart outlets. I am running Z2M as a docker container.

**Comment by Tomcat86878** [comment]
One more hint: Downgrading to 2.6.2 and just restarting my docker container did not resolve the issue completely. I had to reboot my server, probably disconnecting and reconnecting the USB stick would have worked as well. 

Still monitoring and will provide new logs as soon as I recorded several hours of data.

**Comment by Tomcat86878** [comment]
Please find the logs from 2.6.2 below. Don't know if it important for this bug, but it also shows failed pings from time to time. But the overall experience is much better and the network responses more reliable and quick. 

[log.log](https://github.com/user-attachments/files/24087228/log.log)
[log1.log](https://github.com/user-attachments/files/24087227/log1.log)
[log2.log](https://github.com/user-attachments/files/24087226/log2.log)

@Koenkk Are these logs okay to work with?

**Comment by Belgose** [comment]
Having the same issue here: Zigbee drop offs at random moments (during day or night).
Setup:
SLZB-06p10
Firmware: core: v3.1.3 / zigbee: 20240716 
Zigbee2MQTT Version: 2.7.1-1 

After having seen this with an SLZB-06, I swapped to the 06p10, without success, now I tried to change the setup from network based to usb connection, but the connection dropped again this night.
Unfortunately, logfiles were deleted when restarting the z2m Add-In.

**Comment by andyblac** [comment]
for me the connection issues only seem to related to battery powered devices, for example some sensors (not all) I have double activate them ie Open, Close, Open a door sensor for it recognise that the door has opened. From what I have noticed it is devices that are connected to a router device, and if they are connected directly to the co-ordinator they seem to operate as normal. Also if I don't use a device for about 36 Hours they loose connection, but a simple activate (open / close / walk in front of a motion sensor) a few times bring them back online.

**Comment by andyblac** [comment]
no change with `2.7.2`

**Comment by JC38** [comment]
I rolled back to version 2.6.2 again because the later versions are not satisfactory for a production environment. The responsiveness of the equipment is no longer up to scratch. For example, motion sensors that control lighting do not change state quickly enough, or sometimes not at all. When you check their status in the Zigbee2mqtt web interface, it is common to see a motion sensor with its occupancy stuck on “Clear” even while I am standing right in front of it. Simply pressing the refresh button in the web interface makes its status update and the light turns on. After going back to version 2.6.2, the responsiveness of the equipment returns to normal.

It doesn’t seem that I’m the only one experiencing this — how can we help contribute to resolving this problem?

**Comment by andyblac** [comment]
can anyone explain how I can rollback to 2.6.2, if I'm running HAOS, and don't have a backup from 2.6.2 ?, 

Thanks 
Andy

**Comment by pascalschmiederer** [comment]
Like here explained: https://github.com/Koenkk/zigbee2mqtt/issues/29800#issuecomment-3581279937

**Comment by andyblac** [comment]
> Like here explained: [#29800 (comment)](https://github.com/Koenkk/zigbee2mqtt/issues/29800#issuecomment-3581279937)

looks like that is not for HAOS, as it is not installed as a add-on (docker container).

**Comment by andyblac** [comment]
is there an easy way to stop my sockets acting as routers, without removing them for Z2M ?

**Comment by davidrpfarinha** [comment]
Just tried to jump to latest, and still facing the same slowness!
Can't get hold of what is causing this.
I rollbacked to v2.6.3, and it is smooth as butter.

**Comment by lavir** [comment]
> Just tried to jump to latest, and still facing the same slowness! Can't get hold of what is causing this. I rollbacked to v2.6.3, and it is smooth as butter.

That's really odd. What radical changes were made to the code that led to this problem?

**Comment by jesusgcas** [comment]
I've been experiencing the same problems for weeks. Also SLZB-06 and some battery devices not responding for a short period of time and then a few minutes later everything works again as intended. Its kind of annoying. I tried many things except restoring a backup.

**Comment by lavir** [comment]
In my case, I use SLZB-MR3, which works fine for 2-4 days and then starts disconnecting devices or running slowly from time to time.
I currently “solve” this problem by stopping Z2M, then turning off MR3 (I use POE), and then reversing the process.
 
I don't know and am not 100% sure that it's Z2M; perhaps it's the controller/firmware. I think that, at least in my case, it's a combination of software/firmware and Wi-Fi interference, even if they don't overlap much (Wi-Fi 1,3,6. ZB: 25).

I'm tired of debugging the ZB network. It takes a lot of time and effort, both mine and, more importantly, it annoys my wife. Every day, it becomes more difficult for me to explain to her that it's a bug in the software/firmware. 🤣

**Comment by jesusgcas** [comment]
For me going back to coordinator OS version 2.3.6 fixed all the problems and now I can use zigbee2mqtt last version without issues. I've been on the same zigbee firmware all the time (20240710). SLZB-06

**Comment by davidrpfarinha** [comment]
> For me going back to coordinator OS version 2.3.6 fixed all the problems and now I can use zigbee2mqtt last version without issues. I've been on the same zigbee firmware all the time (20240710). SLZB-06

Might give it a try to downgrade my coordinator OS version. 
Currently, I'm on v3.1.3, but might try to update to v3.2.4 before downgrading.

Anyone on both GA for the SLZB-06 OS and Z2M, and working fine?

**Comment by iFormatrix1** [comment]
Hey everyone,

I had the same problem and every few hours devices—mainly Zigbee gateways—would drop out of the network. After disconnecting them from the power supply, the affected devices reconnected.

I use Home Assistant OS on Generic x86-64.
Core: 2026.1.3
Supervisor: 2026.02.1
Operating System: 17.0
Mosquitto broker: 6.5.2
Zigbee2MQTT: 2.8.0-1
Zigbee Router: 22
End devices: 29


I have also been experiencing outages since around November.

I had already tested the following:
- WLAN channel optimization to the Zigbee channel
- Sonoff Dongle P firmware update from 20210708? to 20250321
- Migration from Sonoff Dongle P to SMLIGHT SLZB-06P10
- Firmware update of the SMLIGHT SLZB-06P10 to Zigbee Coordinator: 20240716, Core: v3.2.4
- Direct connection of the mainly affected devices to the nearest Zigbee gateway
- Removal of the mainly affected devices from the Zigbee network
- Removal of old devices that are no longer actively in use from the network. For example, Fingerbot, whose battery had been empty for some time, was no longer in use, but was still in the network.

I use automation to notify me as soon as devices drop out of the network. Since this was happening every 3 hours or so, I took the time to completely rebuild my Zigbee network. In my environment – see above – it took me about 8 hours for the following:

- Filter the entity overview by “hidden” and group by “device,” then note the devices that have a changed device type.

- Check whether device names deviate from the standard designation that Home Assistant uses for entities—in my case, this was the case with ü instead of ue. Note the entity names in case of deviation.

- Take a screenshot of each device overview and save it with the currently assigned device name. The device model is also visible here.

- Home Assistant full backup

- Zigbee2MQTT backup

- Deactivate automations

- Stop Zigbee2MQTT add-on

- Stop MQTT broker add-on

- Change the IEEE address of the SMLIGHT SLZB-06P10 to the factory setting. Before that, I had a customized one, which I had taken over from the Sonoff Dongle P during migration.

- Uninstall Zigbee2MQTT add-on, including data deletion and repository removal

- Uninstall MQTT Broker add-on, including data deletion of the integration

- Delete the Zigbee2MQTT folder, if still present, /homeassistant/zigbee2mqtt

- Restart Home Assistant

- Install MQTT Broker add-on

- Add Zigbee2MQTT repository and install add-on

- Set up Zigbee2MQTT with further optimized Zigbee channel and connection to SMLIGHT SLZB-06P10

- Restart Home Assistant

- Teach all Zigbee routers. For each device, the model name from the screenshot taken in advance can be used to find out how to teach the device on the page https://www.zigbee2mqtt.io/supported-devices/. The device name can be taken from the name of the screenshot.

- Teach all end devices using the same principle as for the Zigbee routers.

- Change the entity names noted at the beginning to the previous ones - only if they differ from the device name

- Change the devices noted at the beginning if the device type differs.

- Check areas, labels, scenes, helper groups – all of mine have been retained by using the same names for devices and entities.

- Reactivate automations.

- Watchdog to check for missing entities in scripts and automations – this was not the case for me.


As I wrote before, I had devices that disconnected from the network every few hours.

 Since performing the steps above, my network has been running stably for 4 days without any outages.

**Comment by lavir** [comment]
> Hey everyone,
> 
> I had the same problem and every few hours devices—mainly Zigbee gateways—would drop out of the network. After disconnecting them from the power supply, the affected devices reconnected.
...
> 
> As I wrote before, I had devices that disconnected from the network every few hours.
> 
>  Since performing the steps above, my network has been running stably for 4 days without any outages.

Thanks for the info. I'm having the same issue, and after the latest Z2M and SLZB-MR3 software update, the ZB network is going down even more often than before.
That will take a lot of time (140+ devices in total) for me to repeat your steps. But I'll try, as I don't see a better solution.

Thank you!

**Comment by jesusgcas** [comment]
> > Hey everyone,
> > I had the same problem and every few hours devices—mainly Zigbee gateways—would drop out of the network. After disconnecting them from the power supply, the affected devices reconnected.
> > ...
> > As I wrote before, I had devices that disconnected from the network every few hours.
> >  Since performing the steps above, my network has been running stably for 4 days without any outages.
> 
> Thanks for the info. I'm having the same issue, and after the latest Z2M and SLZB-MR3 software update, the ZB network is going down even more often than before. That will take a lot of time (140+ devices in total) for me to repeat your steps. But I'll try, as I don't see a better solution.
> 
> Thank you!

My coordinator is the SLZB-06, so this may not help you but you can give it a try.

In my case I was having problems with the ZB network. Also updated to latest os firm and the problems got worse so I downgraded to  2.3.6. Its old but I havent had a problem ever since.

**Comment by jay-kub** [comment]
Is it possible to rollback Z2M when installed via the HA App? I tried the method in https://github.com/Koenkk/zigbee2mqtt/issues/29800#issuecomment-3581279937 but it looks like the folder structure is different, causing the restore to fail.

Edit: it's a bit janky but I figured it out.

1. Download the 2.6.3 release - https://github.com/Koenkk/zigbee2mqtt/releases/tag/2.6.3
2. Create your own public repo
3. Add the 2.6.3 release to your repo
4. In Home Assistant go to Settings > Apps > Install App > Three Dots > Repositories and add your repo
5. Install the Zigbee2MQTT app from your repo
6. Stop the old Zigbee2MQTT app
7. BACK UP YOUR DATA DIR
8. Start the new Zigbee2MQTT

**Comment by pannal** [comment]
Soooo. This might be a little off topic but could help some users:

I've had a router drop off the network recently (power relay). After reconnecting it, I've had serious random/intermittent delay issues with my lights both when triggered by sensors and when triggered by switches. I've had this years ago and back then had to re-pair some "badly behaving devices" (they don't show a connection on the zigbee map but just "float" there).
Sadly, this time, this didn't change anything.

Downgraded the coordinator, re-paired a bunch of devices, to no avail.

I then noticed while browsing Home Assistant, that one of my robot vacuums was dead (it died before reaching it's charging pad), and the Xiaomi integration showed an exclamation mark, while constantly retrying to connect to the dead robot, forever, every couple of seconds.

After fixing this, all delay issues are gone.

tl;dr: Check your HA integrations. Certain ones, if they fail, they fail constantly and it seems like they block the main HA thread while doing so, blocking the event handling (which seems like bad design). It feels exactly like a wonky zigbee network (bad LQI on routers).

**Comment by jay-kub** [comment]
This is still an active issue. @Koenkk, are you still waiting for the 10 hour logs you requested back in November? Please let us know what we can do to help here.

**Comment by Koenkk** [comment]
@jay-kub it would be nice to have the logs indeed, can you provide the logs on z2m 2.10.1 for 1 hour? (when the resource usage is high)

**Comment by jay-kub** [comment]
I've been running 2.10.1 for a couple weeks now with no issues. I'm very hopeful this is now resolved. My apologies for delaying the closure of this thread.

**Comment by t3ch-fr3ak** [comment]
> I've been running 2.10.1 for a couple weeks now with no issues. I'm very hopeful this is now resolved. My apologies for delaying the closure of this thread.

Thanks for the hint, jay-kub!
I have updated from version 2.6.2 to version 2.10.1 immediately after seeing your message on June 6th 08:05 pm. Since then, the new version is running without any issues. It even seems more responsive than the previous version.

**Comment by kambyte0** [comment]
Glad to see we finally have resolved (whatever it caused ;-)) issues here!
