### ISSUE TITLE
[Bug] Sinope TH1123ZB-G2 & TH1124ZB-G2 backlight auto dim off doesn't work

### ISSUE THREAD

**Issue by lemoinem** [Koenkk/zigbee2mqtt#29828]
### What happened?

When trying to set my TH1123ZB-G2 & TH1124ZB-G2 to backlight auto dim off, it remains as sensing. The off value simply doesn't work. I've tried both the UI and through Developer Tools, Actions.

### What did you expect to happen?

I expect the thermostat's backlight to remains ON at all time when backlight auto dim is set to off.

### How to reproduce it (minimal and precise)

1. Set a TH1123ZB-G2 or TH1124ZB-G2 to backlight auto dim off.
2. Turn off the light in the thermostat's room.
3. BUG: The display's backlight turns down.

### Zigbee2MQTT version

2.6.3 (unknown)

### Adapter firmware version

{"build":0,"ezsp":13,"major":7,"minor":4,"patch":5,"revision":"7.4.5 [GA]","special":0,"type":170}

### Adapter

EmberZNet

### Setup

os: `#1 SMP PREEMPT Tue Nov  4 14:31:07 UTC 2025 - 6.12.51-haos - arm64`
node: `v22.16.0`
ha: `true`

### Device `database.db` entry

I don't know how to find the database.db file

### Debug log

```
[25/11/2025, 22:54:22] zh:ember:uart:ash: <--- [FRAME type=DATA]
[25/11/2025, 22:54:22] zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=3](ackRx=3 frmTx=3)
[25/11/2025, 22:54:22] zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=3 frmNum=5](frmRx=5) Added to rxQueue
[25/11/2025, 22:54:22] zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=6](ackRx=3)
[25/11/2025, 22:54:22] zh:ember:ezsp: <=== [CBFRAME: ID=69:"INCOMING_MESSAGE_HANDLER" Seq=146 Len=38]
[25/11/2025, 22:54:22] zh:ember:ezsp: ezspIncomingMessageHandler: type=UNICAST apsFrame={"profileId":260,"clusterId":2820,"sourceEndpoint":1,"destinationEndpoint":1,"options":320,"groupId":0,"sequence":24} packetInfo:{"senderShortId":55946,"senderLongId":"0xFFFFFFFFFFFFFFFF","bindingIndex":255,"addressIndex":255,"lastHopLqi":255,"lastHopRssi":-27,"lastHopTimestamp":0} messageContents=18180a0b05293500080521d200
[25/11/2025, 22:54:22] zh:controller: Received payload: clusterID=2820, address=55946, groupID=0, endpoint=1, destinationEndpoint=1, wasBroadcast=false, linkQuality=255, frame={"header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":24,"commandIdentifier":10},"payload":[{"attrId":1291,"dataType":41,"attrData":53},{"attrId":1288,"dataType":33,"attrData":210}],"command":{"ID":10,"name":"report","parameters":[{"name":"attrId","type":33},{"name":"dataType","type":32},{"name":"attrData","type":1000}]}}
[25/11/2025, 22:54:22] z2m: Received Zigbee message from 'basement.office.thermostat', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":53,"rmsCurrent":210}' from endpoint 1 with groupID 0
[25/11/2025, 22:54:22] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/basement.office.thermostat', payload '{"backlight_auto_dim":"off","current":0.21,"enable_outdoor_temperature":null,"energy":null,"keypad_lockout":"unlock","linkquality":255,"local_temperature":19.2,"main_cycle_output":"15_sec","occupied_heating_setpoint":19,"outdoor_temperature_timeout":7200,"pi_heating_demand":20,"power":53,"running_state":"heat","second_display_mode":"auto","system_mode":"heat","temperature_display_mode":null,"thermostat_occupancy":null,"thermostat_outdoor_temperature":3,"time_format":"12h","voltage":null}'
```

#### Last health check
time: `Tue Nov 25 2025 23:27:52 GMT-0500 (Eastern Standard Time)`
os.load_average: `0, 0.02, 0.05`
os.memory_percent: `24.9177`
process.memory_percent: `2.722`
process.uptime_sec: `1811`

**Comment by lemoinem** [comment]
The issue seems to be that the codes for sensing and off are reversed. Setting the backlight to `sensing` actually gives the off behavior.

I'll check if I can provide a PR later.

**Comment by nongagf** [comment]
@lemoinem  I believe the fix caused a regression for all other Sinope models with auto-dimming. The TH1320ZB-04 for example only has `on_demand` and `sensing` (no `off` option).
I get this error when trying to set backlight_auto_dim to `sensing`:

`z2m: Publish 'set' 'backlight_auto_dim' to 'plancher_sdb' failed: 'Error: ZCL command 0x500b91400006650f/1 hvacThermostat.write({"SinopeBacklight":2}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"manufacturerCode":4508,"writeUndiv":false}) failed (Status 'INVALID_VALUE')'`

**Comment by scoulombe79** [comment]
Same regression here since the last upgrade...

`z2m: Publish 'set' 'backlight_auto_dim' to 'Thermostat (office)' failed: 'Error: ZCL command 0x500b91400001c6dd/1 hvacThermostat.write({"SinopeBacklight":2}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"manufacturerCode":4508,"writeUndiv":false}) failed (Status 'INVALID_VALUE')'`

**Comment by lemoinem** [comment]
Uh. Sorry about that.

I'll try to prepare a PR to revert my change and offer a better fix in the
next few days.

Would you be able to test it?
Since I don't have the devices, I can't test it myself.

**Comment by nongagf** [comment]
I won't be home to test until mid-January. But I was able to force-set `{"SinopeBacklight":1}` in the Dev Console and can confirm that the auto-dimming now behaves like it should in `sensing` mode (always on, auto-adjusting intensity).

**Comment by xetalx** [comment]
Exact same issue here. I cannot fall back to sensing anymore on the TH1300ZB. Note that some thermostats have 3 toggles and some other have only two. Example : 

<img width="356" height="89" alt="Image" src="https://github.com/user-attachments/assets/e54f3716-51bf-4bea-bf66-c95afadd0273" />
<img width="367" height="83" alt="Image" src="https://github.com/user-attachments/assets/2c4257a7-5c27-4f88-b335-a2822a3ead0e" />

The ones with only two options are broken now and cannot go back to "sensing".

**Comment by xetalx** [comment]
> Uh. Sorry about that.
> 
> I'll try to prepare a PR to revert my change and offer a better fix in the
> next few days.
> 
> Would you be able to test it?
> Since I don't have the devices, I can't test it myself.
> […](#)


> Uh. Sorry about that.
> 
> I'll try to prepare a PR to revert my change and offer a better fix in the
> next few days.
> 
> Would you be able to test it?
> Since I don't have the devices, I can't test it myself.
> […](#)

If you revert the change it will test it for you no issues at all before.

So you know, since this change i have 3 thermostats with dim screens and i cannot put them back to sensing.

Merci beaucoup !

**Comment by lemoinem** [comment]
Hey everyone,

I'm so sorry for breaking all your configs. I have sent https://github.com/Koenkk/zigbee-herdsman-converters/pull/11236 in order to revert my change.

I'll try to setup a new fix when time permits and will request feedback here once the fix is ready so it can be properly tested with your devices.

If you have been affected by the change (either positively or negatively) and would like to test the new fix, please keep an eye on this issue.

**Comment by lemoinem** [comment]
@Koenkk I'm trying to find a way to implement a better fix for this.
Essentially, I'm thinking into providing some options/parameter to `fzLocal.thermostat` and `tzLocal.backlight_autodim` so I can pick which version of the enum to use. Then I could adjust the -G2 thermostats (and those only) so they use the new enum.

If other devices need to switch device (based on community feedback), I'll address that as separate PRs if needed, I guess. Or it should be easier for other contributors/users to submit such PRs themselves. But at least I won't break everyone's device again (I want to renew my apologies for that by the way, both to you and the community at large).

`tzLocal.backlight_autodim` is easy-ish, because I can just have a separate converter `backlight_autodim2` or something. Although I'd prefer a similar approach for both tz and fz converters. Seems easier to follow what's happening.

But the the `fzLocal` seems harder to me. There are the `meta` and `options` parameters, but I'm not sure where the data in there come from and whether I could use it. But it feels like the best avenue.

I don't know if I could convert it into a factory closure? It seems overkill and could impact a lot of devices.
Splitting away the common part and having two separate `fzLocal` seems a tad difficult to do. It doesn't seem to be designed for modularity.

I'm looking for advice and open to suggestions on how to implement this the cleaner way, essentially. Especially since I can't really test the code with my setup, I'd like to minimize back-and-forth.

**Comment by Koenkk** [comment]
You can use a meta option for this, example:
- https://github.com/Koenkk/zigbee-herdsman-converters/blob/90ea42a8815357c83ad69c6c228f5bfb030ae2c9/src/converters/toZigbee.ts#L86
- https://github.com/Koenkk/zigbee-herdsman-converters/blob/90ea42a8815357c83ad69c6c228f5bfb030ae2c9/src/devices/woox.ts#L30

**Comment by lemoinem** [comment]
@xetalx , @nongagf, @scoulombe79:
https://github.com/Koenkk/zigbee-herdsman-converters/pull/11454 has just been merged and should solve my issue without creating new ones for you.

The new fix should be available in z2m Edge by now. Please let me know if I have inadvertently broken something else.

@ichabot609: I see you submitted https://github.com/Koenkk/zigbee-herdsman-converters/pull/11283, I'm afraid that since I reverted my initial commit with https://github.com/Koenkk/zigbee-herdsman-converters/pull/11236, your PR will actually create more issues than it solved in the long run (including for you). You might have to revert yours. My apologies.

I'll install z2m Edge myself in the next few days. And if that solves my issue and keeps everyone else happy, I'll close this case.

**Comment by lemoinem** [comment]
Just wanted to mention that I have tested the latest Z2M Edge and this is working great for me.

I'll wait for a few weeks after the next Z2M release to make sure this isn't creating trouble for anyone else, then I'll close the issue.

**Comment by jsrich31** [comment]
I am presently running into this issue as well. My display screen was set to on demand when the problem occured and I have not been able to turn it off since. 

<img width="349" height="168" alt="Image" src="https://github.com/user-attachments/assets/aea71aff-494a-414c-94f8-cc4d93678aec" />

z2m: Publish 'set' 'backlight_auto_dim' to 'Boys Room' failed: 'Error: ZCL command 0x500b914000022c75/1 hvacThermostat.write({"SinopeBacklight":2}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"manufacturerCode":4508,"writeUndiv":false}) failed (Status 'INVALID_VALUE')'

<img width="2655" height="828" alt="Image" src="https://github.com/user-attachments/assets/4a95367e-8656-4390-9a07-6fdcb38152ca" />

<img width="946" height="851" alt="Image" src="https://github.com/user-attachments/assets/a2f03e99-0db5-4861-b638-c9a821fc2c1a" />


This was tested with the latest version of Edge

**Comment by lemoinem** [comment]
@jsrich31: This is probably caused by @ichabot609's patch (https://github.com/Koenkk/zigbee-herdsman-converters/pull/11283).

Since I have no way of testing the fix and it would be bad form to revert their changes without their feedback/input, I'll wait a few more days to give them a chance to reply/confirm/test this. It's been merely a week since I posted my message to them.

If they don't answer by, say, Feb 20, I might go ahead and submit a PR to revert their patch. I'll poke you if/when I do so.

**Comment by jsrich31** [comment]
Did you get the response you were waiting for? I tried to install the
latest version of Edge, but I am running into the same issue. I have
automation that turns these displays on and off in the bedrooms at night
and back on in the morning. I would love to use that feature again.

Thanks in advance.
Jermaine

**Comment by lemoinem** [comment]
@jsrich31 No, I didn't hear back from @ichabot609, sadly. So I've submitted https://github.com/Koenkk/zigbee-herdsman-converters/pull/11581 to revert their patch.

Please let me know as soon as you can test it whether it solves your issue or if we need to find a better fix.

I feel you, I have a similar automation on some of my G2's, that's how I noticed my original issue to begin with. So sorry I broke it for everyone else.

**Comment by lemoinem** [comment]
@jsrich31 The revert has been merged. I'd say give it a few days, try to update Z2M, and let me know if that solved your issue 🤞

**Comment by jsrich31** [comment]
I will follow up at the end of the week.

**Comment by darkalfx** [comment]
I've just downloaded 2.9.0 and unfortunately I'm not seeing any changes on my TH1123ZB-G2 thermostats.

I've tried on firmware versions:
- 1027
- 1305

Instead of the getting the expected behavior this is what happens:
```
Off == Auto Sensing
Auto Sensing == Off
On Demand == On Demand
```

Was I supposed to remove and add the devices for the fix to take effects?

**Comment by lemoinem** [comment]
@darkalfx Sorry for the delay.

The fix works for me right away, only needed to update & restart Z2M. Maybe restart the hub, then the buttons start doing the right thing.
My G2 devices have firmware 1305. Both 23 and 24.

Is the behavior you have new with my fixes or is it something you had previously already (as in Nov 2025 and before)?

@jsrich31 How about the issue for the G1, is it solved?

**Comment by jsrich31** [comment]
Yes the issue is resolved. I was tagged to two open issuses and gave more
details there. I am grateful that you have all mange to correct the problem.

Cheers,
Jermaine.

**Comment by darkalfx** [comment]
@lemoinem 

Hello! 

I updated to 2.9.1, rebooted Z2M along with the hub, and I'm still getting the same behaviour as described in my last post.

I added those thermostats a long time ago on a much older version of Z2M, I believe at the time only `Sensing` and `On Demand` were even available as an option for G2 thermostat.

I updated Z2M somewhat recently and since then I've been having issues since `Sensing` now turns off the display on my thermostats, I ended up remapping them in my integration as a workaround but its not ideal.

Was I supposed to remove the thermostats and re-add in Z2M? 
Is there a possibility of something being cached preventing it from working?

Thanks again for all the help.

**Comment by lemoinem** [comment]
@darkalfx

Well, "Sensing" is supposed to turn off the display on the thermostat unless there is enough ambient light.
"On demand" is supposed to turn off the display unless one of the physical buttons is pushed. (And re-dim it again after a few seconds).
"Off" (which is "Auto-dimming is Off") will keep the display bright all the time.

Is this what you are seeing?

**Comment by darkalfx** [comment]
@lemoinem 

Yes it is what I'm actually seeing.

I guess it was confusing because when I first setup the G2 thermostats on the old version of Z2M, the `Sensing` option behaved like the new `Off` option, so when I updated some of my thermostat screens started to turn off. 

But from your post it seems like it's intended behavior, so I guess everything works then.

Thanks again for all the help!

**Comment by lemoinem** [comment]
Well, I'm glad it's all working as intended, but sorry it's causing you grief and you had to adjust all your settings and automations.

I think I'll be closing this case now, since everything seems to have been resolved.
