### ISSUE TITLE
[ConBee III] Aqara Smoke Detector (JY-GZ-01AQ) not updating infos

### ISSUE THREAD

**Issue by msnjdev** [Koenkk/zigbee2mqtt#29880]
### What happened?

I've a Conbee III with the latest firmware and Z2M latest version. I've also an Aqara smoke detector in my room (JY-GZ-01AQ) which is connected with Z2M. Sadly, when the alarm goes off (device detected smoke), the smoke detection is still on "false" in Z2M. I need to manually update the information with the sync button in order to update that state (it also happens with other informations like manually mute etc.)

### What did you expect to happen?

When the alarm goes off, the information on Z2M (and also on Homeassistant) should be automatically be updated.

### How to reproduce it (minimal and precise)

- Have a Conbee III
- Use Aqara JY-GZ-01AQ
- Have it paired with Z2M
- Try to fill the sensor with smoke
- Let the alarm go off
- The information should change now on Z2M, but doesn't.

### Zigbee2MQTT version

2.6.3

### Adapter firmware version

26550900

### Adapter

Conbee III

### Setup

Z2M inside a Docker container.

### Debug log

```
[11/28/2025, 10:47:17 PM] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/0x54ef4410012b890e', payload '{"battery":81,"buzzer":null,"buzzer_manual_alarm":false,"buzzer_manual_mute":false,"heartbeat_indicator":false,"last_seen":"2025-11-28T22:47:17+01:00","linkage_alarm":true,"linkage_alarm_state":null,"linkquality":248,"power_outage_count":null,"selftest":null,"smoke":false,"smoke_density":0,"smoke_density_dbm":0,"test":null,"update":{"installed_version":19,"latest_version":21,"state":"available"},"voltage":2900}'
[11/28/2025, 10:47:48 PM] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/0x54ef4410012b890e', payload '{"battery":81,"buzzer":null,"buzzer_manual_alarm":false,"buzzer_manual_mute":false,"heartbeat_indicator":false,"last_seen":"2025-11-28T22:47:48+01:00","linkage_alarm":true,"linkage_alarm_state":null,"linkquality":248,"power_outage_count":null,"selftest":null,"smoke":false,"smoke_density":0,"smoke_density_dbm":0,"test":null,"update":{"installed_version":19,"latest_version":21,"state":"available"},"voltage":2900}'
[11/28/2025, 10:47:48 PM] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/0x54ef4410012b890e', payload '{"battery":81,"buzzer":null,"buzzer_manual_alarm":false,"buzzer_manual_mute":false,"heartbeat_indicator":false,"last_seen":"2025-11-28T22:47:48+01:00","linkage_alarm":true,"linkage_alarm_state":null,"linkquality":252,"power_outage_count":null,"selftest":null,"smoke":false,"smoke_density":0,"smoke_density_dbm":0,"test":null,"update":{"installed_version":19,"latest_version":21,"state":"available"},"voltage":2900}'
[11/28/2025, 10:49:27 PM] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/0x54ef4410012b890e', payload '{"battery":81,"buzzer":null,"buzzer_manual_alarm":false,"buzzer_manual_mute":false,"heartbeat_indicator":false,"last_seen":"2025-11-28T22:49:27+01:00","linkage_alarm":true,"linkage_alarm_state":null,"linkquality":232,"power_outage_count":null,"selftest":null,"smoke":false,"smoke_density":0,"smoke_density_dbm":0,"test":null,"update":{"installed_version":19,"latest_version":21,"state":"available"},"voltage":2900}'
[11/28/2025, 10:49:27 PM] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/0x54ef4410012b890e', payload '{"battery":81,"buzzer":null,"buzzer_manual_alarm":false,"buzzer_manual_mute":false,"heartbeat_indicator":false,"last_seen":"2025-11-28T22:49:27+01:00","linkage_alarm":true,"linkage_alarm_state":null,"linkquality":236,"power_outage_count":null,"selftest":null,"smoke":false,"smoke_density":0,"smoke_density_dbm":0,"test":null,"update":{"installed_version":19,"latest_version":21,"state":"available"},"voltage":2900}'
[11/28/2025, 10:50:00 PM] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/0x54ef4410012b890e', payload '{"battery":81,"buzzer":null,"buzzer_manual_alarm":false,"buzzer_manual_mute":false,"heartbeat_indicator":false,"last_seen":"2025-11-28T22:50:00+01:00","linkage_alarm":true,"linkage_alarm_state":null,"linkquality":232,"power_outage_count":null,"selftest":null,"smoke":false,"smoke_density":0,"smoke_density_dbm":0,"test":null,"update":{"installed_version":19,"latest_version":21,"state":"available"},"voltage":2900}'
[11/28/2025, 10:50:00 PM] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/0x54ef4410012b890e', payload '{"battery":81,"buzzer":null,"buzzer_manual_alarm":false,"buzzer_manual_mute":false,"heartbeat_indicator":false,"last_seen":"2025-11-28T22:50:00+01:00","linkage_alarm":true,"linkage_alarm_state":null,"linkquality":228,"power_outage_count":null,"selftest":null,"smoke":false,"smoke_density":0,"smoke_density_dbm":0,"test":null,"update":{"installed_version":19,"latest_version":21,"state":"available"},"voltage":2900}'
[11/28/2025, 10:50:25 PM] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/0x54ef4410012b890e', payload '{"battery":81,"buzzer":null,"buzzer_manual_alarm":false,"buzzer_manual_mute":false,"heartbeat_indicator":false,"last_seen":"2025-11-28T22:50:25+01:00","linkage_alarm":true,"linkage_alarm_state":null,"linkquality":252,"power_outage_count":null,"selftest":null,"smoke":false,"smoke_density":0,"smoke_density_dbm":0,"test":null,"update":{"installed_version":19,"latest_version":21,"state":"available"},"voltage":2900}'
```

Those logs are mixed with "before" and "after" the alarm goes off. As you see, nothing changed.

### Notes

I tried to upgrade the firmware on the devices, but it didn't help.

**Comment by Nerivec** [comment]
Can you provide a `debug` log?
https://www.zigbee2mqtt.io/guide/configuration/logging.html#debugging
We need to see if the device is actually sending anything to let us know that e.g. "the alarm went off".

**Comment by mrmaximas** [comment]
@Nerivec FYI https://github.com/Koenkk/zigbee-OTA/pull/897 Perhaps you can help us with something.
The Z2M release will be out tonight, hundreds or thousands of TRVs may be broken.

**Comment by msnjdev** [comment]
> [@Nerivec](https://github.com/Nerivec) FYI [Koenkk/zigbee-OTA#897](https://github.com/Koenkk/zigbee-OTA/pull/897) Perhaps you can help us with something. The Z2M release will be out tonight, hundreds or thousands of TRVs may be broken.

@mrmaximas I wish it was the corrupted update. But it isn't. I have a second smoke detector with version 19, which also makes the issue with not reporting the correct state to Z2M.

**Comment by mrmaximas** [comment]
@msnjdev Have you tried zigbee traffic sniffing? It's the best diagnostic method.

**Comment by msnjdev** [comment]
No, never tried. But maybe I should also check with the deCONZ Software if the state is overall given to my Coordinator.

**Comment by mrmaximas** [comment]
@msnjdev Have you tried to re-configure sensor?

**Comment by msnjdev** [comment]
> Can you provide a `debug` log? https://www.zigbee2mqtt.io/guide/configuration/logging.html#debugging We need to see if the device is actually sending anything to let us know that e.g. "the alarm went off".

@Nerivec 
Above in the first message there is the debug log (yeah, the config file is set to "debug"). It is mixed with logs "before the alarm" and "after the alarm". I copied it from the WebUI log console.
As you see, the states are the same.
Let me know if you need something different.

I also made a MQTT request to `zigbee2mqtt/AQARASMOKEDETECTOR/get` with the following payload:
```
{
  "smoke": "",
  "smoke_density": "",
  "smoke_density_dbm": "",
  "linkage_alarm": "",
  "buzzer_manual_alarm": "",
  "buzzer_manual_mute": "",
  "heartbeat_indicator": ""
}
```
After sending this, the states gets reloaded in Z2M. But I need to still send this request to get an update (manual polling).

**Comment by msnjdev** [comment]
> [@msnjdev](https://github.com/msnjdev) Have you tried to re-configure sensor?

@mrmaximas yes. I did everything. Also to create a binding, which didn't help, except that when pressing the button on the sensor, it sends something in the logs (see above, the content is the same).

**Comment by mrmaximas** [comment]
@msnjdev When this sensor is asleep, it make `Data Request`s from the parent every 15 seconds. 
After waking up, it requests data once per second for several minutes.

**Comment by msnjdev** [comment]
> [@msnjdev](https://github.com/msnjdev) When this sensor is asleep, it make `Data Request`s from the parent every 15 seconds. After waking up, it requests data once per second for several minutes.

@mrmaximas I will try to sniff my Conbee. Sniffing on windows doesn't work with Zshark lol (ZShark crashes). I will switch to linux and post later my results here.

**Comment by mrmaximas** [comment]
@msnjdev I'm still using cc2531 under MacOS, waiting for NRF52840-DONGLE on the way.

**Comment by Nerivec** [comment]
@msnjdev we need the `debug` log from the file. The frontend does not have `debug` level logs due to the load that creates (unless specifically enabled).

@mrmaximas Koenkk will take a look. _The device is not enabled for ota in release branch yet from what I glanced._

**Comment by mrmaximas** [comment]
@Nerivec 🙏🏻

**Comment by msnjdev** [comment]
> [@msnjdev](https://github.com/msnjdev) we need the `debug` log from the file. The frontend does not have `debug` level logs due to the load that creates (unless specifically enabled).
> 
> [@mrmaximas](https://github.com/mrmaximas) Koenkk will take a look. _The device is not enabled for ota in release branch yet from what I glanced._

@Nerivec 
Alr, here is the whole file. I edited the file with my comments when the alarm was going off and when the pairing part was.
The ID of the sensor is `0x54ef4410012b890e` (MQTT Topic: `zigbee2mqtt/0x54ef4410012b890e`)

You can search in the file for the following texts:
`Everything BEFORE here was the pairing part.`
`The sensor was here filled with smoke and the alarm was going off`
`Manual State reload in Z2M` - In this part, the "alarm" state was manually reloaded in Z2M.

I know there are a lot of different sensors (like the airqualitysensor) inside, but I want to make sure you have everything you need.

[log.log](https://github.com/user-attachments/files/23839379/log.log)

Edit: Yeah, I paired my smoke detector again for the logs. So you see what happens while pairing.

**Comment by msnjdev** [comment]
FYI @mrmaximas 
I can't sadly sniff my Conbee the usual way. The tool "Zshark" hangs up on my computer (i dunno why).
I know there are some workarounds, but I don't have the time rn.

**Comment by Nerivec** [comment]
Looks like a converter problem from the logs. I'm guessing this is the alarm reporting:
```
[30.11.2025 13:02:56] debug: 	z2m: Received Zigbee message from '0x54ef4410012b890e', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":1}' from endpoint 1 with groupID 0
[30.11.2025 13:02:56] debug: 	z2m: No converter available for 'JY-GZ-01AQ' with cluster 'ssIasZone' and type 'commandStatusChangeNotification' and data '{"extendedstatus":0,"zonestatus":1}'
```

@mrmaximas you have that device and no problem? different firmware maybe?

**Comment by mrmaximas** [comment]
@Nerivec I broke my four sensors with the firmware update 21 https://github.com/Koenkk/zigbee-OTA/pull/897

**Comment by msnjdev** [comment]
> [@Nerivec](https://github.com/Nerivec) I broke my four sensors with the firmware update 21 [Koenkk/zigbee-OTA#897](https://github.com/Koenkk/zigbee-OTA/pull/897)

@mrmaximas I guess the update shouldn't change the function of reporting the state to Z2M. Try it and let us know, if your alarm state in Z2M gets updated when one detector goes off.

Edit: My guess is, that it has something to do with the Coordinator. He has a Sonoff and I've a Conbee III.

**Comment by mrmaximas** [comment]
@msnjdev  1. The buzzer sounds once, the buzz stops sounding, sensor flashes red some minutes.
2. The alarm message is sent to z2m once and does not reappear when smoke hits the sensor 10-20-60 seconds after the first alarm. 
It's very bad behavior.
Please check the sniff file.

[smoke.alarm.pcapng.zip](https://github.com/user-attachments/files/23839975/smoke.alarm.pcapng.zip)

**Comment by msnjdev** [comment]
> [@msnjdev](https://github.com/msnjdev) 1. The buzzer sounds once, the buzz stops sounding, sensor flashes red some minutes. 2. The alarm message is sent to z2m once and does not reappear when smoke hits the sensor 10-20-60 seconds after the first alarm. It's very bad behavior. Please check the sniff file.
> 
> [smoke.alarm.pcapng.zip](https://github.com/user-attachments/files/23839975/smoke.alarm.pcapng.zip)

@mrmaximas so in Z2M it sets the alarm state (automatically!) to true?
The buzzer issue is another issue, but for now, it is important to know if Z2M does change the state for smoke automatically (!) to true.

**Comment by mrmaximas** [comment]
@msnjdev my sensors status changes to smoke = true automatically but does not change to false when the smoke disappears.
I just smogged the sensor with smoke from a smoldering paper napkin for a minute. For the next few minutes, the sensor will be in this state in z2m

```
{
    "battery": 99,
    "buzzer_manual_alarm": false,
    "buzzer_manual_mute": true,
    "heartbeat_indicator": false,
    "last_seen": "2025-11-30T17:14:51+03:00",
    "linkage_alarm": true,
    "linkage_alarm_state": true,
    "linkquality": 171,
    "power_outage_count": 42,
    "smoke": true,
    "smoke_density": 0,
    "smoke_density_dbm": 0,
    "test": false,
    "update": {
        "installed_version": 21,
        "latest_version": 21,
        "state": "idle"
    },
    "voltage": 2993
}
```

I'll wait for the status change and post a sniff.

**Comment by mrmaximas** [comment]
@msnjdev 

[alarm.true.false.pcapng.zip](https://github.com/user-attachments/files/23840093/alarm.true.false.pcapng.zip)

```
{
    "battery": 99,
    "buzzer_manual_alarm": false,
    "buzzer_manual_mute": false,
    "heartbeat_indicator": false,
    "last_seen": "2025-11-30T17:24:21+03:00",
    "linkage_alarm": true,
    "linkage_alarm_state": true,
    "linkquality": 171,
    "power_outage_count": 42,
    "smoke": false,
    "smoke_density": 0,
    "smoke_density_dbm": 0,
    "test": false,
    "update": {
        "installed_version": 21,
        "latest_version": 21,
        "state": "idle"
    },
    "voltage": 2993
}
```

**Comment by Nerivec** [comment]
Went back to the debug logs, I saw this (started before the "pairing" comment, so I missed it first time):
```
[30.11.2025 13:02:23] debug: 	zhc:lumi: JY-GZ-01AQ: Processed data into payload {"smoke":false}
[30.11.2025 13:02:24] debug: 	zhc:lumi: JY-GZ-01AQ: Processed data into payload {"smoke_density":0,"smoke_density_dbm":0}
[30.11.2025 13:02:25] debug: 	zhc:lumi: JY-GZ-01AQ: Processed data into payload {"heartbeat_indicator":false}
[30.11.2025 13:02:26] debug: 	zhc:lumi: JY-GZ-01AQ: Processed data into payload {"buzzer_manual_alarm":false}
[30.11.2025 13:02:28] debug: 	zhc:lumi: JY-GZ-01AQ: Processed data into payload {"buzzer_manual_mute":false}
[30.11.2025 13:02:29] debug: 	zhc:lumi: JY-GZ-01AQ: Processed data into payload {"linkage_alarm":true}
[...]
[30.11.2025 13:03:08] debug: 	zhc:lumi: JY-GZ-01AQ: Processed data into payload {"smoke":true}
```
And that last line does result in a publish:
```json
{"battery":62,"buzzer":null,"buzzer_manual_alarm":false,"buzzer_manual_mute":false,"heartbeat_indicator":false,"last_seen":"2025-11-30T13:03:08+01:00","linkage_alarm":true,"linkage_alarm_state":null,"linkquality":224,"power_outage_count":null,"selftest":null,"smoke":true,"smoke_density":0,"smoke_density_dbm":0,"test":null,"update":{"installed_version":-1,"latest_version":-1,"state":null},"voltage":2800}
```
As for the interview, in case it's relevant, I see this:
```
{"modelId":"lumi.sensor_smoke.acn03"}
{"manufacturerName":"LUMI"}
{"appVersion":19}
{"dateCode":"20230310"}
{"swBuildId":"2019\u0000www."}
```

**Comment by msnjdev** [comment]
> [@msnjdev](https://github.com/msnjdev) my sensors status changes to smoke = true automatically but does not change to false when the smoke disappears. I just smogged the sensor with smoke from a smoldering paper napkin for a minute. For the next few minutes, the sensor will be in this state in z2m
> 
> ```
> {
>     "battery": 99,
>     "buzzer_manual_alarm": false,
>     "buzzer_manual_mute": true,
>     "heartbeat_indicator": false,
>     "last_seen": "2025-11-30T17:14:51+03:00",
>     "linkage_alarm": true,
>     "linkage_alarm_state": true,
>     "linkquality": 171,
>     "power_outage_count": 42,
>     "smoke": true,
>     "smoke_density": 0,
>     "smoke_density_dbm": 0,
>     "test": false,
>     "update": {
>         "installed_version": 21,
>         "latest_version": 21,
>         "state": "idle"
>     },
>     "voltage": 2993
> }
> ```
> 
> I'll wait for the status change and post a sniff.

@mrmaximas 
At least it changes for you to `true`. Mine doesn't change automatically at all.
What I know, is that the `smoke` state is when the alarm goes off (and the detector blinks red). When you quit the alarm manually on the device, the state should change to false. It is not a state, if smoke is present or not, it is a state if the detector has been going off or not. After a few minutes without smoke, the device itselfs quits the alarm.

@Nerivec I guess the problem is the coordinator. His coordinator is a Sonoff, mine is Conbee III. Maybe there are other guys with the same problem with a Conbee III. Do you think this is an issue of Z2M?

**Comment by Nerivec** [comment]
@msnjdev I'm not sure how that device works exactly, but [as mentioned](https://github.com/Koenkk/zigbee2mqtt/issues/29880#issuecomment-3592610311), the stuff is published by Z2M similar to mrmaximas (`{"smoke":true}`).

**Comment by mrmaximas** [comment]
@msnjdev Do you mean that if I press the button on the sensor after the alarm, it should immediately return the status `smoke = false`? Or if I press `Buzzer > mute` in z2m? Should I check this?

**Comment by mrmaximas** [comment]
@msnjdev next sniff. smoke for 30 sec > no smoke > button press for 3-5-7 then commands via z2m.
For some reason, I couldn't turn off the flashing LED with the button on the case, even when I pressed buzzer > mute.
Nothing changed the smoke state. It only changes when the flashing LED goes off (check in the prev sniff).

[alarm.true.then.button.then.z2m.buzzer.mute.pcapng.zip](https://github.com/user-attachments/files/23840291/alarm.true.then.button.then.z2m.buzzer.mute.pcapng.zip)
P.S. When I held the button down for a long time (5+ sec), the buzzer started to buzz continuously in combination with the LED continuing to blink. Maybe they (Aqara) changed the buzzer's behavior with the button on the body? Today, I can no longer conduct experiments because my family would kill me ;)

**Comment by msnjdev** [comment]
> [@msnjdev](https://github.com/msnjdev) I'm not sure how that device works exactly, but [as mentioned](https://github.com/Koenkk/zigbee2mqtt/issues/29880#issuecomment-3592610311), the stuff is published by Z2M similar to mrmaximas (`{"smoke":true}`).

@Nerivec 
My bad, didn't saw this message.
However, you missed my note: At that point, i manually reloaded the state in Z2M with the reload button.

<img width="892" height="323" alt="Image" src="https://github.com/user-attachments/assets/f4457744-7934-4d41-824c-f66c9adb3c40" />

Edit: You can also see how Z2M makes a MQTT Request to ".../get" with the payload `{"smoke": ""}` and then gets the correct state.

**Comment by msnjdev** [comment]
> [@msnjdev](https://github.com/msnjdev) Do you mean that if I press the button on the sensor after the alarm, it should immediately return the status `smoke = false`? Or if I press `Buzzer > mute` in z2m? Should I check this?

No, to quit the alarm on the device, you need to press the button on the device for a long time. IF smoke is still present, the alarm goes off again and if not, the device should stop blinking red and the state in Z2M should change back to "false".

Btw.: When trying to quit the alarm and the smoke is still present, my device than beeps normally (and not with the issue of one time beeps in v21). Kinda weird.

**Comment by mrmaximas** [comment]
> Btw.: When trying to quit the alarm and the smoke is still present, my device than beeps normally (and not with the issue of one time beeps in v21). Kinda weird.

That's exactly what I got in the last test. I couldn't turn off the LED, but the source of the smoke had already been suppressed. At the same time, I was also able to make the buzzer work continuously - 3 buzz then 1s pause.

**Comment by msnjdev** [comment]
> [@msnjdev](https://github.com/msnjdev) next sniff. smoke for 30 sec > no smoke > button press for 3-5-7 then commands via z2m. For some reason, I couldn't turn off the flashing LED with the button on the case, even when I pressed buzzer > mute. Nothing changed the smoke state. It only changes when the flashing LED goes off (check in the prev sniff).
> 
> [alarm.true.then.button.then.z2m.buzzer.mute.pcapng.zip](https://github.com/user-attachments/files/23840291/alarm.true.then.button.then.z2m.buzzer.mute.pcapng.zip) P.S. When I held the button down for a long time (5+ sec), the buzzer started to buzz continuously in combination with the LED continuing to blink. Maybe they (Aqara) changed the buzzer's behavior with the button on the body? Today, I can no longer conduct experiments because my family would kill me ;)

Just to make sure, that you know how the device works:
When alarm goes off: `smoke` changes to true in Z2M, buzzer should start and the button should blink red on the device.

When you mute the alarm: Buzzer stops, button still blinks red and state in Z2M still `true`.

When smoke goes away: it takes a few minutes (maybe around 10 minutes) until it stops beeping and stops blinking red. And the state in Z2M changes back to `false` then.

When you press the button (5-10secs) while the alarm was going off: 
IF the smoke is still present: The buzzer starts again (if it was muted before) and the button still blinks red
IF the smoke is NOT anymore present: The buzzer stops (if not muted) and the blinking red light stops. The state in Z2M changes back to `false`

That's how the device should work.

**Comment by mrmaximas** [comment]
> That's how the device should work.

with not affected fw :)

**Comment by Nerivec** [comment]
@msnjdev can you post screenshots of the "bind" and "reporting" tabs for the device, so mrmaximas can compare?

**Comment by mrmaximas** [comment]
@Nerivec i have no binds and no reporting tabs configured.
`{"id":110,"type":"EndDevice","ieeeAddr":"0x54ef441000a39e12","nwkAddr":49453,"manufId":4447,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_smoke.acn03","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1280,3,1],"outClusterList":[25],"clusters":{"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b002a1aa3c4","zoneState":1}},"genBasic":{"attributes":{"modelId":"lumi.sensor_smoke.acn03","appVersion":21,"dateCode":"20230912","swBuildId":"2019\u0000www.","manufacturerName":"LUMI","powerSource":3,"zclVersion":3,"stackVersion":2,"hwVersion":1}},"genPowerCfg":{"attributes":{"batteryVoltage":30}},"manuSpecificLumi":{"attributes":{"247":{"type":"Buffer","data":[1,33,171,11,3,40,25,4,33,168,19,5,33,43,0,6,36,1,0,0,0,0,8,33,21,1,10,33,219,64,12,32,1,102,32,3,103,32,1,104,33,168,0,160,33,0,0,161,32,0,162,32,0,163,32,0,164,32,0,165,32,1]},"252":0,"294":0,"295":0,"314":0,"315":0,"316":0,"317":0,"331":1,"332":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":21,"stackVersion":2,"hwVersion":1,"dateCode":"20230912","swBuildId":"2019\u0000www.","zclVersion":3,"interviewCompleted":true,"interviewState":"SUCCESSFUL","meta":{"configured":332242049},"lastSeen":1764508017862,"checkinInterval":3600}`
A couple of days ago, I have binded the OTA and IAS clusters to the coordinator, thinking that this would help to rollback the firmware. Subsequently, I have removed this binds. By default (after configure or first interview), no bindings or reports are configured for this sensor.

**Comment by msnjdev** [comment]
> [@msnjdev](https://github.com/msnjdev) can you post screenshots of the "bind" and "reporting" tabs for the device, so mrmaximas can compare?

@Nerivec Same as @mrmaximas , no binding and reports are configured.
I tried to configure `ssIASzone` as binding to my Coordinator (Endpoint 242) without any luck. Btw.: When trying to add over the WebUI a binding to the Coordinator endpoint `242`, it will save as `1` instead of `242`. I found out, that Z2M sends a MQTT payload with the DST endpoint as `null`, which automatically chooses `1`. I needed to manually make a MQTT request, so it sets the endpoint to `242`.

And adding ANYTHING to the reportings-tab gets rejected with the error `UNSUPPORTED ATTRIBUTE` or something like that.

**Comment by Isusami** [comment]
I also have this issue(cannot update the device), is there any help I can do for debuggin?
My cordinatior is EZSP v13
and my MQQT run in docker.

**Comment by msnjdev** [comment]
> I also have this issue(cannot update the device), is there any help I can do for debuggin? My cordinatior is EZSP v13 and my MQQT run in docker.

@Isusami Do you have a problem with updating the smoke detector or with getting the newest state when the detector goes off?

**Comment by Isusami** [comment]
> @Isusami Do you have a problem with updating the smoke detector or with getting the newest state when the detector goes off?

I have update problem cannot update the smoke sensor they are on version 19.

**Comment by mrmaximas** [comment]
> I have update problem cannot update the smoke sensor they are on version 19.

@Isusami Hi! Do you have zigbee sniffer stick/dongle? 
**PLEASE DO NOT UPDATE FW to v21.**

**Comment by Isusami** [comment]
> @Isusami Hi! Do you have zigbee sniffer stick/dongle? 
> **PLEASE DO NOT UPDATE FW to v21.**

I have EZSP v13 dongle and assumed it's not a sniffer, is there anything to help?

Thanks for the note, I will keep this version until the issue is solved.

**Comment by mrmaximas** [comment]
> > [@Isusami](https://github.com/Isusami) Hi! Do you have zigbee sniffer stick/dongle?
> > **PLEASE DO NOT UPDATE FW to v21.**
> 
> I have EZSP v13 dongle and assumed it's not a sniffer, is there anything to help?
> 
> Thanks for the note, I will keep this version until the issue is solved.

Best choice - **original** NRF52840-DONGLE

**Comment by msnjdev** [comment]
@Isusami FYI: https://github.com/Koenkk/zigbee-OTA/pull/897
@mrmaximas I will try later today again sniffing with my Conbee III. I hope it works in any way. 
What I can add: with ZHA and Conbee III, the state doesn't reload there too. Maybe it is a Coordinator-Specific issue.

**Comment by msnjdev** [comment]
> I also have this issue(cannot update the device), is there any help I can do for debuggin? My cordinatior is EZSP v13 and my MQQT run in docker.

@Isusami does your Z2M update the alarm state when the detector goes off?

**Comment by mrmaximas** [comment]
@msnjdev I don't know anything about your Conbee III dongle, but my current TI СС2531 needed special sniffer firmware.

FYI https://community.silabs.com/s/article/turning-any-efr32-into-a-zigbee-or-thread-sniffer?language=en_US

**Comment by Isusami** [comment]
> > I also have this issue(cannot update the device), is there any help I can do for debuggin? My cordinatior is EZSP v13 and my MQQT run in docker.
> 
> @Isusami does your Z2M update the alarm state when the detector goes off?

Yes I test it now.

**Comment by msnjdev** [comment]
> > > I also have this issue(cannot update the device), is there any help I can do for debuggin? My cordinatior is EZSP v13 and my MQQT run in docker.
> > 
> > 
> > [@Isusami](https://github.com/Isusami) does your Z2M update the alarm state when the detector goes off?
> 
> Yes I test it now.
@Isusami alr thank you.

I will then buy another Coordinator, as this is the problem. Maybe I will consult them in the deCONZ forum about the issue with the Conbee 3.

Btw.: The sniffing tool doesn‘t work for ConBee 3, sadly…

**Comment by mrmaximas** [comment]
@msnjdev You need special sniffer firmware; a router or coordinator is not suitable for this purpose.

**Comment by msnjdev** [comment]
> [@msnjdev](https://github.com/msnjdev) You need special sniffer firmware; a router or coordinator is not suitable for this purpose.

@mrmaximas nah, deCONZ has a software called ‚ZShark‘ which you can use on a Conbee 1 or 2 to sniff with wireshark. Conbee 3 is rn not supported.

**Comment by mrmaximas** [comment]
@msnjdev ZShark this is FW not SW ☝🏻

**Comment by msnjdev** [comment]
> [@msnjdev](https://github.com/msnjdev) ZShark this is FW not SW ☝🏻

@mrmaximas it‘s both :)
SW for PC and FW for ConBee

**Comment by msnjdev** [comment]
Can confirm now: It is a Coordinator specific issue. 

I ordered a Sonoff ZBDongle-E (efr32mg21a020f768im32) and the issue is gone. The state gets updated when the alarm goes off. I will create an issue-task on deCONZ, so they can start an investigation.

**Comment by TAKeanice** [comment]
> I will create an issue-task on deCONZ, so they can start an investigation.

Was just about to buy the aquara smoke sensors, thanks for the warning on the documentation page. @msnjdev can you link the issue ticket you created with Dresden Electronic here, please?

**Comment by TAKeanice** [comment]
Also this sounds a lot like https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7962 , but as far as I understand that issue was supposed to be solved in April 2025

**Comment by bjornfor** [comment]
The issue title ("Aqara Smoke Detector (JY-GZ-01AQ) not updating infos") makes it sound like a generic issue, but it only manifests with deCONZ USB dongle, right? (I have 3 of the same smoke detectors, and they all work fine with my Sonoff Zigbee 3.0 USB Dongle Plus.) Update the title?

**Comment by msnjdev** [comment]
> > I will create an issue-task on deCONZ, so they can start an investigation.
> 
> Was just about to buy the aquara smoke sensors, thanks for the warning on the documentation page. [@msnjdev](https://github.com/msnjdev) can you link the issue ticket you created with Dresden Electronic here, please?

@TAKeanice Sorry, hadn't any time rn to make a new issue ticket and then i forgot to create one. I will make one today, if I get some time for me.



> The issue title ("Aqara Smoke Detector (JY-GZ-01AQ) not updating infos") makes it sound like a generic issue, but it only manifests with deCONZ USB dongle, right? (I have 3 of the same smoke detectors, and they all work fine.) Update the title?

@bjornfor done.

**Comment by TAKeanice** [comment]
> Sorry, hadn't any time rn to make a new issue ticket and then i forgot to create one.

Nvm, I know that issue far too well. 

I bought Aquara smoke sensors anyway, so I'd be even more happy to see the ticket link and then some action from Dresden Electronic, and hope you can find the time for creating it. 

As an incentive, I only have my gratitude to offer though, or a coffee and some talk if we ever meet irl.

**Comment by andrei-lazarov** [comment]
Hi. I didn't follow the thread, but regarding missing events / actions / state reportings:
**The router through which you pair the devices is very important.**

I can consistently fail pairing my IKEA STYRBAR remote (shows success, but Actions not reported) through a Tuya Telink bulb...
Power-off the bulb and pairing works immediately, 100% successful, all Actions reported.
Sometimes clicking the drop-down on Permit join and selecting coordinator is enough.

I consider Telink devices (IEEE adress starts with 0xa4c138) bad routers. Usually Tuya and Tuya re-brands, AwoX.
Switching to a more powerful coordinator may skip the bad router and solve the issue.

**Comment by TAKeanice** [comment]
I don't think this has been solved yet

**Comment by PHB-fra** [comment]
I migrate my conbee II to nabu casa zbt 2 and this problem is still present

**Comment by mamatdv** [comment]
Hi,
Have you got some news about this issue ? 
I have a conbee II and the problem are present

**Comment by msnjdev** [comment]
> Hi. I didn't follow the thread, but regarding missing events / actions / state reportings: **The router through which you pair the devices is very important.**
> 
> I can consistently fail pairing my IKEA STYRBAR remote (shows success, but Actions not reported) through a Tuya Telink bulb... Power-off the bulb and pairing works immediately, 100% successful, all Actions reported. Sometimes clicking the drop-down on Permit join and selecting coordinator is enough.
> 
> I consider Telink devices (IEEE adress starts with 0xa4c138) bad routers. Usually Tuya and Tuya re-brands, AwoX. Switching to a more powerful coordinator may skip the bad router and solve the issue.

Nah, I tried it to route it directly to my coordinator, without success. It is not an issue with the route, it is an issue with the Conbee III. I also use now a Sonoff ZBDongle-E (efr32mg21a020f768im32) and the issue has been resolved for me.



> I migrate my conbee II to nabu casa zbt 2 and this problem is still present

"Still present"? So, the Conbee II has this problem too?



> Hi, Have you got some news about this issue ? I have a conbee II and the problem are present

Nah sorry, didn't have time and forgot to contact the manufacturer. 
Quick fix would be to use another coordinator like Sonoff ZBDongle-E (efr32mg21a020f768im32) (can confirm, that it is working with this device).

**Comment by mtguido87** [comment]
Good evening,
I added the Aqara JY-GZ-01AQ sensor to Z2M using the SONOFF 3.0 USB Dongle Plus (TI CC2652P).
The sensor was added successfully. If I run a smoke test, it starts beeping, but the status on Z2M doesn't change. Also, if I try an OTA update, it fails.

Has anyone solved the problem? How?

Thanks!

**Comment by bjornfor** [comment]
> I added the Aqara JY-GZ-01AQ sensor to Z2M using the SONOFF 3.0 USB Dongle Plus (TI CC2652P).
The sensor was added successfully. If I run a smoke test, it starts beeping, but the status on Z2M doesn't change. Also, if I try an OTA update, it fails.

Try adding it again? If it's consistent, then it might be another class of problematic zigbee dongles?

About the firmware, I don't see any OTA available for them? I've never run it I think.... currently Z2M shows

```
Firmware ID: 2019www.
Firmware version: 20230310
```

Btw, I have no problems with Sonoff_Zigbee_3.0_USB_Dongle_Plus with EmberZNet 8.0.2 -- I have multiple of these smoke detectors and they are all working fine for 6+ months. I just did another successful selftest, currently on Z2M 2.12.0.

**Comment by mtguido87** [comment]
> > I added the Aqara JY-GZ-01AQ sensor to Z2M using the SONOFF 3.0 USB Dongle Plus (TI CC2652P).
> > The sensor was added successfully. If I run a smoke test, it starts beeping, but the status on Z2M doesn't change. Also, if I try an OTA update, it fails.
> 
> Try adding it again? If it's consistent, then it might be another class of problematic zigbee dongles?
> 
> About the firmware, I don't see any OTA available for them? I've never run it I think.... currently Z2M shows
> 
> ```
> Firmware ID: 2019www.
> Firmware version: 20230310
> ```
> 
> Btw, I have no problems with Sonoff_Zigbee_3.0_USB_Dongle_Plus with EmberZNet 8.0.2 -- I have multiple of these smoke detectors and they are all working fine for 6+ months. I just did another successful selftest, currently on Z2M 2.12.0.

I have Z2M 2.12.1 and same firmware you said on the smoke sensor. Don't know if your dongle is same as mine, mine is SONOFF 3.0 USB Dongle Plus (TI CC2652P).
Just tried to remove and add the smoke sensor again but same things. 
The strange is that if I launch a selftest from Z2M the smoke sensor ring...so it seems it comunicate correctly. But when the smoke sensor get smoke it ring but not change the value status on Z2M.

Nobody knows what should I do?

**Comment by bjornfor** [comment]
(I can only answer what I know, sorry.)

> Don't know if your dongle is same as mine, mine is SONOFF 3.0 USB Dongle Plus (TI CC2652P).

That's different from mine, which is this model: https://sonoff.tech/products/sonoff-zigbee-3-0-usb-dongle-plus-zbdongle-e. The "E" variant has Silabs chip, not Texas Instruments (TI). They run different firmware/zigbee stack.

**Comment by mtguido87** [comment]
> (I can only answer what I know, sorry.)
> 
> > Don't know if your dongle is same as mine, mine is SONOFF 3.0 USB Dongle Plus (TI CC2652P).
> 
> That's different from mine, which is this model: https://sonoff.tech/products/sonoff-zigbee-3-0-usb-dongle-plus-zbdongle-e. The "E" variant has Silabs chip, not Texas Instruments (TI). They run different firmware/zigbee stack.

Yes it is quite different, don't know if this could be the reason why not working to me.
Waiting if somebody could help me fixing it! Thanks!!

**Comment by msnjdev** [comment]
> > (I can only answer what I know, sorry.)
> > > Don't know if your dongle is same as mine, mine is SONOFF 3.0 USB Dongle Plus (TI CC2652P).
> > 
> > 
> > That's different from mine, which is this model: https://sonoff.tech/products/sonoff-zigbee-3-0-usb-dongle-plus-zbdongle-e. The "E" variant has Silabs chip, not Texas Instruments (TI). They run different firmware/zigbee stack.
> 
> Yes it is quite different, don't know if this could be the reason why not working to me. Waiting if somebody could help me fixing it! Thanks!!

Hi @mtguido87 

We couldn‘t solve it yet. My fix for this issue would be to use another dongle like the „Sonoff ZBDongle-E (efr32mg21a020f768im32)“. Can confirm that it works with this dongle. I had the same issue with the ConBee III.

Edit: It is the device which @bjornfor sent as a link.

**Comment by msnjdev** [comment]
@bjornfor and @mtguido87 
FYI because of the OTA question:
There are currently issues with the newest version of the devices (see https://github.com/Koenkk/zigbee-OTA/issues/938)

The OTA file has been retracted from Z2M. If you have any buzzering issues like the described in the issue above, please follow the instruction in the issue to revert the FW. 

I does NOT resolve the issue with the alarm state update, it only resolves the issue with ‚buzzering one time and then it stopps when going off‘. If you don‘t have this issue, then you don‘t need to do everything.

**Comment by msnjdev** [comment]
I see currently that the only protocol, which works with this smoke detector, is Ember. I had deCONZ and @mtguido87 had the TI Z-Stack. 

If anyone uses the smoke detector with Z-Stack OR deCONZ without any issues, please let me know. Maybe there is a protocol issue.

**Comment by mrmaximas** [comment]
@msnjdev i use four JY-GZ-01AQ reverted to fw 17 / 20220617 with the SLZB-06p7 / CC2652P7 fw 20250321 without any issues.

**Comment by mtguido87** [comment]
> [@msnjdev](https://github.com/msnjdev) i use four JY-GZ-01AQ reverted to fw 17 / 20220617 with the SLZB-06p7 / CC2652P7 fw 20250321 without any issues.

Could you please explain me how to revert to fw 17? I have actually Firmware ID: 2019www. Firmware version: 20230310

**Comment by mrmaximas** [comment]
@mtguido87 https://github.com/Koenkk/zigbee-OTA/issues/972#issuecomment-3706384016

**Comment by mtguido87** [comment]
> [@mtguido87](https://github.com/mtguido87) [Koenkk/zigbee-OTA#972 (comment)](https://github.com/Koenkk/zigbee-OTA/issues/972#issuecomment-3706384016)

Vuole you please explain here better? Can’t understand how to do

**Comment by mrmaximas** [comment]
@mtguido87 
1.  Add custom ota index to z2m. https://raw.githubusercontent.com/andrei-lazarov/zigbee-OTA/refs/heads/aqara/aqara.json

How to: https://www.zigbee2mqtt.io/guide/usage/ota_updates.html#using-custom-firmware-files-or-index

```
[
  {
    "fileName": "20220718113235_OTA_lumi.sensor_smoke.acn03_0.0.0_0017_20220617_CB9276.ota",
    "fileVersion": 22,
    "fileSize": 222094,
    "url": "https://raw.githubusercontent.com/andrei-lazarov/zigbee-OTA/aqara/images1/Lumi/20220718113235_OTA_lumi.sensor_smoke.acn03_0.0.0_0017_20220617_CB9276.ota",
    "imageType": 9728,
    "manufacturerCode": 4447,
    "sha512": "3f5279c0a40d75c3e6de8922b5bedbdcd416c8365d026ab4951ba04add761caf156c3b151ff29ec98c1e83f27ed93d95293922ee26a349256ba0f781649be0ee",
    "otaHeaderString": "OM15082-WIN-JN5180--ENCRYPTED000",
    "modelId": "lumi.sensor_smoke.acn03"
  }
]

```
2. Update fw for JY-GZ-01AQ

**Comment by mtguido87** [comment]
> [@mtguido87](https://github.com/mtguido87)
> 
> 1. Add custom ota index to z2m. https://raw.githubusercontent.com/andrei-lazarov/zigbee-OTA/refs/heads/aqara/aqara.json
> 
> How to: https://www.zigbee2mqtt.io/guide/usage/ota_updates.html#using-custom-firmware-files-or-index
> 
> ```
> [
>   {
>     "fileName": "20220718113235_OTA_lumi.sensor_smoke.acn03_0.0.0_0017_20220617_CB9276.ota",
>     "fileVersion": 22,
>     "fileSize": 222094,
>     "url": "https://raw.githubusercontent.com/andrei-lazarov/zigbee-OTA/aqara/images1/Lumi/20220718113235_OTA_lumi.sensor_smoke.acn03_0.0.0_0017_20220617_CB9276.ota",
>     "imageType": 9728,
>     "manufacturerCode": 4447,
>     "sha512": "3f5279c0a40d75c3e6de8922b5bedbdcd416c8365d026ab4951ba04add761caf156c3b151ff29ec98c1e83f27ed93d95293922ee26a349256ba0f781649be0ee",
>     "otaHeaderString": "OM15082-WIN-JN5180--ENCRYPTED000",
>     "modelId": "lumi.sensor_smoke.acn03"
>   }
> ]
> ```
> 
> 2. Update fw for JY-GZ-01AQ

I tried added two line to the configuration.yaml of z2m:

`ota: 
  zigbee_ota_override_index_location: my_index.json`

The create my_index.json in the same folder of the configuration.yaml and putted your code inside it.

Then try to ota update the device but it reply:

z2m: Failed to check if OTA update available for '0x54ef44100143aa43' (Device didn't respond to OTA request)

**Comment by mtguido87** [comment]
Made the update as @mrmaximas said but still not working :(

**Comment by PHB-fra** [comment]
It still isn't working; a manual interrogation is required to re-establish the connection with the dongle.
