### ISSUE TITLE
IKEA LED1623G12 - wrong brightness status after power ON

### ISSUE THREAD

**Issue by poki123** [Koenkk/zigbee2mqtt#4343]
Hello,

after "Power ON line" (with classic switch), the ikea bulb IKEA LED1623G12 report brightness as 0:

'{"brightness":**0**,"color_temp":366,"linkquality":254,"state":"**ON**","update_available":false}'

it restore to report olny after publishing the brightness change.

zigbee2mqtt@1.14.4

**Comment by sjorge** [comment]
I believe this got fixed in the dev branch

**Comment by poki123** [comment]
No, it wasn’t.
I have tried dev branch right now and issue persists.

**Comment by poki123** [comment]
Hello, now, with latest dev branch is everything working fine.
