### ISSUE TITLE
SEA801-Z01 Tuya TRV  Unknown device.

### ISSUE THREAD

**Issue by Ryanmt2** [Koenkk/zigbee2mqtt#5082]
## What happened
https://www.zigbee2mqtt.io/devices/SEA801-Zigbee.html

I have a TRV with the markings SEA801-Z01 that when paired is not identified by zigbee2mqtt

## What did you expect to happen

The device is listed as supported so I expected it to be discovered by home assistant.

## How to reproduce it (minimal and precise)

Pair the device.

## Debug info
Zigbee2MQTT version: 1.16.1 
Adapter hardware: CC2531
Adapter firmware version:  zStack12

```
Zigbee2MQTT:warn  2020-11-25 10:28:46: Received message from unsupported device with Zigbee model 'TS0601'
```
Model is reported as TS0601 by _TZE200_c88teujp.

- edit. just noticed this seems to be present in devices.js so need to check my local version. I suspect this may be fixed already

**Comment by Ryanmt2** [comment]
Closing, looks like I am behind the latest devices.js and this is already fixed

**Comment by seidler2547** [comment]
I got the same device today, and while I see the device in devices.js, it still doesn't work. Anything I am missing, or do I just need to wait until the change is released?

**Comment by Ryanmt2** [comment]
Depends, the has been supported for a while but there is an unreleased change for some different identifiers eg `_TZE200_c88teujp`

Here is the latest copy/changes
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L13513
