### ISSUE TITLE
Firmware version of Aqara SP-EUC01 not correctly updated after OTA

### ISSUE THREAD

**Issue by tabnul** [Koenkk/zigbee2mqtt#8526]
I bought a bunch of SP-EUC01 aqara plugs and not all of them where running the latest firmware.
Latest firmware: 09-22-2020
Firmware of some plugs: 09-10-2019

When i perform the OTA update via the GUI, it seems to pick the right new image;
`getNewImage for '0x04cf8cdf3c89dcc5', meta {"fileVersion":32,"fileSize":278094,"url":"https://github.com/Koenkk/zigbee-OTA/raw/master/images/Xiaomi/OTA_lumi.plug.maeu01_V32_20200922_C11F8A.20200924102946.ota","sha512":"e91499339cf5f247cf5496ad704207ce7862e7cf04adecac217e365a7ad1e0037f5932be9315e574ed112ab04eeb264cf2fde1367414c5a57c66ca9449919057"}`
>>>

completes the update:
```
Finished update of 'terra1_daylight'
Received Zigbee message from 'terra1_daylight', type 'readResponse', cluster 'genBasic', data '{"dateCode":"09-22-2020"}' from endpoint 1 with groupID 0
```

However, after the update, the firmware version in the GUI is not updated (stays 09-10-2019)
No new firmware detected, so i think this is a visual issue.
![image](https://user-images.githubusercontent.com/16493960/130937231-5e2fbeb5-37a2-4a1e-b76a-c5177a3d27e9.png)

Unplugging/replugging the device didnt help.

By the way, this seems to be the exact same issue as happened back in the days with the Tradfri integration;
https://github.com/Koenkk/zigbee2mqtt/issues/3767
The workaround, removing and rejoining the device, did not work in my case (aqara sp-euc01)

**Comment by tabnul** [comment]
Anyone can confirm this one?

**Comment by junknstuff** [comment]
If it's helpful, I also had the 2019 firmware shipped on my outlet SP-EUC01.  Initially, the WebGUI was not showing the update correct. It must have been corrected after a few updates (~2 months since I did the OTA update) because now it is showing the correct firmware on the Device and OTA GUI after (pics below for reference).

Here are my z2m info for comparison:
Zigbee2MQTT version: 1.21.1 commit: unknown
Coordinator type: zStack30x
Coordinator revision: 20201227
Frontend version: 0.6.0

![Screen Shot 2021-11-03 at 16 08 09](https://user-images.githubusercontent.com/11420141/140034083-7d4490a6-cedf-430a-9db3-04da697122e8.png)
![Screen Shot 2021-11-03 at 16 08 16](https://user-images.githubusercontent.com/11420141/140034096-9e4f2497-e6a6-42f3-8be0-39a3309ee88b.png)

**Comment by antti365** [comment]
Problem still exists. I just made an update, the version remains old.

![Снимок экрана 2021-12-05 в 01 39 24](https://user-images.githubusercontent.com/6865425/144727921-f2f25838-0c03-40c0-89bd-6c9a119df515.jpg)
![Снимок экрана 2021-12-05 в 01 40 15](https://user-images.githubusercontent.com/6865425/144727923-180a02be-5fe3-46cd-928d-bde05e0ead52.jpg)
![Снимок экрана 2021-12-05 в 01 40 47](https://user-images.githubusercontent.com/6865425/144727935-f2fe8f83-8c7f-4110-b434-f05b2eea59e2.jpg)
