### ISSUE TITLE
LCZ030 output of both temperature & humidity is null

### ISSUE THREAD

**Issue by geigervibe** [Koenkk/zigbee2mqtt#9054]
## What happened

I got a TuYa TS0201/LCZ030 Temperature & humidity & illuminance sensor with display but I can not join it fully resp. the configuration failed. When I attempt to join this device the log looks like this:

```
Zigbee2MQTT:error 2021-10-07 15:54:56: Failed to configure '0x804b50fffe028867', attempt 2 (Error: Bind 0x804b50fffe028867/1 genBasic from '0x00124b001949c846/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7))
```

and this is then the resulted state:

```
{
    "alarm_humidity": "off",
    "alarm_humidity_max": 90,
    "alarm_humidity_min": 20,
    "alarm_temperature": "off",
    "alarm_temperature_max": 40,
    "alarm_temperature_min": 10,
    "battery": null,
    "illuminance": 4772,
    "illuminance_lux": 3,
    "last_seen": "2021-10-07T15:57:49+02:00",
    "linkquality": 69,
    "humidity": null,
    "temperature": null
}
```

If I short click on the reset button of device, the battery value is then present but nothing more, even if I repeat that:

```
{
    "alarm_humidity": "off",
    "alarm_humidity_max": 90,
    "alarm_humidity_min": 20,
    "alarm_temperature": "off",
    "alarm_temperature_max": 40,
    "alarm_temperature_min": 10,
    "battery": 100,
    "illuminance": 4772,
    "illuminance_lux": 3,
    "last_seen": "2021-10-07T15:58:32+02:00",
    "linkquality": 66,
    "humidity": null,
    "temperature": null
}
```

I did re-join it more than 20 times (close to the coordinator and close repeaters are powered off) and short clicked the reset button on device more than 50 times... I also force removed this device some times... But it doesn't matter how often I repeat this, the picture is always the same. Here the entry out of the database.db file:

`
{"id":38,"type":"EndDevice","ieeeAddr":"0x804b50fffe028867","nwkAddr":2145,"manufId":4098,"manufName":"_TZ3000_qaaysllp","powerSource":"Battery","modelId":"TS0201","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":262,"inClusterList":[0,1,1024,57346],"outClusterList":[25,10],"clusters":{"msIlluminanceMeasurement":{"attributes":{"61441":50,"measuredValue":4772}},"manuSpecificTuya_2":{"attributes":{"alarm_temperature_max":40,"alarm_temperature_min":10,"alarm_humidity_max":90,"alarm_humidity_min":20,"alarm_temperature":2,"alarm_humidity":2,"unknown":0}},"genBasic":{"attributes":{"modelId":"TS0201","manufacturerName":"_TZ3000_qaaysllp","powerSource":3,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}}},"binds":[{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00124b001949c846","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b001949c846","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1775056678},"lastSeen":1633615045151}
`
## What did you expect to happen

See temperature & humidity values

## How to reproduce it (minimal and precise)

Join this device

## Debug info
Zigbee2MQTT version: 1.21.2-1 (hassio addon)
Homeassistant supervisor-2021.09.6/core-2021.9.6
Adapter hardware: CC2652P

I also tested current edge but same...

Any advice, is this integration is beta or is my device faulty? Thanks...

**Comment by geigervibe** [comment]
Hi @rsteininger , do you have any tuya-gateway? I do not have one, else I would test, if the sensor would work correctly within the tuya-cloud. I was looking for amazon customer feedbacks, but there are not many and nothing about missing values: [amazon](https://www.amazon.de/SOLE-HOME-Feuchtigkeit-Thermometer-Erforderlich/dp/B091KVFFY1)

**Comment by rsteininger** [comment]
That would have been a great idea, but no, unfortunately, I also only have a zigbee2mqtt based gateway ... no other zigbee gateways at hand ... maybe I should get one just for these instances for testing!

**Comment by geigervibe** [comment]
thanks for the hint. ordered a hub now, expect to test this at the weekend.

**Comment by rsteininger** [comment]
is there really no way to "emulate" whatever the tuya zigbee hub does as a battery change is a fairly common thing ... I had planned to install one of these in my mother-in-laws house but if it needs that special treatment every couple of months, then this is a no go for an other wise interesting device (illuminance + temp + humidity in a reasonably looking device).
Do we (@nukusinji) have any idea what the tuya hub might do initially? 
I ordered one but I am probably no good in troubleshooting / reverse engineering ...

**Comment by schlugges** [comment]
Temperature updates correlate with values on the display, so it does not seem to be related to zigbee

**Comment by geigervibe** [comment]
this device is even worse: even if it only reports the temperature in 1.1°C steps, it is floating the one and the same value in 8 seconds interval. So this device is using most size in the homeassistant database for nothing... wonder what drugs the developer has taken while programming the firmware...

**Comment by JDanRibeiro** [comment]
I also have the device and here I have the same temperature and humidity problem, in my environment I use a Zigbee Cc2531 Usb Adapter.

**Comment by Koenkk** [comment]
@schlugges could you make a sniff when pairing this device to the TuYa gateway? https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html#with-cc2531

**Comment by Antroxin** [comment]
I'm suffering the same issues with temperature and humidity. I notice for some comments in Aliexpress that was happening, but reading z2m documentation I thought thas was in previous versions. I have not a TuYa gateway for trying to do it as you mention. Other thing should be updating period.

**Comment by schlugges** [comment]
@Koenkk I tried to make a sniff. But it seems that I can can capture packets only when it's talking to zigbee2mqtt. Do you know if the Tuya Gateway uses a different channel or something like this?

**Comment by Koenkk** [comment]
@schlugges it probably does, only way to find out is to sniff on every channel starting from 11 till 26.

**Comment by ceaswaran** [comment]
![image](https://user-images.githubusercontent.com/40624146/143779092-9842e77d-09cc-4a2b-a6ba-6745d026d385.png)
Any Solution to report Temperature & Humidity?
Please help

**Comment by RaW79** [comment]
Can confirm that after pairing LCZ030 to Tuya gateway once the device is also submitting T&H.
But this functionality seems no to be activated for ever. After removing the battery this gone and the device has to be paired again to a Tuya gateway. So finding this activiation step for replication without Tyua gateway would be great.

**Comment by Antroxin** [comment]
Maybe that would be the solution, to replicate the behaivour of Tuya gateway when pairing this device just to turn on exposing T&H.

**Comment by DaveDavenport** [comment]
Could the https://www.zigbee2mqtt.io/devices/LCZ030.html#tuya-lcz030 be updated to state this information.
I bought 3 of these as they where listed to work, and they are not.

**Comment by dlarge51** [comment]
Same problem, no values. I've connected the device to a trust z1, but this doesn't make a difference. I have still only null values in domoticz.

**Comment by jeykodev** [comment]
I also bought the devices based on the info page: https://www.zigbee2mqtt.io/devices/LCZ030.html#tuya-lcz030

There should be a warning for users!

Anyway, are there any new informations on this topic?

**Comment by StuartHaire** [comment]
Bought this before finding out about this issue. 

Have there been any findings on how to get full functionality without the tuya gateway/hub? 
Don't really want to spend the money on this to have it sit around after being used just to get this one thing working..

**Comment by SolarstormTM** [comment]
I should get my TuYa gateway tomorrow.
I will try to record the pairing with Wireshark and post it here.
Maybe that will help finding a solution.

**Comment by SolarstormTM** [comment]
I captured the initial traffic with wireshark now.
I just have to figure out how to export the decrypted Messages without my mesh key.
Perhaps anyone can give me a hint.

**Comment by StuartHaire** [comment]
@SolarstormTM I've never done it before, guessing @Koenkk can help here. Hopefully someone can help!

**Comment by HugeMissedSteak** [comment]
> I captured the initial traffic with wireshark now. I just have to figure out how to export the decrypted Messages without my mesh key. Perhaps anyone can give me a hint.

Does [this "Build a Zigbee CC2531 Sniffer & How to Use it" guide](https://community.oh-lalabs.com/t/guide-build-a-zigbee-cc2531-sniffer-how-to-use-it/469) provide you with the details (see chapter 2 for decryption)? (zboss [download credentials](http://bugmenot.com/view/zboss.dsr-wireless.com)) Found it [here](https://github.com/zigpy/zha-device-handlers/issues/862#issuecomment-862221932):
> oh, I simply add 5a6967426565416c6c69616e63653039 key from [this link](https://community.oh-lalabs.com/t/guide-build-a-zigbee-cc2531-sniffer-how-to-use-it/469)

That is from a simular discussion: [[Device Support Request] Neo Tuya Temperature, Humidity and Illumination Sensor TS0201 _TZ3000_qaaysllp #862](https://github.com/zigpy/zha-device-handlers/issues/862) 
Where there is also a good indication how the implementation might look like: https://github.com/zigpy/zha-device-handlers/issues/862#issuecomment-986903211
> btw, I had a similar issue with a zemismart (tuya) smart plug recently (_TZ3000_rdtixbnu). It wouldn't start reporting endpoint 2. By sniffing the traffic I mimicked the requests on z2m and got it working: ![image](https://user-images.githubusercontent.com/11080704/144877588-86be7962-ff0c-4f07-bfe7-abcf13c8c163.png)
> 
> maybe it's just as simple with this sensor...

**Comment by SolarstormTM** [comment]
I got the data encrypted, but i don't want to upload the Wireshark recording which contains my TuYa key.
![grafik](https://user-images.githubusercontent.com/10888722/148567382-fd776140-b2eb-4994-a4ab-70a2bb24197d.png)

**Comment by HugeMissedSteak** [comment]
Continuing on the work done previously in this thread:
> "Warning. For using all function (temperature, and humidity) have to paring with tuya Hub once. If it did't, can be use just illuminance." [Koenkk/zigbee-herdsman-converters#3081](https://github.com/Koenkk/zigbee-herdsman-converters/pull/3081)

Using [this same device](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/tuya.js#L1653) as the base for my custom external convertor, and following thise excellent guide to add my custom device: [Support new devices](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_1-pairing-the-device-with-zigbee2mqtt). Additionally i have been using this guide: [Support new Tuya devices](https://www.zigbee2mqtt.io/advanced/support-new-devices/02_support_new_tuya_devices.html#_5-adding-your-first-data-point)

I am able to read the humidity and temperature from the device! And since I do not own a tuya hub, this device has never been connected to anything except zigbee2mqtt. I have been messing with the scripts and settings however, so I should pull the batteries out and try fresh to see if there was anything additional needed that I removed by now.

**Zigbee2mqtt configuration**
```yaml
external_converters:
  - LCZ030-custom.js
```

**/config/zigbee2mqtt/LCZ030-custom.js**
```js
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [{modelID: 'TS0201', manufacturerName: '_TZ3000_qaaysllp'}],
    model: 'LCZ030',
    vendor: 'TuYa',
    description: 'Temperature & humidity & illuminance sensor with display',
    fromZigbee: [fz.battery, fz.illuminance, fz.ts0201_temperature_humidity_alarm, fz.tuya_illuminance_temperature_humidity_sensor],
    toZigbee: [],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic', 'genPowerCfg']);
    },
    meta: {multiEndpoint: true},
    endpoint: (device) => {
        return {'left': 1, 'center': 2};
    },
    exposes: [/*e.temperature(),*/ e.humidity(), e.battery(), e.illuminance(), e.illuminance_lux(),
        exposes.numeric('temperature_center', ea.STATE).withUnit('°C').withDescription('Temperature'),
        exposes.numeric('alarm_temperature_max', ea.STATE).withUnit('°C').withDescription('Alarm temperature max'),
        exposes.numeric('alarm_temperature_min', ea.STATE).withUnit('°C').withDescription('Alarm temperature min'),
        exposes.numeric('alarm_humidity_max', ea.STATE).withUnit('%').withDescription('Alarm huminity max'),
        exposes.numeric('alarm_humidity_min', ea.STATE).withUnit('%').withDescription('Alarm huminity min'),
        exposes.enum('alarm_humidity', ea.STATE, ['below_min_humdity', 'over_humidity', 'off']).withDescription('Alarm humidity status'),
        exposes.enum('alarm_temperature', ea.STATE, ['below_min_temperature', 'over_temperature', 'off']).withDescription('Alarm temperature status'),
    ],
};
    
module.exports = definition;
```
**Returned json payload in zigbee2mqtt:**
```json
{
    "alarm_humidity": "off",
    "alarm_humidity_max": 90,
    "alarm_humidity_min": 20,
    "alarm_temperature": "off",
    "alarm_temperature_max": 40,
    "alarm_temperature_min": 10,
    "battery": 100,
    "humidity": 43.5,
    "illuminance": 16336,
    "illuminance_lux": 43,
    "linkquality": 31,
    "temperature_center": 22.3
}
```
**Zigbee2mqtt result**
![Temperature and humidity](https://user-images.githubusercontent.com/56737876/148587595-b1f837bf-aa93-4339-8ac0-e8965f958b04.png)

I think the suffix on `temperature_center` comes from the endpoint mapping: `return {'left': 1, 'center': 2};`. Additionally have enabled the `multi_endpoint`, these changes result in the endpoint 2 returned on my clusters tab in zigbee2mqtt.

Key differences:
![Differences](https://user-images.githubusercontent.com/56737876/148590371-e20f3234-b0ad-49c3-8869-ab54a9b3610b.png)

So now we need to clean everything up, and add it to the code base so that this device has full support!

**Comment by HugeMissedSteak** [comment]
I have been experimenting a bit with this device and different configurations. It seems to me that the key to getting this device to report its values is to **read** it's attributes. 
This is the request equal to the _response_ that @SolarstormTM posted above (his post is the request), here is a _request_ in wireshark:

![read attributes request](https://user-images.githubusercontent.com/56737876/148620483-caa2c045-bd16-4c7f-900e-2160584a465b.png)

If I simulate this, using this convertor:
```javascript
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [{modelID: 'TS0201', manufacturerName: '_TZ3000_qaaysllp'}],
    model: 'LCZ030',
    vendor: 'TuYa',
    description: 'Temperature & humidity & illuminance sensor with display',
    fromZigbee: [
        fz.battery, 
        fz.temperature, 
        fz.humidity, 
        fz.illuminance
    ],
    toZigbee: [],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic', 'genPowerCfg']);
        
        await endpoint.read('genBasic', [
            0x0004, // Manufacturer Name
            0x000,  // ZCL Version
            0x0001, // Application Version
            0x0005, // Model Identifier
            0x0007, // Power Source
            0xfffe  // Unknown
        ]);
    },
    exposes: [e.temperature(), e.humidity(), e.battery(), e.illuminance(), e.illuminance_lux() ],
};
    
module.exports = definition;
```
Then I get all the fields that are displayed on the device. These update when there is a change in the value (temperature when updated on the display), and for the battery also when you short press the reset button. illuminance seems to be triggered very frequent (every few seconds), even when there is no change measured.
![results](https://user-images.githubusercontent.com/56737876/148620801-16b359f8-be8c-42f8-a89c-ed0108b4103f.png)

This has been tested by removing the device from zigbee2mqtt, then removing the battery from the device, and repairing the device. Which I hadn't performed with my previous script, and I might have read these attributes before.

Notice that in the above example, there are no TUYA specific instructions or datapoints. Although it seems to report values from different clusters as well, including tuya specific datapoints:
```
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":0}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffed10efb', payload '{"battery":100,"humidity":45.9,"illuminance":0,"illuminance_lux":0,"linkquality":34,"temperature":22.2}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":7540}' from endpoint 2 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffed10efb', payload '{"battery":100,"humidity":75.4,"illuminance":0,"illuminance_lux":0,"linkquality":34,"temperature":22.2}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":7540}' from endpoint 2 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffed10efb', payload '{"battery":100,"humidity":75.4,"illuminance":0,"illuminance_lux":0,"linkquality":34,"temperature":22.2}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":7540}' from endpoint 2 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffed10efb', payload '{"battery":100,"humidity":75.4,"illuminance":0,"illuminance_lux":0,"linkquality":34,"temperature":22.2}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":9010}' from endpoint 2 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffed10efb', payload '{"battery":100,"humidity":90.1,"illuminance":0,"illuminance_lux":0,"linkquality":34,"temperature":22.2}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":9010}' from endpoint 2 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffed10efb', payload '{"battery":100,"humidity":90.1,"illuminance":0,"illuminance_lux":0,"linkquality":34,"temperature":22.2}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":9010}' from endpoint 2 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffed10efb', payload '{"battery":100,"humidity":90.1,"illuminance":0,"illuminance_lux":0,"linkquality":34,"temperature":22.2}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'manuSpecificTuya_2', data '{"alarm_humidity":1}' from endpoint 1 with groupID 0
Debug No converter available for 'LCZ030' with cluster 'manuSpecificTuya_2' and type 'attributeReport' and data '{"alarm_humidity":1}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":0}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffed10efb', payload '{"battery":100,"humidity":90.1,"illuminance":0,"illuminance_lux":0,"linkquality":34,"temperature":22.2}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":2370}' from endpoint 2 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffed10efb', payload '{"battery":100,"humidity":90.1,"illuminance":0,"illuminance_lux":0,"linkquality":34,"temperature":23.7}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":2370}' from endpoint 2 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffed10efb', payload '{"battery":100,"humidity":90.1,"illuminance":0,"illuminance_lux":0,"linkquality":34,"temperature":23.7}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":2370}' from endpoint 2 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffed10efb', payload '{"battery":100,"humidity":90.1,"illuminance":0,"illuminance_lux":0,"linkquality":34,"temperature":23.7}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":9470}' from endpoint 2 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffed10efb', payload '{"battery":100,"humidity":94.7,"illuminance":0,"illuminance_lux":0,"linkquality":31,"temperature":23.7}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":15052}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffed10efb', payload '{"battery":100,"humidity":94.7,"illuminance":15052,"illuminance_lux":32,"linkquality":34,"temperature":23.7}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":8610}' from endpoint 2 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffed10efb', payload '{"battery":100,"humidity":86.1,"illuminance":15052,"illuminance_lux":32,"linkquality":34,"temperature":23.7}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":8610}' from endpoint 2 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffed10efb', payload '{"battery":100,"humidity":86.1,"illuminance":15052,"illuminance_lux":32,"linkquality":34,"temperature":23.7}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":8610}' from endpoint 2 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffed10efb', payload '{"battery":100,"humidity":86.1,"illuminance":15052,"illuminance_lux":32,"linkquality":34,"temperature":23.7}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'manuSpecificTuya_2', data '{"alarm_humidity":2}' from endpoint 1 with groupID 0
Debug No converter available for 'LCZ030' with cluster 'manuSpecificTuya_2' and type 'attributeReport' and data '{"alarm_humidity":2}'
Debug Received Zigbee message from '0xcc86ecfffed10efb', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":15186}' from endpoint 1 with groupID 0
```

When I then reenable the temperature_humidity_alarm (as it seems to indeed report these settings), strangely enough the reporting of the temperature and illuminance stops again, and the reporting seem to be slower (maybe only on display changes):
```javascript
fromZigbee: [
        // added this field to convertor above
        fz.ts0201_temperature_humidity_alarm
    ],
    exposes: [
        // added these fields to convertor above
        exposes.numeric('alarm_temperature_max', ea.STATE).withUnit('°C').withDescription('Alarm temperature max'),
        exposes.numeric('alarm_temperature_min', ea.STATE).withUnit('°C').withDescription('Alarm temperature min'),
        exposes.numeric('alarm_humidity_max', ea.STATE).withUnit('%').withDescription('Alarm huminity max'),
        exposes.numeric('alarm_humidity_min', ea.STATE).withUnit('%').withDescription('Alarm huminity min'),
        exposes.enum('alarm_humidity', ea.STATE, ['below_min_humdity', 'over_humidity', 'off']).withDescription('Alarm humidity status'),
        exposes.enum('alarm_temperature', ea.STATE, ['below_min_temperature', 'over_temperature', 'off']).withDescription('Alarm temperature status')
    ]
``` 
![with ts0201_temperature_humidity_alarm](https://user-images.githubusercontent.com/56737876/148623077-929ae3bd-22af-42c0-949d-806936d7a7aa.png)

But as it seems, a lot of these configurations can be configured and controlled. So currently I am using this script:
```javascript
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const constants = require('zigbee-herdsman-converters/lib/constants');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [{modelID: 'TS0201', manufacturerName: '_TZ3000_qaaysllp'}],
    model: 'LCZ030',
    vendor: 'TuYa',
    description: 'Temperature & humidity & illuminance sensor with display',
    fromZigbee: [
        fz.battery, 
        fz.temperature, 
        fz.humidity, 
        fz.illuminance,
        fz.ts0201_temperature_humidity_alarm
    ],
    toZigbee: [],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        
        await endpoint.read('genBasic', [
            0x0004, // Manufacturer Name
            0x000,  // ZCL Version
            0x0001, // Application Version
            0x0005, // Model Identifier
            0x0007, // Power Source
            0xfffe  // Unknown
        ]);
        
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic', 'genPowerCfg', 'msTemperatureMeasurement', 'msIlluminanceMeasurement', 'msRelativeHumidity', 'manuSpecificTuya_2']);
        
        //Works, but not needed when binding to manuSpecificTuya_2
        //await endpoint.read('manuSpecificTuya_2', ['alarm_temperature_max', 'alarm_temperature_min', 'alarm_humidity_max', 'alarm_humidity_min', 'alarm_humidity', 'alarm_temperature']);
        
        //These report configuration parameters seem to fail
        //await reporting.temperature(endpoint, {change: 1});
        //await reporting.illuminance(endpoint, {min: constants.repInterval.MINUTE, max: constants.repInterval.HOUR, change: 100});
        //await reporting.batteryPercentageRemaining(endpoint);
        //await reporting.humidity(endpoint);
    },
    exposes: [
        e.temperature(),
        e.humidity(),
        e.battery(),
        //e.battery_low(),
        e.illuminance(),
        e.illuminance_lux(),
        exposes.numeric('alarm_temperature_max', ea.STATE).withUnit('°C').withDescription('Alarm temperature max'),
        exposes.numeric('alarm_temperature_min', ea.STATE).withUnit('°C').withDescription('Alarm temperature min'),
        exposes.numeric('alarm_humidity_max', ea.STATE).withUnit('%').withDescription('Alarm huminity max'),
        exposes.numeric('alarm_humidity_min', ea.STATE).withUnit('%').withDescription('Alarm huminity min'),
        exposes.enum('alarm_humidity', ea.STATE, ['below_min_humdity', 'over_humidity', 'off']).withDescription('Alarm humidity status'),
        exposes.enum('alarm_temperature', ea.STATE, ['below_min_temperature', 'over_temperature', 'off']).withDescription('Alarm temperature status')
    ]
};
    
module.exports = definition;
```

Which seem to work pretty well:
![all values](https://user-images.githubusercontent.com/56737876/148629814-4f187f5d-a882-43f2-8176-23bdd8335b86.png)
This also works when taking the battery out plus reconnecting. It also reads the battery without short pressing the reset button.
Note that I now removed the multi endpoint, and the endpoint binding. This also removes the temperature_center weirdness

**Comment by Koenkk** [comment]
@HugeMissedSteak this read requests makes a lot of sense, I've just added the same for another TuYa device. https://github.com/Koenkk/zigbee-herdsman-converters/commit/ab434284e8073bdb8a0e47ecc6b7b4288dff8207 

Could you make a pr?

**Comment by HugeMissedSteak** [comment]
> @HugeMissedSteak this read requests makes a lot of sense, I've just added the same for another TuYa device. [Koenkk/zigbee-herdsman-converters@ab43428](https://github.com/Koenkk/zigbee-herdsman-converters/commit/ab434284e8073bdb8a0e47ecc6b7b4288dff8207)
> 
> Could you make a pr?

Cool! Thanks for confirming! I have created the [PR](https://github.com/Koenkk/zigbee-herdsman-converters/pull/3644). 
Regarding to your [issue](https://github.com/Koenkk/zigbee2mqtt/issues/9057#issuecomment-1007771295), couldn't that be the same type of problem as I had with this device? As in that you need to bind the clusters to an endpoint to receive the measurements?
```javascript
await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic', 'genPowerCfg', 'msTemperatureMeasurement', 'msIlluminanceMeasurement', 'msRelativeHumidity', 'manuSpecificTuya_2']);
``` 

If I should rename `0xfffe` to `'attributeReportingStatus'` as [discused on your referenced thread](https://github.com/Koenkk/zigbee2mqtt/issues/9057#issuecomment-1007986328), the please let me know.

**Comment by Koenkk** [comment]
@HugeMissedSteak even with binding it doesn't work, I've checked it with the original gateway, seems it only polls

Thanks to @HugeMissedSteak this issue should be fixed now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by tobi1449** [comment]
Any idea why my unit might still not report temp and humidity?
I'm on the latest version (as of yesterday) of z2m and I have already removed the batteries and re-paired it.

**Comment by thoogveldHU** [comment]
> Any idea why my unit is still not reporting temp and humidity?
> I'm on the latest version (as of yesterday) of z2m and I have already removed the batteries and re-paired it.

It's not on the release branch, are you on dev or release?

**Comment by tobi1449** [comment]
> > Any idea why my unit is still not reporting temp and humidity?
> > I'm on the latest version (as of yesterday) of z2m and I have already removed the batteries and re-paired it.
> 
> It's not on the release branch, are you on dev or release?

I‘m on 1.22.2-dev commit: b6d26e3 which should already include the PR for this.

**Comment by ede-kowalski** [comment]
> It's not on the release branch, are you on dev or release?

Does anyone knows when it will be available on the stable release branch?

**Comment by Koenkk** [comment]
> Does anyone knows when it will be available on the stable release branch?


1 February

**Comment by BrEr** [comment]
Sorry for the bump. Whilst this pull request fixes the issue the update rate of the sensor is still extremely low. A big quick change (such as breathing on the device) triggers an update. Pressing the reset button short triggers and update. But it seems that slow changes don't result in an update. I am staring at the device reporting 23.7 now while the last reported value is 24.9.

Is there a way to enable periodic polling or something?

**Comment by douglas-srs** [comment]
Do I still need Tuya Hub to get full functionality on this device?

**Comment by stmcodes** [comment]
@douglas-srs 
I bought the LCZ030 and it worked out of the box with z2m without first pairing it with the tuya hub.
